### ISSUE TITLE
[BUG]: issue title

### ISSUE THREAD

**Issue by RamitK** [microsoft/powerapps-tools#850] opened 2021-03-18 14:02 UTC
**Description**
"Microsoft Teams Admin | Weekly Clean Up of Microsoft Teams environments" flow is actually able to delete the Teams environment but throwing "statusCode":404,"message":"Resource not found" and failing.

**Component:**
 - Solution Center of Excellence - Governance Components 
 - Version 1.28
 - Flow Microsoft Teams Admin | Weekly Clean Up of Microsoft Teams environments

**Screenshots**

![image](https://user-images.githubusercontent.com/39703138/111638736-a1cf9900-8820-11eb-9acc-f563d786e5ea.png)

**Comment by manuelap-msft** [comment] 2021-03-18 15:17
Hello,

this is a duplicate of #764 and was fixed in our latest release. You're on an old version of the Governance components, so will need to upgrade to get the latest version.

lease be sure to remove any unmanaged layers from flows before you update as described in[ installing updates](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#installing-updates) or you will not see the changes.

Thanks for using the CoE
Manuela

**Closed by manuelap-msft** 2021-03-18 15:17 UTC
Labels: coestarterkit

**Comment by RamitK** [comment] 2021-03-19 08:13
Thanks Manuela! We will do the upgrade as you suggested.
