### ISSUE TITLE
[BUG]: Admin | Sync Template v3 (Apps) & (Flows) Error - 'item/admin_userisserviceprinciple'

### ISSUE THREAD

**Issue by anton3sco** [microsoft/powerapps-tools#1007] opened 2021-05-06 19:34 UTC
**Describe the bug**
When turning on the Admin | Sync Template v3 (Apps) & Admin | Sync Template v3 (Flows) workflows for the first time after the initial upload, I get the following error: 

Your flow could not turn on: Admin | Sync Template v3 (Apps). Error: Flow client error returned with status code "BadRequest" and details "{"error":{"code":"InvalidOpenApiFlow","message":"Flow save failed with code 'WorkflowOperationParametersExtraParameter' and message 'The API operation does not contain a definition for parameter 'item/admin_userisserviceprinciple'.'."}}".

Please note that the other flows related to this step were turned on without issue.

****

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [Core]
 - Version [1.7]
 - App or Flow [Admin | Sync Template v3 (Apps) & Admin | Sync Template v3 (Flows)]

**To Reproduce**
1. Go to your dataverse environment
2. Select view all
3. Select cloud flows
4. Select the flow "Admin | Sync Template v3 (Apps)"
5. Turn on "Admin | Sync Template v3 (Apps)"
4. See error: Your flow could not turn on: Admin | Sync Template v3 (Apps). Error: Flow client error returned with status code "BadRequest" and details "{"error":{"code":"InvalidOpenApiFlow","message":"Flow save failed with code 'WorkflowOperationParametersExtraParameter' and message 'The API operation does not contain a definition for parameter 'item/admin_userisserviceprinciple'.'."}}".

**Expected behavior**
The other workflows turned on without issue, giving a green banner that it had successfully turned on.

**Screenshots**
<img width="464" alt="Snag_22eab255" src="https://user-images.githubusercontent.com/26906102/117355253-f59d4c80-ae77-11eb-864e-c92aa6df774f.png">

**Additional context**
This is a brand new tenant I am installing this on. I will try this with another tenant in the meantime. Many thanks for considering my request.

**Comment by manuelap-msft** [comment] 2021-05-06 20:17
Hello,

thank you for letting us know! Looks like a bug on our side where we missed to add a new field we're using to the teams version of the solution. Please give me an hour, and I'll upload a new version where this will work and will post here to let you know when it's ready.

Sorry for the inconvenience,
Manuela

**Comment by anton3sco** [comment] 2021-05-06 20:46
No problem at all! Happy to do my small part. Thank you for all the hard work!

**Comment by manuelap-msft** [comment] 2021-05-06 20:49
Hello,

I just uploaded a new version and I tested turning on the flows in a Teams environment, and it worked, so I think the issue is fixed now. Could you try upgrading what you have imported / or installing to a new Teams environment the new version (1.96) and let me know if you still experience issues!

Thank you
Manuela

**Comment by anton3sco** [comment] 2021-05-07 00:36
That did the trick! I imported over the current solution, and it immediately reflected your changes resolving the issues. Thank you!

**Comment by manuelap-msft** [comment] 2021-05-07 15:59
Hello,

sorry again! Here's the new version - this time I turned on all the flows when testing and it looks like it's succeeding now. Let me know if you continue to see issues. Thank you for your patience!

[CenterofExcellenceCoreComponentsTeams_1_97_managed.zip](https://github.com/microsoft/powerapps-tools/files/6442905/CenterofExcellenceCoreComponentsTeams_1_97_managed.zip)

**Comment by manuelap-msft** [comment] 2021-05-12 11:54
Closing this issue, as I think we resolved it with the latest release. Let me know if you continue to see issues! Thank you for using the CoE!

**Closed by manuelap-msft** 2021-05-12 11:54 UTC
Labels: coestarterkit

**Comment by anton3sco** [comment] 2021-05-12 17:06
You bet, this worked! Thank you again!! Life saver!
