### ISSUE TITLE
SETUP REQUIRED | Admin | Find and add admins as owners for apps that leverage certain connectors SETUP REQUIRED | Admin | Find and add admins as owners for apps that leverage certain connectors

### ISSUE THREAD

**Issue by aakashpatel660** [microsoft/powerapps-tools#407] opened 2020-08-03 13:57 UTC
**Describe the bug**
When the flow run it throws the error message - The solution aware canvas application could not be shared with a security group with edit or share permissions. Cannot add admin to the application if they are using certain connector. 

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Center of Excellence - Governance Components
 - Version - 1.18
 - Flow SETUP REQUIRED | Admin | Find and add admins as owners for apps that leverage certain connectors SETUP REQUIRED | Admin | Find and add admins as owners for apps that leverage certain connectors

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/59940632/89190660-c3b92b80-d56f-11ea-9938-700e868f8d0b.png)

**Additional context**
{
  "error": {
    "code": "SolutionAppCanEditShareNotAllowedWithGroups",
    "message": "The solution aware canvas application could not be shared with a security group with edit or share permissions"
  }
}

**Comment by JeneferM-MSFT** [comment] 2020-08-03 16:10
Thank for using CoE. This issue is already known and track via:
Duplicate of #304 

Product does not yet support this. We are following up but cannot fix until then.

**Closed by JeneferM-MSFT** 2020-08-03 16:10 UTC
Labels: coestarterkit
