### ISSUE TITLE
CLEANUP - Admin | Sync Template v2 (Power Apps User Shared With)

### ISSUE THREAD

**Issue by raj835** [microsoft/powerapps-tools#748] opened 2021-02-02 16:33 UTC
![CLEANUP-AdminSyncTemplate v2 (Power Apps User Shared With)](https://user-images.githubusercontent.com/66004078/106630960-5039ba80-65a2-11eb-943f-3f43130798af.PNG)
**Describe the bug**

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [Core,]

When I am running the flow ,its getting failed .

**Comment by JeneferM-MSFT** [comment] 2021-02-02 16:43
Hello I'm afraid I need more information in order to assist

First, what version of core are you using?

Then, please dive down into that action until you see the actual point of failure and return with the screen capture and the error output. Right now I just know what action failed but not in what way.

This is the action, but I need the error message
![image](https://user-images.githubusercontent.com/62659043/106632496-aa9b3280-6532-11eb-890f-caddbe83152e.png)

**Comment by raj835** [comment] 2021-02-03 03:13
![Env2](https://user-images.githubusercontent.com/66004078/106693056-aedf5280-65fb-11eb-8a4a-259a0a2c190d.PNG)
![Env3](https://user-images.githubusercontent.com/66004078/106693061-b0a91600-65fb-11eb-8e1a-5c324a942efa.PNG)
![Env4](https://user-images.githubusercontent.com/66004078/106693062-b141ac80-65fb-11eb-9b86-ef40de1fba58.PNG)
![Env5](https://user-images.githubusercontent.com/66004078/106693063-b141ac80-65fb-11eb-9cba-439f360daef9.PNG)
![Getenv1](https://user-images.githubusercontent.com/66004078/106693065-b1da4300-65fb-11eb-9afb-aa93b7173658.PNG)
![Output_GetEnv](https://user-images.githubusercontent.com/66004078/106693068-b272d980-65fb-11eb-8b20-0047a2fe4c73.PNG)


I get 400 error in all the failed environments .
How  do i find the version of core solution.I downloaded it from MS link 2 weeks back .

**Comment by JeneferM-MSFT** [comment] 2021-02-03 12:46
Yes it appears you have an old version, because you are running a v2 of the sync flows, something I didn't notice at first. 

The issue you have failed on is that the compose isn't getting you the correct id, so its failing for envts with pre-fixes like legacy- and default-.  I just confirmed that this bug does not exist in the current v3 versions of the sync flows. 

v3 was already in place 2 weeks ago though so something went wrong in your upgrade. 

Here are some tips
1) To see current version, browse to solutions page for the environment in which you have the CoE, you will see versions there
![image](https://user-images.githubusercontent.com/62659043/106748398-0a004d80-65da-11eb-9ecd-7f798b4e0835.png)

2) This upgrade will create new flows (v3) and delete old flows (v2). You should see something like this when complete
![image](https://user-images.githubusercontent.com/62659043/106748705-754a1f80-65da-11eb-9b58-d37ac963e283.png)

3) Upgrade requires you to remove unmanaged layers on every flow in order to succeed. This is described in [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates).

4) You may have created copies of the v2 flows which is why you are still seeing them and using them. This does not appear to be the case from the name of the flow, but something to double check in case. If these still exist, delete them after upgrade and use the V3 versions from within the solution.

**Comment by JeneferM-MSFT** [comment] 2021-02-03 12:46
Given that this issue is no longer current in the shipping bits, I will go ahead and close this. 
Thanks for using CoE

**Closed by JeneferM-MSFT** 2021-02-03 12:46 UTC
Labels: coestarterkit
