### ISSUE TITLE
[BUG]: Error Code 80041A06

### ISSUE THREAD

**Issue by djambo70** [microsoft/powerapps-tools#855] opened 2021-03-19 10:47 UTC
**Describe the bug**
Trying to upgrade CoE core Components to 1.98 fails with ErrorCode 80041A06
**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: CenterofExcellenceCoreComponent
 - Version: 1.45

**To Reproduce**
1. Import Solution
2. Select File CenterofExcellenceCoreComponents_1_98_managed (1).zip
3. Fails
4. ErrorCode 80041A06, Exception message Attribute admin_rpamodifiedon is a String, but a DateTime type was specified. Patch: No

**Expected behavior**
Successful import of the solution

**Screenshots**
![image](https://user-images.githubusercontent.com/6538198/111768601-6d072480-88a8-11eb-8a68-77b370e27395.png)

**Additional context**

**Comment by manuelap-msft** [comment] 2021-03-19 12:11
Hello, you will need to upgrade to the interim solution (1.62) shown in #515
And then try again to upgrade to the latest version

Thanks for using CoE!
Closing as duplicate of #515

**Closed by manuelap-msft** 2021-03-19 12:11 UTC
Labels: coestarterkit
