### ISSUE TITLE
[BUG]: CoE Components (Template Catalog)

### ISSUE THREAD

**Issue by Daleyon** [microsoft/powerapps-tools#225] opened 2020-04-15 22:02 UTC
**Describe the bug**
Attempting to import the CoE Components related to the Template Catalog (https://docs.microsoft.com/en-us/power-platform/guidance/coe/modify-components#controls-provided-in-the-template-catalog-app). Receiving error: "There was a problem importing "Component name". This app cannot be edited with this version of Power Apps. Please go to make.powerapps.com and use Power Apps Studio to edit this app."

**Component (please tell us which flow or app you are experiencing issues with):**
https://github.com/microsoft/powerapps-tools/raw/master/Administration/CoEStarterKit/Individual%20Components/CoE%20Components.zip

**To Reproduce**
Download
1. Go to 'https://github.com/microsoft/powerapps-tools/raw/master/Administration/CoEStarterKit/Individual%20Components/CoE%20Components.zip'
2. 'Unzip (while keeping original zip)'

Power Apps Component Library Route
1. Go to 'https://make.powerapps.com/'
2. Go to 'Component Library'
3. Click on 'Edit'
4. Click on 'Components Tab', 'Import components', 'Upload file' 
5. Select 'msapp file (4 possible components but only selected 1)'
6. See error

Power Apps New App Route
1. Go to 'https://make.powerapps.com/'
2. Go to 'New App -> Canvas'
3. Click on 'Components Tab', 'Import components', 'Upload file' 
4. Select 'msapp file (4 possible components but only selected 1)'
5. See error

Power Apps Open App Route
1. Go to 'https://us.create.powerapps.com/studio/#'
2. Click on 'Open' 
3. Click on 'Browse File' 
4. Select 'msapp file (4 possible components but only selected 1)'
5. See error

Power Apps Import Canvas App Route
1. Go to 'https://make.powerapps.com/'
2. Click on 'Import canvas app'
3. Click on 'Upload' 
4. Select 'zip file'
5. See error

Power Apps Template Catalog Route
1. Go to 'https://make.powerapps.com/'
2. Go to 'Template Catalog Canvas App"'
3. Click on 'Edit'
3. Click on 'Components Tab', 'Import components', 'Upload file' 
4. Select 'msapp file (4 possible components but only selected 1)'
5. See error

**Expected behavior**
Import component without issues and to use component for its intended purpose.
https://docs.microsoft.com/en-us/power-platform/guidance/coe/modify-components#controls-provided-in-the-template-catalog-app

**Screenshots**
![image](https://user-images.githubusercontent.com/17080282/79393268-ff89a000-7f42-11ea-8c29-c8d093a07753.png)

**Additional context**
Environment allows Components and related App allows Components.

Power Apps Studio Session Details:
Timestamp: 2020-04-15T21:28:34.663Z
Session ID: e451d3d0-7f5f-11ea-8628-91227a1a3f65
Tenant ID: 7480c3de-a79c-42a2-95cd-a35cf14f9b3f
Object ID: 0cc82be5-72b3-4a4a-a77d-b5f6f564193f
Build name: 0.0.20200415.3-2004.1-prod

Power Apps Release: 3.20023.8

**Comment by JeneferM-MSFT** [comment] 2020-04-15 22:28
Thank you, we are able to reproduce this and are investigating.

**Comment by Daleyon** [comment] 2020-04-15 22:30
Thank you!

Best regards,
Dale Yon
Mobile App Services (FIIW42)
Mobility & Internet Publishing

Zoom Community:
Power Apps and Power Automate Forum<https://zoom.zf-world.com/sites/com14/groups/18893/SitePages/Home.aspx>

Microsoft Power Platform:
Microsoft Power Apps<https://powerapps.microsoft.com/en-us/>
Microsoft Power Automate<https://flow.microsoft.com/en-us/>
Microsoft Power BI<https://powerbi.microsoft.com/en-us/>

[cid:image001.png@01D61353.EBBB9200]

ZF North America, Inc.
Corporate Finance, IT, M&A
2846 North Old Laurens Road, Gray Court, South Carolina 29645, USA
Phone: +1 (864) 601-2698, Mobile: +1 (586) 651-4793
dale.yon@zf.com<mailto:dale.yon@zf.com>

**Comment by JeneferM-MSFT** [comment] 2020-04-16 18:35
Thanks again for taking the time to let us know about this issue. The components were created in a tenant that had new bits for the Power Platform. The apps will not be available to you to open for a few weeks until those bits are released to Production. 
Our next set of documents will hide reference to these until they are available, so thanks for reporting so other people did not run in to the same issue. 

In the meantime, you can use these components released in the past by one of our colleagues.
[PowerApps - Ten Reusable Components](https://powerapps.microsoft.com/en-us/blog/powerapps-ten-reusable-components/
)

**Closed** 2020-04-20 13:20 UTC
Labels: coestarterkit

**Comment by DennisGaida** [comment] 2020-04-27 09:15
I just had to sleuth my way around to only find this closed issue. The "CoE Components.zip" are still included in the default CoEStarterKit, but are not mentioned anywhere in the documentation. I had to run through the same steps as the OP and wasted time only to now find out I can't import the components since they are require newer features than my tenant has.

Please remove the components from the release and I don't think this issue is resolved until the components are removed from the download or fixed in a way that it works with other tenants.
