### ISSUE TITLE
[BUG]: Pagination Policy error on copy of Admin | Sync Template v2 (Custom Connectors)

### ISSUE THREAD

**Issue by tcamozzi** [microsoft/powerapps-tools#428] opened 2020-08-18 15:09 UTC
**Describe the bug**
Created a copy of the flow.  Can't save it as I get an error.  "The pagination policy of workflow run action 'Find_connector_record' of type 'ApiConnection' at line '1' and column '5555' is not valid...."

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution= Core
 - Version 1.54
 - Flow = Admin | Sync Template v2 (Custom Connectors)

**To Reproduce**
1. Go to Solutions > Center of Excellence - Core Components > find Admin | Sync Template v2 (Custom Connectors) flow.
2. Click on '....' and then Details
3. In flow, select Save As from the menu.  
4. Continue past the connectors dialog box.
5. Save as copy
6. See error

**Expected behavior**
Expected the flow to save as the other flows have.

**Screenshots**
![image](https://user-images.githubusercontent.com/49409486/90530578-e596de80-e129-11ea-98ff-5a9c6bd0242b.png)

**Additional context**
None.
![Annotation 2020-08-18 080735](https://user-images.githubusercontent.com/49409486/90530694-08c18e00-e12a-11ea-99d5-963189d9de1f.jpg)

**Comment by JeneferM-MSFT** [comment] 2020-08-18 15:43
This has been fixed in later versions of the toolkit
Duplicate of #424

**Comment by tcamozzi** [comment] 2020-08-19 16:19
I have downloaded the most recent CoeStarterKit from this URL: https://aka.ms/CoeStarterKitDownload as found on this page: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components  I am working on version 1.60 for Core Components.

Also I have tried to follow the steps listed on #424<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fpowerapps-tools%2Fissues%2F424&data=02%7C01%7Ctrish.camozzi%40alaskaair.com%7C39df72faf1a24235ae5908d8438d7429%7C0f44c5d442b045c2bf55d0fea8430d33%7C0%7C0%7C637333622105145580&sdata=Fk%2BW55wkfZNOr3WcreqjT22cqNzQ0kVnabEIEhZogM0%3D&reserved=0>. I can’t save the flow to edit it to expand the pagination on the step shown.  What should I be doing differently?

Trish Camozzi-Ekberg
ITS Collaboration Services
Alaska Airlines – McGee Building 1st Floor
p 206.392.3198 | m. 206.696.4443

**Comment by JeneferM-MSFT** [comment] 2020-08-19 17:56
When you upgraded, did you hit overwrite? It is not the default and without it you wont receive the changes. 
Please see [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates)

**Comment by tcamozzi** [comment] 2020-08-19 17:59
Yes I did specify overwrite.  Is version 1.6 the most recent for the Core Component?  I am not 100% sure the link I was using actually took me to the most recent version of the solution.

**Comment by JeneferM-MSFT** [comment] 2020-08-19 18:07
Yep it looks like the fix didn't stick for some reason. 
Please make the change as suggested in #424 
![image](https://user-images.githubusercontent.com/62659043/90673128-1d765280-e20c-11ea-8b3c-e3679f9df019.png)

**Comment by tcamozzi** [comment] 2020-08-19 18:13
That is where I am getting stuck. I can’t edit the original and can’t save it to edit the copy.  If I can edit the original, I don’t know how to do that.  What am I missing on how to do that?

**Comment by JeneferM-MSFT** [comment] 2020-08-19 18:18
What happens when you click this edit button?
![image](https://user-images.githubusercontent.com/62659043/90674221-a9d54500-e20d-11ea-962e-3a7975486882.png)

**Comment by JeneferM-MSFT** [comment] 2020-08-19 18:23
re-opening as the change did not release, will validate with next release

**Comment by tcamozzi** [comment] 2020-08-19 18:29
I am in the solution > flow > details.  Hit the edit button. Find the step and the settings option is grayed out.

[cid:image001.png@01D6761C.0E97F590]

I can’t edit the copy I made because I haven’t been able to save the copy first.

**Comment by JeneferM-MSFT** [comment] 2020-08-19 18:33
Your picture didnt come through unfortunately. 
But here is a copy of the flow with the fix: [customconnectorpaginationfix_20200819183301.zip](https://github.com/microsoft/powerapps-tools/files/5098555/customconnectorpaginationfix_20200819183301.zip)


Thanks for using CoE!

**Comment by tcamozzi** [comment] 2020-08-19 18:35
Thanks!

**Comment by JeneferM-MSFT** [comment] 2020-09-21 15:34
This is fixed now in the 1.7 release of Core. 
Thanks again for letting us know, and for using the CoE!

**Closed by JeneferM-MSFT** 2020-09-21 15:34 UTC
Labels: coestarterkit
