### ISSUE TITLE
Admin | Sync Template v2 (Model Driven Apps) Failing

### ISSUE THREAD

**Issue by dhawal16** [microsoft/powerapps-tools#430] opened 2020-08-19 20:57 UTC
I am executing this flow with my Power Platform Service Admin Account.
The environment which returned the result today, is throwing the error while running the flow again tomorrow.
I am seeing the performance is not consistent everyday.

Is there anything specific I have to see for this issue?

Cheers,
Dhawal Mehta

**Comment by JeneferM-MSFT** [comment] 2020-08-19 21:10
We did have a regression in this solution this week which impacted this flow. We shipped the fix yesterday. Can you upgrade and see if that fixes you? Be sure to choose overwrite customizations on upgrade.

**Comment by Paul-NA8E** [comment] 2020-08-27 16:11
I'm also having some trouble with this flow.  This is a brand new setup with Core 1.6.
I'm seeing 400s in the "List Model Driven Apps" step with "Invalid value provided for data set"

**Comment by Paul-NA8E** [comment] 2020-09-08 23:36
@JeneferM-MSFT    In the 1.6 version there's a problem in the "Get App Modules Table. Fail out if no permissions to environment" section.     In the List Model Driven apps step the Environment is set to admin_environmentcdsmetadataname   which looks like  orgXXXXXXXX.crm.dynamics.com.    This results in a 400 error when the step runs.
If I manually set the environment to one from the drop down and then go to peek code i can see the it is looking for only orgXXXXXXXX.crm.    I changed environment to the following:
replace(triggerBody()?['admin_environmentcdsmetadataname'],'.dynamics.com','')
This removes .dynamics.com from the environment name and the step runs successfully.
Same problem again in the "Get MDD App Creator" step.  
Once those were both changed the flow runs successfully.

**Comment by JeneferM-MSFT** [comment] 2020-09-09 15:27
Hi Paul. I think you may have not chosen overwrite on upgrade as the issue you are seeing did ship but was fixed in 1.6

Thank you for getting yourself unblocked though! And thanks for using CoE!

**Closed by JeneferM-MSFT** 2020-09-09 15:27 UTC
Labels: coestarterkit

**Comment by Paul-NA8E** [comment] 2020-09-09 18:48
Jenefer,
      Ok,  I'm not sure that applies since this was our initial install and we started on 1.6?    Experienced the same problem with new install in test tenant.
It's working fine for me after the above work around, I just wanted to report the issue in case it comes up again.

Paul

**Comment by JeneferM-MSFT** [comment] 2020-09-09 18:56
Thanks Paul. The release may have missed the fix then, but our local version contains it and we are shipping soon. 
Really appreciate your efforts to help make CoE great!
