### ISSUE TITLE
[BUG]: Issue in (and solution of) action "Get Envt from CoE" in flow "CLEANUP - Admin | Sync Template v2 (Power Apps User Shared With)"

### ISSUE THREAD

**Issue by formsandflows** [microsoft/powerapps-tools#624] opened 2020-12-10 14:20 UTC
Module: Admin (Core solution)
Version: 1.71.7
Flow: CLEANUP - Admin | Sync Template v2 (Power Apps User Shared With)
Action: Get Envt from CoE

An error occurred when the default environment was processed. The default environment has an id/name that starts with: "Default_". This is thus not a guid.

The issue was corrected after changing the filter query:
OLD: admin_environmentid eq <<OUTPUTS>>
NEW: admin_environmentname eq '<<OUTPUTS>>'

The quotes are important too!

**Comment by JeneferM-MSFT** [comment] 2020-12-10 14:33
Duplicate of #601 
Thank you for posting! This was noted in #601 and has been local fixed for next delivery.

**Closed by JeneferM-MSFT** 2020-12-10 14:33 UTC
Labels: coestarterkit
