### ISSUE TITLE
[BUG]: issue title

### ISSUE THREAD

**Issue by Cathi029** [microsoft/powerapps-tools#510] opened 2020-10-09 09:09 UTC
Configuring App Power Platform Admin View not possible
There is no option in the navigation on the left side where I can configure the App (Logo, Company name, ...), also the Maker-Section is missing.
I use the app in German. I tried to uninstall the solution and installed it again because i was not sure if I have the latest Version and unfortunately there was a second problem. It is not possible to delete the Apps "Set Apps Permissions" and "Set Flows Permissions".

Component:
 - Solution: Core
 - Version e.g. 1.70.2
 - App Power Platform Admin View

![image](https://user-images.githubusercontent.com/62603605/95564758-8bc2de80-0a1f-11eb-93ea-2d1dd35ba386.png)

![image](https://user-images.githubusercontent.com/62603605/95563389-9da38200-0a1d-11eb-8f17-97766b333e92.png)

Many thanks for your help!

**Comment by JeneferM-MSFT** [comment] 2020-10-09 11:49
Hello this is a known limitation with some language packs. I have added a note to document this limitation 

Please see here from issue 
Duplicate of #443 

![image](https://user-images.githubusercontent.com/62659043/95579607-2f49ca00-09f3-11eb-8eff-574ea6cc79d5.png)

**Closed by JeneferM-MSFT** 2020-10-09 11:49 UTC
Labels: coestarterkit
