### ISSUE TITLE
[BUG]: Admin | Sync Template v2 (Flows) never ending

### ISSUE THREAD

**Issue by orauch-a** [microsoft/powerapps-tools#675] opened 2021-01-07 14:21 UTC
**Describe the bug**
For the Default environment "Admin | Sync Template v2 (Flows)" never ending during more than 13 days 
We have more than 80 environments and the defaut environment more than 4600 flows.
Today, the starter kit is not functional because the "Admin | Sync Templace v2 (flows)" never ending on the default environment.
After 13 days of exection, we stopped it.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Core Components
 - Version 1.71.7
 - Admin | Sync Template v2 (Flows)

**Screenshots**
![image](https://user-images.githubusercontent.com/34766578/103902385-be51a580-50fa-11eb-993b-f6acd7e04547.png)

![image](https://user-images.githubusercontent.com/34766578/103902495-e2ad8200-50fa-11eb-8e70-a564b08e56e1.png)

**Comment by JeneferM-MSFT** [comment] 2021-01-07 15:01
Hello. This is known and due to a product change that started to enforce throttling of large call volumes like our inventory requires. 
We have done a re-architect of the suite in order to work around this and so you will need to upgrade the toolkit in order to continue using it.
Be sure to follow the new path for update in order to receive the changes as described in [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates)
Duplicate of #497

**Closed by JeneferM-MSFT** 2021-01-07 15:01 UTC
Labels: coestarterkit
