### ISSUE TITLE
[BUG]: Audit Log Component Child Flow

### ISSUE THREAD

**Issue by rsch136** [microsoft/powerapps-tools#236] opened 2020-04-24 09:11 UTC
**Describe the bug**
Hi,
We are currently trying to set up the CoE Audit Log Components and are running into the follwoing error when trying to turn on the [Child] Admin | Sync Logs:

Your flow could not turn on: [Child] Admin | Sync Logs. Error: Flow client error returned with status code "Forbidden" and details "{"error":{"code":"DlpViolation","message":"Flow '' cannot be activated due to admin API policies."}}".

The flow also claims not to have any connections for this flow.

What could be the cause for these errors? There were no errors when installing the solution.

Please let us know what connections are being used so that we can build a custom DLP for the environment.

**Component (please tell us which flow or app you are experiencing issues with):**
 - CoE Audit Log Components
 - Version from 20.04.20
 - [Child] Admin | Sync Logs

**To Reproduce**
1. Follow documentation: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog

**Expected behavior**
No errors.

**Comment by manuelap-msft** [comment] 2020-04-24 10:36
Hello,

like this issue is caused because you have a DLP Policy configured on the environment where the CoE is installed that restricts which connectors can be used together. 

For the Audit Log solution to work, the Common Data Service, Power Apps Management, Office 365 Users, Office 365 Outlook connectors must be in the business data bucket and you will also need to add the custom connector (Office 365 Management Connector) to the business data only group so it can be used together with the above mentioned standard connecters.

We have had this raised before, and described here how to do that, so you can follow the steps here:
https://github.com/microsoft/powerapps-tools/issues/184#issuecomment-617103048

**Comment by rsch136** [comment] 2020-04-24 11:19
I also thought it must be a DLP issue which is why we created a new DLP for the CoE environment that allows everything. However, the child flow also claims not to have any connections at all:
![image](https://user-images.githubusercontent.com/44471683/80207255-21171580-862e-11ea-9ae9-9724bd2202bc.png)

**Comment by JeneferM-MSFT** [comment] 2020-04-24 15:56
Thank you so much for reporting this. I was able to repro locally and have a fix ready to release with the next update to CoE. 

To fix locally on your side, please do the below, from this [blog on child flows](https://docs.microsoft.com/en-us/power-platform-release-plan/2019wave2/power-automate/call-child-flows).

Please let me know if this resolves for you, and thanks again for reporting and helping make the CoE great! 
- - - 
![image](https://user-images.githubusercontent.com/62659043/80231623-78a28a80-8608-11ea-941e-9cb6cb726c05.png)

**Comment by lcimon** [comment] 2020-04-27 10:00
Hello,

I got the same issue: I can't turn on the child flow.
Solution provided by @JeneferM-MSFT doesn't solve it for me.

As @rsch136, I can't edit the child flow. Same error message. In "See more details", I have this message:
_"Time:
Server/Client Correlation ID: cb887db2-4416-4cd3-8d05-b2573b38f91f
Error: Could not find api 'shared_admin-5foffice-20365-20management-20api-5f1bdc0283b66cd8a9'."_

Also, I remarked other issues with this custom connector:
- I can't add this custom connector to the DLP. It isn't listed in the "DLP Customizer" app.
- I can't shared my connection with other people. This error message is shown: _"The caller with object id '92d441fa-70f7-494b-aa89-d8d17660f8e2' does not have permission to custom connector 'admin-5foffice-20365-20management-20api-5f838ff16dff5f3f69'."_

That let me think that something is wrong with custom connector.
I well configure it as described into the documentation. I'm also able to find it in "Custom Connectors" page.

Should I miss something ?

**Comment by JeneferM-MSFT** [comment] 2020-04-27 19:48
Are you saying when you browse to view custom connectors as shown below, that the connector created for this isn't present at all? If that is the case, then it was not installed there. Perhaps you were in a different environment at the time? 

![image](https://user-images.githubusercontent.com/62659043/80413648-a1cf4f00-8884-11ea-97ee-003786430d23.png)

Can you please try to re-do the steps in the [audit log setup documention](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog)?

**Comment by rsch136** [comment] 2020-04-28 07:34
I've taken a look at the custom connector again. Testing it now fails (401).
When I look at 2. Security, it also seems like none of my changes (Client Id, secret, resource URL) were saved:
![image](https://user-images.githubusercontent.com/44471683/80459948-6b044200-8933-11ea-8f0c-1feaf8dbff69.png)

**Comment by lcimon** [comment] 2020-04-28 08:29
> Are you saying when you browse to view custom connectors as shown below, that the connector created for this isn't present at all? If that is the case, then it was not installed there. Perhaps you were in a different environment at the time?

When I browse to view custom connectors, the custom connector is well shown:
![image](https://user-images.githubusercontent.com/22662809/80460724-86bc1800-8934-11ea-874f-74d72967b85c.png)

My points was:
- I can't add this custom connector to the DLP. It is like if it isn't found anywhere. In the "DLP Customize" app provided into the CoE Kit, it isn't listed:
![image](https://user-images.githubusercontent.com/22662809/80461159-25487900-8935-11ea-9878-a0364f2a7abe.png)
_(The 2 connectors displayed on the screenshot are tests of connectors without MFA. The one using MFA isn't shown here)_

- This error message is displayed when I want to share a connection from the view Connections:
![image](https://user-images.githubusercontent.com/22662809/80461606-d18a5f80-8935-11ea-82cc-78d37f04fea7.png)
_(I installed the solution, configure the custom connector and create the connection with the same account. I should be the owner of it)_

Obviously, I checked that I'm well in the good environment.
And I also tried to reinstall the solution and re-do the setup steps (several times and with different accounts), I still have the same issues.

**Comment by manuelap-msft** [comment] 2020-04-28 08:45
There is a gap with the Get-AdminPowerAppConnector  action in both PowerShell as well as the management connector which leads to it not returning custom connectors that are shipped as part of a managed solution. This has been reported to the owning team who are looking at a resolution.

In order to add the custom connector to the business data only group of your DLP policy, please follow the following steps using PowerShell cmdlets:

1. Follow the steps here to set up the PowerShell cmdlets, if not already done https://docs.microsoft.com/en-us/power-platform/admin/powerapps-powershell
2. Open the DLP Policy you want to add the custom connector to, and note the GUID of the DLP Policy. You can also achieve this by calling Get-AdminDlpPolicy in PowerShell and noting the PolicyName
image
![image](https://user-images.githubusercontent.com/55705669/80466783-e5819180-8934-11ea-9f27-df2969c94569.png)

3. Navigate to flow.microsoft.com > Data > Custom Connector and select Edit on the custom connector
image
![image](https://user-images.githubusercontent.com/55705669/80466797-eb777280-8934-11ea-82b3-b4f6a470b90b.png)

4. Note the Connector Name (everything between custom and edit)
image
![image](https://user-images.githubusercontent.com/55705669/80466826-f29e8080-8934-11ea-8018-a8e2e0066c42.png)

In PowerShell, use Add-CustomConnectorToPolicy to add the custom connector to your policy.
The format here is:
Add-CustomConnectorToPolicy -PolicyName {your policy name GUID} -ConnectorName {the nName you copied from above} -GroupName hbi -ConnectorId /providers/Microsoft.PowerApps/scopes/admin/environments/{your environment GUID{/apis/{your connector name}

for example this should look like this
Add-CustomConnectorToPolicy -PolicyName fbe6cc78-1234-1234-9362-a87c1618abcd -ConnectorName shared_admin-5foffice-20365-20management-20api-5f218397e7aabcdef -GroupName hbi -ConnectorId /providers/Microsoft.PowerApps/scopes/admin/environments/aab123ca-1234-1234-8b12-eae67cabcdef/apis/shared_admin-5foffice-20365-20management-20api-5f218397e7aabcdef

**Comment by manuelap-msft** [comment] 2020-04-28 08:49
@rsch136 This is expected behaviour, in view only mode (befor you click Edit on the Authentication), authentication details like client id and secret are not revealed. When you edit those details, ensure you confirm changes by clicking Update Connector in the top right corner. 

401 indicates an Unauthorized access error, this could be because 
- The Client ID / Secret are incorrect
- The API Permissions of the Azure App Registration have not been configured correctly
- tenant consent has not been granted for the App Registration

**Comment by manuelap-msft** [comment] 2020-04-28 08:55
@lcimon sharing custom connectors that are shipped as part of a managed solution is currently not available / supported by the product.

**Comment by lcimon** [comment] 2020-04-28 10:53
@manuelap-msft, thanks for the guidances. I will follow it to add the connector in DLP.

To avoid DLP issue with the Child Flow, I used an environment where everything is approved (no DLP).
The steps provided by @JeneferM-MSFT doesn't fix it. I edited the connection to use my specific connection instead of "Provided by run-only user". When I tried to turn on, it's failed as described in the first post.

**Comment by manuelap-msft** [comment] 2020-04-28 10:57
@Icimon What is the error message that you receive now, after you've specified run only users for the child flow and configured all your connection references?

**Comment by JeneferM-MSFT** [comment] 2020-04-28 12:18
Thanks for helping make CoE great everyone! From your notes above, I have added how-to's on the DLP problem described above to our local copy of the documentation.

**Comment by rsch136** [comment] 2020-04-28 12:25
> 401 indicates an Unauthorized access error, this could be because
> 
> * The Client ID / Secret are incorrect
> * The API Permissions of the Azure App Registration have not been configured correctly
> * tenant consent has not been granted for the App Registration

@manuelap-msft Tenant consent has been granted, permission are set correctly. However, whenever I go back to edit anything in 2. Security, the Fields are blank again. I have tried it multiple times and clicked update connector. Is this really intended behavior?

**Comment by manuelap-msft** [comment] 2020-04-28 15:50
@rsch136 yes that's expected. When you edit the custom connector and go to the "Test" tab, have you successfully established a connection to the connector there and been able to run the Start Subscription action in the test?

@lcimon and @rsch136, just verifying a few things:

If under Test, your screen looks like this
![image](https://user-images.githubusercontent.com/55705669/80506362-62c8f880-896d-11ea-8eda-3f98405a833b.png)

You need to select + New connection to create a new connection, which will authenticate with your account.

Data > Custom Connector > Edit Office 365 Management API > Test should look like this, with a connection established. This should succeed when the correct client ID and client secret has been provided
![image](https://user-images.githubusercontent.com/55705669/80506658-ceab6100-896d-11ea-955d-85af6b0bdd59.png)

Data > Connections should have your connection to the custom connector listed
![image](https://user-images.githubusercontent.com/55705669/80507044-4b3e3f80-896e-11ea-9a70-527e527306f6.png)

And then Child Flow > Edit Run only users should look like this, the icon and connector name should show for the custom connector. If this is a grey square, you don't have an active connection to the custom connector yet
![image](https://user-images.githubusercontent.com/55705669/80508622-2f3b9d80-8970-11ea-9404-da9976da6867.png)

**Comment by rsch136** [comment] 2020-04-30 07:54
@manuelap-msft 
I have managed to get a 200 when testing the connector. The error was in the resource URL. For some reason (perhaps when copying it from the website) an extra / was added to the end. Once I entered the correct URL it worked.

**Comment by manuelap-msft** [comment] 2020-04-30 08:20
@rsch136 That's great, thank you for confirming

**Comment by lcimon** [comment] 2020-04-30 12:27
@manuelap-msft  @JeneferM-MSFT
I ensure that the environment isn't covered by a DLP and perform a clean installation. And it is work well now. Thanks for the support.

**Comment by manuelap-msft** [comment] 2020-04-30 12:29
@Icimon thanks for confirming, great to hear! 
I will close this issue for now, but please feel free to reach out again if you have any further issues!

**Closed by manuelap-msft** 2020-04-30 12:29 UTC
Labels: coestarterkit

**Comment by rsch136** [comment] 2020-05-13 08:27
Hello,
I am still having the same issues with this solution.
In the meantime I was able to set up the connector and add it to the DLP.
I had to make one small change to what @manuelap-msft [suggested](https://github.com/microsoft/powerapps-tools/issues/236#issuecomment-620468625).
Apparently -type is a mandatory parameter. I set it to Microsoft.PowerApps/apis, like the other connectors in the DLP.
However, the child flow still does not show any connections and I still get the same error when trying to edit it. I have also followed @JeneferM-MSFT 's instructions on how to [repair the child flow](https://github.com/microsoft/powerapps-tools/issues/236#issuecomment-619097298). It does not fix the issue for me.
Please let me know what else I can do to fix this. Can I get an advanced copy of the fix?
Thanks

**Comment by manuelap-msft** [comment] 2020-05-13 08:30
Can you please raise a new issue for this so we can track this appropriately? This issue for example was raised due to incorrectly configured DLP policies and not issues with the Child Flow.
