### ISSUE TITLE
[BUG]: Unable to update the InnovationBacklogAppURL environment variable

### ISSUE THREAD

**Issue by marcster** [microsoft/powerapps-tools#670] opened 2021-01-06 14:53 UTC
Hi,

When importing the CenterofExcellenceInnovationBacklog_1_1_managed solution, I get the below screen.

![image](https://user-images.githubusercontent.com/1025102/103781689-94cb4800-502e-11eb-8262-dd772e086cda.png)

So, I entered a random text for the InnovationBacklogAppURL.  The solution imports fine but when I try to update the environment variable as shown in the next screenshot, I get the following error.

![image](https://user-images.githubusercontent.com/1025102/103781545-6a798a80-502e-11eb-889b-8afd40ae1a8b.png)

**Comment by JeneferM-MSFT** [comment] 2021-01-07 13:37
Duplicate of #663 
Hello. You have to go to the Default Solution to change env vars once you've used the "updated" pane. 
![image](https://user-images.githubusercontent.com/62659043/103898843-65f2b780-50aa-11eb-9c73-bcd8cf2f76ce.png)

**Closed by JeneferM-MSFT** 2021-01-07 13:37 UTC
Labels: coestarterkit
