### ISSUE TITLE
[BUG]: issue title

### ISSUE THREAD

**Issue by Pieter-Veenstra** [microsoft/powerapps-tools#549] opened 2020-10-30 11:25 UTC
**Describe the bug**
In the Sync Template v2 (Apps) flow Orphaned apps don't get logged.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Core
 - Version 1.70.6

**To Reproduce**
In my case an account of the owner of an app doesn't exist anymore. Now the get profile action fails.

In the Switch 2 action however the run after settings don't include "has failed" and the flow will end before the orphaned app can be logged. 

**Expected behavior**
Orphaned apps should be logged.

**Screenshots**

This will fix the issue:
![image](https://user-images.githubusercontent.com/18352488/97699634-6404ea80-1aa2-11eb-8ac6-72de2dcc1a6b.png)

**Additional context**
Some other parts of the flows will have exactly the same issue. The flows should be reviewed for this issue.

**Comment by JeneferM-MSFT** [comment] 2020-10-30 11:43
Duplicate of #537 

Hello. this is known and fixed in the upcoming release. Thanks for using CoE

**Closed by JeneferM-MSFT** 2020-10-30 11:43 UTC
Labels: coestarterkit
