### ISSUE TITLE
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E

### ISSUE THREAD

**Issue by RakeshRoutRicky** [microsoft/powerapps-tools#797] opened 2021-03-03 14:24 UTC
Getting the above error when connecting my org URL with power BI desktop
![Error BI Loading](https://user-images.githubusercontent.com/79986529/109819391-02c07400-7c5a-11eb-8a54-1b65ea18f474.jpg)
![Error workflow refresh 2](https://user-images.githubusercontent.com/79986529/109819411-07852800-7c5a-11eb-84ec-cded4b062afb.jpg)
![Error workflow refresh](https://user-images.githubusercontent.com/79986529/109819421-094eeb80-7c5a-11eb-977b-c0f48a414e0f.jpg)
[Error.txt](https://github.com/microsoft/powerapps-tools/files/6076566/Error.txt)
[Error-Session Diag.txt](https://github.com/microsoft/powerapps-tools/files/6076567/Error-Session.Diag.txt)
![Version Details](https://user-images.githubusercontent.com/79986529/109819566-37ccc680-7c5a-11eb-9c08-a095cdcd5f3c.jpg)

Link for reference: COE Starter Kit on Github - powerapps-tools/Administration/CoEStarterKit at master · microsoft/powerapps-tools · GitHub

**Comment by manuelap-msft** [comment] 2021-03-03 14:30
Hello,

can you confirm you only have one row in your CoE Settings table? It sounds like the issue is based on that, as the relationship in Power BI expects that table to only have one row.

Thank you
Manuela

**Comment by RakeshRoutRicky** [comment] 2021-03-03 14:33
Hi Manuela,

I confirm on the same. Did route in this direction.

[cid:image003.jpg@01D71068.4C0B4850]
Rakesh

**Comment by manuelap-msft** [comment] 2021-03-03 14:49
Would you be able to please try something following the steps below?

1. Select Cancel on the load and the Power BI should open (without values)
2. Under Modeling select Manage Relationships
![image](https://user-images.githubusercontent.com/55705669/109822651-10143900-7c2f-11eb-931a-cea70af9b518.png)
3. Look for the Environments - CoE Settings relationship and **delete** that one
![image](https://user-images.githubusercontent.com/55705669/109822762-2fab6180-7c2f-11eb-88b8-79aa389ef924.png)
4. Once you Save and Close that dialog, the re-load should start and work fine now.

It looks like Power BI auto-detected an unnecessary relationship between CoE Settings and Environment (this is not required) which could be causing this issue. I verified in my tenant that the dashboard still worked after removing the relationship, but if you could try and see if that also removes your error that would be great - and then we can include this change the next time we ship the dashboard.

**Comment by RakeshRoutRicky** [comment] 2021-03-03 15:53
Hi Maneula,

Tried setting as below(screenshot attached).

[cid:image003.jpg@01D71073.70604600]

But getting a new set of errors now:

[cid:image004.jpg@01D71073.70604600]
[cid:image005.jpg@01D71073.70604600]
Rakesh

**Comment by manuelap-msft** [comment] 2021-03-03 16:40
Hello,

sorry the images don't come through if you reply to the GitHub issue via email - could you go directly to GitHub and paste the images in again?

Thank you
Manuela

**Comment by RakeshRoutRicky** [comment] 2021-03-03 20:21
![ManageRelationshipsError](https://user-images.githubusercontent.com/79986529/109866921-ec331080-7c8b-11eb-866a-85bbd903db99.jpg)
![NewSetofErrors](https://user-images.githubusercontent.com/79986529/109866936-efc69780-7c8b-11eb-92d3-dd3b078a72b1.jpg)
![NewSetofErrors2](https://user-images.githubusercontent.com/79986529/109867043-12f14700-7c8c-11eb-94d8-074cd8d47b86.jpg)

**Comment by RakeshRoutRicky** [comment] 2021-03-03 20:21
Apologies for the delayed response
Attached are the new set of errors...

**Comment by RakeshRoutRicky** [comment] 2021-03-03 20:23
Hi Maneula,

Apologies for the delay in response.

I have added the concerned images in the portal.

Please do go through the same and let us know your feedback on the same.

Rakesh

**Comment by JeneferM-MSFT** [comment] 2021-03-03 23:42
Can you please share a screenshot (you will have to paste from within GitHub) of your CoE Settings data? 

In your CoE environment > Data >Tables > All > Search for Settings > Select the CoE Settings to open it in edit
![image](https://user-images.githubusercontent.com/62659043/109887527-be6fac80-7c36-11eb-8367-fc6f3adacd85.png)

Select Data > Change the View to All Columns
![image](https://user-images.githubusercontent.com/62659043/109887661-faa30d00-7c36-11eb-8bb6-a473001288c3.png)

And then share this view
![image](https://user-images.githubusercontent.com/62659043/109887706-11e1fa80-7c37-11eb-95a3-d1ffaaf128e9.png)

**Comment by manuelap-msft** [comment] 2021-03-04 09:11
Hello,

and could you do the same for the Environment and Apps table which seem to be blocking the Power BI too.

**Comment by RakeshRoutRicky** [comment] 2021-03-04 13:09
![image](https://user-images.githubusercontent.com/79986529/109968607-f3543000-7d18-11eb-83ff-44a061f45cec.png)

above image is for query as below

In your CoE environment > Data >Tables > All > Search for Settings > Select the CoE Settings to open it in edit
 
Select Data > Change the View to All Columns

And then share this view

**Comment by RakeshRoutRicky** [comment] 2021-03-04 13:11
![image](https://user-images.githubusercontent.com/79986529/109968810-2c8ca000-7d19-11eb-8b3a-b861d6550059.png)

**Comment by RakeshRoutRicky** [comment] 2021-03-04 13:12
![image](https://user-images.githubusercontent.com/79986529/109968934-4fb74f80-7d19-11eb-854f-a1eee4601773.png)

**Comment by RakeshRoutRicky** [comment] 2021-03-04 13:35
![image](https://user-images.githubusercontent.com/79986529/109971711-88a4f380-7d1c-11eb-83df-7561780a05d0.png)

**Comment by manuelap-msft** [comment] 2021-03-04 14:02
Thank you for providing this!

1. In your CoE Settings table you have two rows - can you delete both of those rows and add just one new one?
2. It looks like you don't have data in your tables yet - can you confirm you have turned on the Admin | Sync Flow v3 and that is running successfully? This is populating the App, Environment and Flow tables the Power BI is based on.

Thank you
Manuela

**Comment by RakeshRoutRicky** [comment] 2021-03-04 14:08
![image](https://user-images.githubusercontent.com/79986529/109975452-a5432a80-7d20-11eb-8610-55fb7e5f498e.png)
there were two instances here.
With the help of Valentina was able to remove the error , hit refresh now i have only blank table with no data in them

![image](https://user-images.githubusercontent.com/79986529/109975627-d885b980-7d20-11eb-8629-952da80a00de.png)

now I see data populating 

![image](https://user-images.githubusercontent.com/79986529/109975820-0e2aa280-7d21-11eb-8333-40ea6f85bcc5.png)

![image](https://user-images.githubusercontent.com/79986529/109975888-226e9f80-7d21-11eb-9504-efafba4d3ad2.png)

**Comment by manuelap-msft** [comment] 2021-03-04 14:13
You're on a drillthrough screen that only shows data when something is selected from a previous screen. Are all of your pages empty? Can you perhaps go to the Overview - Power Apps page in the dashboard and see if that is empty as well?

The Cloud Flow Details page will be empty unless a cloud flow is selected - on some of the overview and inventory pages you can right click in the table and select Drillthrough > Cloud Flow Detail
![image](https://user-images.githubusercontent.com/55705669/109976432-af9aff80-7cf3-11eb-95ed-40b3335cd598.png)

**Comment by RakeshRoutRicky** [comment] 2021-03-04 15:51
![image](https://user-images.githubusercontent.com/79986529/109990506-754f5380-7d2f-11eb-8896-4a9dddd56a3a.png)

Thanks .. i see information in the overview page.. will check on the drill down and update back

**Comment by manuelap-msft** [comment] 2021-03-04 15:55
Great thank you for confirming! 

One way of getting to that page is going to the Cloud Flow Archive page and selecting a flow, right clicking on it and selecting Drillthrough > Cloud flow detail and that should then show you details about an individual flow.
![image](https://user-images.githubusercontent.com/55705669/109991049-e11ac780-7d01-11eb-9a55-d6e4942dd896.png)

**Comment by manuelap-msft** [comment] 2021-04-07 10:32
Closing out issues with no further action.

**Closed by manuelap-msft** 2021-04-07 10:32 UTC
Labels: coestarterkit
