### ISSUE TITLE
[BUG]: CenterofExcellenceAuditComponents_1_17_managed.zip asks for value of "Developer Compliance Center URL" environment variable

### ISSUE THREAD

**Issue by NPrice99** [microsoft/powerapps-tools#324] opened 2020-06-05 11:16 UTC
**Describe the bug**
CenterofExcellenceAuditComponents_1_17_managed.zip asks for value of  Developer Compliance Center URL not Archive Site (URL) Environment Variable.

**Component (please tell us which flow or app you are experiencing issues with):**
CenterofExcellenceAuditComponents
Version 1.17
 - Environment Variable

**To Reproduce**
1. Import CenterofExcellenceAuditComponents_1_17_managed.zip
2. Create the site 
3. click on "See Environment Variable" 

**Expected behavior**
I expect to see Archive Site URL not Developer Compliance Center URL

**Screenshots**
![image](https://user-images.githubusercontent.com/8484048/83870464-394a7c00-a726-11ea-9f32-5c459883683e.png)

**Additional context**

**Comment by JeneferM-MSFT** [comment] 2020-06-05 13:20
Duplicate of #325

**Closed by JeneferM-MSFT** 2020-06-05 13:20 UTC
Labels: coestarterkit
