### ISSUE TITLE
[BUG]: Unable to register for an event within the Power Platform Training Registration app

### ISSUE THREAD

**Issue by marcster** [microsoft/powerapps-tools#877] opened 2021-03-26 14:16 UTC
**Describe the bug**
Unable to register for event within the Power Platform Training Registration app

**Component (please tell us which flow or app you are experiencing issues with):**
 - Nurture
 - 1.27
 - Power Platform Training Registration 

**To Reproduce**
1. Launch the Power Platform Training Registration app
2. Click on an event
3. Nothing happens

**Expected behavior**
When clicking on an event, the user should be taken to the registration event page

**Screenshots**
![image](https://user-images.githubusercontent.com/1025102/112644640-8b879580-8e3d-11eb-822e-9384fc885c5c.png)
![image](https://user-images.githubusercontent.com/1025102/112645284-3a2bd600-8e3e-11eb-8c6e-407e75a7cf28.png)

**Additional context**
There is no "Navigate" method on the "On Select" action for the button within the gallery to go to the Register screen.
Once this is added, it works.

**Comment by JeneferM-MSFT** [comment] 2021-03-26 15:29
Hello, I'm afraid I dont repro. Selecting that then selects the parent which does the navigate as shown here
![image](https://user-images.githubusercontent.com/62659043/112654763-59fad400-8e15-11eb-9cca-9f6bac097d2d.png)

**Comment by marcster** [comment] 2021-03-26 16:19
Can you confirm the version of the toolkit are you using as I have reproduced this in two different environments which have version 1.27 installed?

**Comment by JeneferM-MSFT** [comment] 2021-03-26 22:12
You are correct, it looks like this was a regression in 1.27. I didn't repro in my 1.24 install, nor in my local env where it is already fixed again. 

We are shipping the April release next week and the fix will be there. 

Thanks for using CoE

**Comment by manuelap-msft** [comment] 2021-04-08 11:51
Fixed with the current release, shipped today. Thank you for using the CoE!

**Closed by manuelap-msft** 2021-04-08 11:51 UTC
Labels: coestarterkit, localfixed
