### ISSUE TITLE
[BUG] Office 365 Management APIs Keeps Disappearing from APP Registrations

### ISSUE THREAD

**Issue by NPrice99** [microsoft/powerapps-tools#661] opened 2020-12-30 17:47 UTC
**Describe the bug**
Since Installing Center of Excellence - Core Components v1.71.7 the Custom Connector Office 365 Management APIs keeps disappearing from APP Registrations in Azure Active Directory

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - Core
 - Version  - 1.71.7
 - App or Flow - Custom Connector

**To Reproduce**
1. Install Core Components v1.71.7
2. Install the Office 365 Management APIs in App Registrations in Azure Active Directory
3. Wait 2 weeks
4. See error - notice that Office 365 Management APIs has disappeared from App Registrations

**Expected behavior**
Office 365 Management APIs remains in APP Registrations

**Screenshots**

**Additional context**
I have raised an incident with Microsoft Premier Support and they have come back saying that they cannot find anything wrong with Azure AD and therefore it would seem to be a problem with the Centre of Excellence.
This has now happened on two different tenancies.

**Comment by manuelap-msft** [comment] 2020-12-31 12:51
Closing as duplicate of #662

**Closed by manuelap-msft** 2020-12-31 12:51 UTC
Labels: coestarterkit
