### ISSUE TITLE
[coestarterkit] - Audit custom connector - error [400] - Test Operation

### ISSUE THREAD

**Issue by hsantan** [microsoft/powerapps-tools#647] opened 2020-12-21 21:46 UTC
I'm receiving the error [400] when I try to test the "Start Subscription"
![2020-12-21 18_27_10-Manage your custom connectors _ Power Automate](https://user-images.githubusercontent.com/40079239/102823753-45441580-43ba-11eb-947d-79f12873e81f.png)

{
  "error": {
    "code": "StartSubscription [CorrId=1e66f72e-a894-4359-859b-43dc545c104b]",
    "message": "bf94ede-1182-42c2-b949-958401f12f0d] failed. Exception: Microsoft.Office.Compliance.Audit.DataServiceException: Tenant 1b818c16-117f-4bf5-89a7-028fd47f7664 does not exist.\r\n   at Microsoft.Office.Compliance.Audit.API.AzureManager.<GetSubscriptionTableClientForTenantAsync>d__51.MoveNext() in d:\\dbs\\sh\\nibr\\1214_141956_0\\cmd\\q\\sources\\dev\\auditing\\src\\auditapiservice\\common\\AzureManager.cs:line 1953\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Office.Compliance.Audit.API.AzureManager.<GetAPISubscriptionAsync>d__22.MoveNext() in d:\\dbs\\sh\\nibr\\1214_141956_0\\cmd\\q\\sources\\dev\\auditing\\src\\auditapiservice\\common\\AzureManager.cs:line 498\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Office.Compliance.Audit.API.StartController.<StartSubscription>d__0.MoveNext() in d:\\dbs\\sh\\nibr\\1214_141956_0\\cmd\\17\\sources\\dev\\auditing\\src\\auditapiservice\\apifrontendservicerole\\Controllers\\StartController.cs:line 76"
  }
}

All configuration its ok!

_Originally posted by @hsantan in https://github.com/microsoft/powerapps-tools/issues/615#issuecomment-749205221_

**Comment by manuelap-msft** [comment] 2020-12-22 11:59
When you raise a new issue, could you help us by selecting the correct project under "New Issue"? See highlighted:
![image](https://user-images.githubusercontent.com/55705669/102886438-06ab6b00-444d-11eb-8f5a-59aec087d5f1.png)

This repo is used for different projects, which are worked on by different teams - filing the issue report in the correct category ensures it is automatically labelled and assigned to the correct team.

**Comment by manuelap-msft** [comment] 2020-12-22 12:01
This issue from the error message "Tenant 1b818c16-117f-4bf5-89a7-028fd47f7664 does not exist" typically has two root causes:

- You have turned on the Office 365 Audit Log in your tenant very recently, and it is not active to be consumed via the API yet. Sometimes this can take a few hours to activate.
- You have entered your Tenant ID incorrectly. This is your Tenant ID from the App registration, which you can find under Directory (tenant) ID in the Apo Registration overview.

**Closed** 2020-12-22 12:14 UTC
Labels: coestarterkit

**Comment by hsantan** [comment] 2020-12-22 12:16
@manuelap-msft Thank You Manuela. Now its working after waiting 24h to index all audit logs

**Comment by manuelap-msft** [comment] 2020-12-22 12:16
Great, thank you! We will make sure to add a note in our setup instructions next time we update our documentation to share this as well!
