### ISSUE TITLE
[BUG]: issue Your Flow could not turn on: Admin Sync template v3 error

### ISSUE THREAD

**Issue by rosannaGorman** [microsoft/powerapps-tools#772] opened 2021-02-16 15:30 UTC
**Describe the bug**
I have upgraded to the latest version of Core Components but the Sync Flows will not turn on. get the error as below

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [core components latest version just upgraded]
 - Version [1.89]
 - App or Flow [the Sync FlowsSync Template (v3)]

**To Reproduce**

**Expected behavior**
to start the sync flows - turn them on

We are using the power Apps per user license, is this an issue where we have hit limitations on API calls? 

**Screenshots**
Your flow could not turn on: Admin | Sync Template v3. Error: Flow client error returned with status code "BadRequest" and details "{"error":{"code":"InvalidOpenApiFlow","message":"Flow save failed with code 'InvalidPaginationPolicy' and message 'The pagination policy of workflow run action 'ListDefns-PowerAutomateEnvironmentVariable' of type 'OpenApiConnection' at line '1' and column '2393' is not valid. The value specified for property 'minimumItemsCount' exceeds the maximum allowed. Actual: '100000'. Maximum: '5000'.'."}}".

**Additional context**
![image](https://user-images.githubusercontent.com/79154878/108083787-5bddb480-706b-11eb-8f40-cdb4ba27300e.png)
![image](https://user-images.githubusercontent.com/79154878/108083818-64ce8600-706b-11eb-9d24-616fbc6722ed.png)
![image](https://user-images.githubusercontent.com/79154878/108084215-da3a5680-706b-11eb-96b3-a952b7595726.png)

**Comment by JeneferM-MSFT** [comment] 2021-02-16 19:20
Hello. 

This is covered by #725

All the flows have this pagination policy. It indicates that you are using an insufficient license.
Note that we do not support trial licenses for the toolkit any longer due to some product changes that upped the requirements for throttling purposes.

See here for the license types: [Performance profiles](https://docs.microsoft.com/power-automate/limits-and-config#performance-profiles)
And here for pagination limits: [Paginated items](https://docs.microsoft.com/power-automate/limits-and-config#concurrency-looping-and-debatching-limits)

And hence our requirements for licenses. [What licenses do I need to run this solution?](https://docs.microsoft.com/power-platform/guidance/coe/setup#what-licenses-do-i-need-to-run-this-solution)

Duplicate of #725

**Closed by JeneferM-MSFT** 2021-02-16 19:20 UTC
Labels: coestarterkit

**Comment by rosannaGorman** [comment] 2021-02-17 20:33
Thank You
