### ISSUE TITLE
[BUG]: Default environment ID not stored correctly

### ISSUE THREAD

**Issue by StephenCouch** [microsoft/powerapps-tools#718] opened 2021-01-21 20:31 UTC
**Describe the bug**
The ID of the Default environment is not stored correctly within the 'Environment' table. This seems to be due to two different situations. 1) The ID is stripped of all prefixes before it is stored in the CDS. 2) The Primary field (the ID field) is defined as having a data type of Unique Identifier which is a system type that only will store a GUID. 

Our default environment has a prefix of "Default-" followed by a GUID. Normally this would not be an issue except for downstream processes that rely on this such as the App Archive process. This process reads the environment ID from the Core Environment table and stores it in the Archive Approval table. This creates a situation where applications will not be automatically deleted since the environment ID is not valid (being missing the 'Default-' prefix).

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution = Core
 - Version = 1.72
 - App or Flow = Admin | Sync Template v3

**To Reproduce**
1. Install the solution
2. Run the flows

**Expected behavior**
The ID of the default environment should be stored with the 'Default-' prefix intact.

**Comment by JeneferM-MSFT** [comment] 2021-01-21 20:36
Hello, thanks for using CoE. The issue mentioned in archive approval is covered by #666  and is local fix, expect to ship in the next week. Do you have other specific cases where you see issues?

**Comment by StephenCouch** [comment] 2021-01-21 21:09
I have not seen any other specific cases as of yet. The archival approval is here I fist noticed it and have tracked it to the Environment table from the Core Components solution. 

I look forward to seeing the fix for this. Currently I have a flow that uses "on record creation" as a trigger to rewrite the ID with the correct one - but this is not ideal.

**Comment by JeneferM-MSFT** [comment] 2021-01-21 21:33
Thank you for confirming. Yes the problem is that some connectors want the name (including Default-) and some want the GUID without the pre-fix. So we have to remember and test each time we make a change. We missed this one. 

Please let us know if you find other cases. 
I will close this one as a dupe to the above mentioned issue so you can track the release of the fix.
Duplicate of #666

**Closed by JeneferM-MSFT** 2021-01-21 21:33 UTC
Labels: coestarterkit
