### ISSUE TITLE
[BUG]: Solution "Center of Excellence - Core Components" failed to import: Import failed: An item with the same key has already been added.

### ISSUE THREAD

**Issue by StefanPlizga** [microsoft/powerapps-tools#566] opened 2020-11-13 14:27 UTC
**Describe the bug**
When trying to import the Core Components solutions of the CoE, I get the following error: Solution "Center of Excellence - Core Components" failed to import: Import failed: An item with the same key has already been added.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: Core
 - Version: same issue with 1.70.6, 1.70.2, 1.60, 1.54 (not tested with others)

**To Reproduce**
1. Create a new environment (Trial-Subscription, located in France)
2. Create the connections as per doc
3. Import the solution, set the flow URL to https://france.flow.microsoft.com/manage/environments/
4. Wait a few minutes and get the error: Solution "Center of Excellence - Core Components" failed to import: Import failed: An item with the same key has already been added.

**Expected behavior**
Solution is imported with no error.

**Screenshots**
See 2 attached screenshots
![Error-1](https://user-images.githubusercontent.com/13829302/99082690-c2fb5100-25c4-11eb-8d98-e2a126ff41f9.PNG)
![Error-2](https://user-images.githubusercontent.com/13829302/99082685-c1ca2400-25c4-11eb-82d9-541f6f94f4ef.PNG)

**Comment by JeneferM-MSFT** [comment] 2020-11-13 14:51
Can you please **_Switch to Classic_** and see if import works via that path? Please let me know if you need help with that path.

**Comment by sundium** [comment] 2020-11-16 07:38
I had the same problem, opened the log file in it's shown as the following.

![image](https://user-images.githubusercontent.com/11729099/99224493-49c15f80-284b-11eb-9204-0e4fd841171e.png)

**Comment by sundium** [comment] 2020-11-16 07:43
Confirming importing through Classic Solution explorer worked. Question is why?

![image](https://user-images.githubusercontent.com/11729099/99225071-52fefc00-284c-11eb-8477-681f06f4dbf9.png)

**Comment by JeneferM-MSFT** [comment] 2020-11-16 15:21
Glad we got you a work-around. I don't know why it failed in Modern Import but have sent your case to the product team.

Thanks for using CoE!

**Comment by StefanPlizga** [comment] 2020-11-16 15:50
Thank you @JeneferM-MSFT, however when importing from the Classic UI, there is no UI to submit environment parameters and connections. For environment parameters, that's OK because there is a prompt in the modern portal when going to the Apps part.
However, I don't see here to set the connections to the apps and flows when the package has been imported via the classic UI. Any idea?

**Comment by sundium** [comment] 2020-11-16 18:41
There isn't from what I can see, and the "workaround" is to fix each
connections in each flow, which is painstakingly tedious and time consuming.

**Comment by JeneferM-MSFT** [comment] 2020-11-16 18:54
Hello. I'm afraid there is a product issue here that prevented you from using Modern Import. 

If you'd like to try importing with the new version released today, you may have luck. [https://aka.ms/CoEStarterKitDownload](https://aka.ms/CoEStarterKitDownload)

**PLEASE NOTE:** In order to receive updates, you now have to remove all unmanaged layers from any apps/flows you have created in the past. Otherwise you will not see the changes for the app/flow that maintains its unmanaged layers. 

For more details on what this looks like, please view [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates)

**Comment by StefanPlizga** [comment] 2020-11-16 20:19
Hello, I imported the new solution into a brand new environment located in France and it failed. I created another new environment  in Europe and it worked. So I guess there is an issue with Power Apps in France rather than an issue with the CoE package (or an issue with the CoE package import in France datacenter). If you could pass this info to product team...

**Comment by JeneferM-MSFT** [comment] 2020-11-16 20:27
Wonderful. Thank you for that insight. I have passed it along. 

Thanks for helping make CoE AND the product great.

**Comment by petepuu** [comment] 2020-11-23 21:58
Hi, I got same error with newest 1.71.5 version in Europe region but import seems to work in classic side

**Comment by Panoone** [comment] 2020-11-24 05:03
Same issue here with latest core solution 1.71.5. Using classic sounds like a deal-breaker.

Log file attached. (Added .log extension to filename.)

[ERRORLOG-Core Components_import.xml.log](https://github.com/microsoft/powerapps-tools/files/5587517/ERRORLOG-Core.Components_import.xml.log)

**Comment by SoldadoCOD** [comment] 2020-11-24 14:05
Same here, tried with trial environment, production environment (both on europe area), versions 1.71.1 and 1.71.5, no luck. It could be imported though classic but it's just useless.

**Comment by bennyboy23** [comment] 2020-11-24 14:43
I have also hit his issue. I have managed via the classic side, but now im have to crawl through all the flows and update all the connections.

**Comment by JeneferM-MSFT** [comment] 2020-11-24 14:48
Sorry you are hitting product issues. You will need to create a ticket and they will 
disable a value called: FCB.SolutionSimplificationImportMigration.EnvironmentVariableValue.

**Comment by SoldadoCOD** [comment] 2020-11-24 16:15
> Sorry you are hitting product issues. You will need to create a ticket and they will
> disable a value called: FCB.SolutionSimplificationImportMigration.EnvironmentVariableValue.

You mean Premier Support ticket?

**Comment by coupster74** [comment] 2020-11-24 16:50
I'm having the same issue in NA, and it also worked for me in Classic view. However, I don't seem to have the ability to set the two environment variables as they are "marked as managed". Any ideas.

**Comment by JeneferM-MSFT** [comment] 2020-11-24 16:57
The issue with the env vars is a product change, please add any notes about that to issue #591

**Comment by manuelap-msft** [comment] 2020-11-24 19:15
Hello @SoldadoCOD 

Heres info on how to get support: https://docs.microsoft.com/en-us/power-platform/admin/get-help-support which will depend on your enterprise agreement with Microsoft. As you are experiencing a product issue, not an issue with the CoE kit itself you will have to go through our official support channels.

Others on the thread: if you are experiencing the same issue as at the start of the post, please also raise a support ticket. If you are experiencing a different issue please open a new issue for us to investigate on GitHub - its otherwise challenging for us to keep up with comments if different issues are discussed in the same thread.

Thank you

**Comment by petepuu** [comment] 2020-11-24 19:30
@manuelap-msft @JeneferM-MSFT , is it so that this does not relate any specific version of CoE if the problem is in environment variable not related to CoE? It seems that creating new environment (have tested with trial) does not affect this and will get same error

**Comment by manuelap-msft** [comment] 2020-11-24 19:33
@petepuu Another user was experiencing this issue outside of the CoE Kit as well, so it seems to be a product change: 
https://github.com/microsoft/powerapps-tools/issues/591

**Comment by petepuu** [comment] 2020-11-24 19:45
Ok thanks @manuelap-msft! Just wanted to double check that not related to any specific CoreComponent version

**Comment by ltwlf** [comment] 2020-11-26 10:42
We face the same issue (European environment, DB Version 9.1.0000.25245).

**Comment by manuelap-msft** [comment] 2020-11-26 10:43
@ltwlf Liked noted earlier, this is a product issue - You will need to create a support ticket and they will
disable a value called: FCB.SolutionSimplificationImportMigration.EnvironmentVariableValue.

**Comment by ltwlf** [comment] 2020-11-26 10:44
Thx will do

**Comment by petepuu** [comment] 2020-11-27 21:09
No sure is this relevant anymore but import seems to work in US region. Tested 3 times in different tenants and every time import worked in US region but it is not working in Europe

**Comment by remenator** [comment] 2020-12-01 19:25
I just tried the importing the solution and it failed with the error in this thread.  I tried in two different tenants in Canada region both failed.  I submitted a ticket with Support that directed me to this thread, they are trying to figure out how to disable the FCB.SolutionSimplificationImportMigration.EnvironmentVariableValue as directed by Manuela

**Comment by Panoone** [comment] 2020-12-01 21:13
@manuelap-msft , do you think you guys could share the solution with the back-end team?

I've had a SR open (#2011240030002766) for almost a week and it seems like they're either struggling or not seeing this as a priority.

**Comment by medicineshow** [comment] 2020-12-02 13:42
I just tried the importing the solution and it failed with the error noted. This is in the UK tenant.

**Comment by JeneferM-MSFT** [comment] 2020-12-02 14:19
Folks. I am told by the product team that we should expect this fix to roll out to the rest of the data centers this weekend. So hopefully this will be resolved on Monday.

**Comment by rkrish2020** [comment] 2020-12-02 20:20
I just tried the importing the solution and it failed with the error 
This is in Canada tenant. Version: 1_71_7, 1_70_2, 1_71_5

**Comment by statto1974** [comment] 2020-12-07 15:16
Have just tried this in a UK environment and can now confirm it is working as intended and solution imports successfully

**Comment by medicineshow** [comment] 2020-12-07 15:27
Thank you. I can confirm that it has worked for me too.

Kind Regards

Mark Enfield
Mark Enfield | Desktop Architect | HS2/Fujitsu
[cid:image001.png@01D4F167.F8FE2E00]High Speed Two (HS2), 1st  Floor, The Podium Euston, One Eversholt Street, London, NW1 2DN

Advanced Notice Annual Leave: 21st December – 3rd January
Tel: +44 (0)207 944 6302
Mob: +44 (0)7867 825 281

Web: uk.fujitsu.com<http://uk.fujitsu.com/>
[youtube-icon.gif]<http://www.youtube.com/user/fujitsuUK>[Facebook-icon.gif]<http://www.facebook.com/fujitsuuk> [twitter-icon.gif] <http://twitter.com/#!/fujitsu_uk>  [linkedin-icon.gif] <http://www.linkedin.com/company/fujitsu-uk-and-ireland>  [blogger.png] <http://blog.uk.fujitsu.com/>  [cid:image013.gif@01D56C84.E4379B30] <https://plus.google.com/103287532874520008913/posts>
[cid:image014.jpg@01D56C84.E4379B30]
Fujitsu is proud to partner with Action for Children<http://www.actionforchildren.org.uk/>

**Comment by JeneferM-MSFT** [comment] 2020-12-09 22:27
Thank you everyone for validating this fix went out. And thank you for using the CoE!

**Closed by JeneferM-MSFT** 2020-12-09 22:27 UTC
Labels: coestarterkit
