### ISSUE TITLE
Admin | Sync Template v2 (Apps) SharePointFormApp error

### ISSUE THREAD

**Issue by aakashpatel660** [microsoft/powerapps-tools#551] opened 2020-10-30 14:24 UTC
**Describe the bug**
Many of my flow runs it gets fails at Get App Role Assignments as Admin action. it throws an error for No Permission to the SharePointFormApp Applications. 

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - Core
 - Version - 1.70.6
 - Flow - Sync Template (v2) (Apps)

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/59940632/97716389-f0f77600-1a99-11eb-9381-1712d0fa83af.png)

**Additional context**

**Comment by JeneferM-MSFT** [comment] 2020-10-30 14:41
Thanks for posting. This one is known and local fixed to be released in the next version.
Duplicate of #543

**Closed by JeneferM-MSFT** 2020-10-30 14:41 UTC
Labels: coestarterkit
