### ISSUE TITLE
[BUG]: Flow returns 404 Error when deleting Teams environments

### ISSUE THREAD

**Issue by ApoorvaKantale** [microsoft/powerapps-tools#975] opened 2021-04-28 16:20 UTC
Weekly cleanup of teams environment flow .

The flow is delete the teams environment based on the condition , but it fails with the below error

**{​​​"statusCode":404,"headers":{​​​"Access-Control-Allow-Methods":"GET, PUT, PATCH, DELETE, POST","Access-Control-Allow-Origin":"*","Access-Control-Max-Age":"3600","Access-Control-Expose-Headers":"*","Date":"Wed, 28 Apr 2021 14:58:44 GMT","Content-Length":"54","Content-Type":"application/json"}​​​,"body":{​​​"statusCode":404,"message":"Resource not found"}​​​}​​​**

![image](https://user-images.githubusercontent.com/78148795/116438124-c54c2180-a86b-11eb-8447-350df200b72e.png)

Can you please check and let us know.

**Comment by manuelap-msft** [comment] 2021-04-28 17:05
The 404 error is expected behaviour as per https://docs.microsoft.com/en-us/powershell/module/microsoft.powerapps.administration.powershell/remove-adminpowerappenvironment?view=pa-ps-latest#description

We addressed and fixed this with the latest release, as per #764. Can you confirm you are on the latest version? Please be sure to remove any unmanaged layers from flows before you update as described in [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates) or you will not see the changes.

**Comment by JeneferM-MSFT** [comment] 2021-04-30 14:31
Closing out as duplicate per comment above. 
Duplicate of #764

**Closed by JeneferM-MSFT** 2021-04-30 14:31 UTC
Labels: coestarterkit
