### ISSUE TITLE
[BUG]: Error when update "Center of Excellence - Core Components"

### ISSUE THREAD

**Issue by Louicha** [microsoft/powerapps-tools#696] opened 2021-01-15 11:12 UTC
**Describe the bug**
When we import the latest version of the starter kit, we get the following error:
_Attribute admin_rpamodifiedon is a String, but a DateTime type was specified._

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Center of Excellence - Core Components
 - Version 1.45 to 1.78

**To Reproduce**
1. Solution Center of Excellence - Core Components Version 1.45 installed 
2. Import  Center of Excellence - Core Components Version 1.78
3. Error _Attribute admin_rpamodifiedon is a String, but a DateTime type was specified._

**Expected behavior**
Center of Excellence - Core Components Version 1.78 can be imported and installed.

**Additional context**
_Extract from the error log:_
> _Failure_ at 10:27:42.28 - CenterofExcellenceCoreComponents: Attribute admin_rpamodifiedon is a String, but a DateTime type was specified.
_Prossesed_ at 10:31:06.82 - admin_RPA.admin_rpamodifiedon: The behavior of this field was changed. You should review all the dependencies of   this field, such as business rules, workflows, and calculated or rollup   fields, to ensure that issues won't occur. Attribute: admin_rpamodifiedon (0x800608A4)
_Failure_ at 10:31:08.22 - admin_RPA: Attribute admin_rpamodifiedon is a String, but a DateTime type was specified.(0x80041A06)

**Comment by JeneferM-MSFT** [comment] 2021-01-15 15:00
Duplicate of #491 

This was addressed in issue 491. There is an interim solution there that you will need to update to before you update to the latest.

**Closed** 2021-01-15 15:01 UTC
Labels: coestarterkit
