### ISSUE TITLE
[BUG]: Theming component issue

### ISSUE THREAD

**Issue by melmgcoe** [microsoft/powerapps-tools#955] opened 2021-04-22 16:10 UTC
**Describe the bug**
Hi, we've imported the latest version of Theming component and tried to use the CoE Theme Editor. We can't use the app to change the colours for a test theme. The buttons to change the colours don't appear. I've tried both the Edge Chromium and Chrome browser and the issue happens for both.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - Theming
 - Version - 1.0.0.9
 - App - CoE Theme Editor

**To Reproduce**
1. Launch the CoE Editor app
2. Click on the button to change colour, nothing happens.

**Expected behavior**
I would expect the buttons to be available to change colours.

**Screenshots**
![image](https://user-images.githubusercontent.com/62425530/115747785-7bf06380-a38d-11eb-94c7-6c6b978b87fc.png)

**Comment by manuelap-msft** [comment] 2021-04-22 17:48
Have you followed the pre-requisites here https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-theming#prerequisites and can you try opening the app in Edit mode and check if it shows up then?

Thank you
Manuela

**Comment by melmgcoe** [comment] 2021-04-26 10:10
Hi Manuela,

Thanks for steer. We did enable the pre-req feature but this was only done after the solution was imported. We’ve re-imported the solution and the colour selection boxes now appear.

However, when I attempt to change the Primary1Colour value from white to green, the app suddenly appears to restart. When I go back into the app and edit my theme, the Primary1Colour value remains as white.

If I attempt to change the colour again, the app appears to save the change but gets stuck at this screen. See the screenshot below for what I see:

***@***.***D73A8C.95C46EB0]

Could this be a potential bug with the app?

Regards,

***@***.***D73A8C.95C46EB0]
[M&G Plc Logo]
***@***.***D73A8C.95C46EB0]
Melvin Uy
Collaboration Technical Specialist
Workspace Collaboration O365
***@***.*** ***@***.***>
t. 02039770030 (Internal: 60030)

10 Fenchurch Avenue
London EC3M 5AG
***@***.***D73A8C.95C46EB0]


***@***.***D73A8C.95C46EB0]
***@***.***D73A8C.95C46EB0]
***@***.***D73A8C.95C46EB0]

**Comment by manuelap-msft** [comment] 2021-04-26 10:12
We have some outstanding issues with the Theming editor, see #467 and #421 but the app should work when in Edit mode. The issues appear to be only with Play mode.

**Comment by melmgcoe** [comment] 2021-04-26 10:56
Thanks for the steer, I’ve managed to get the app working in edit mode as advised.

Please go ahead and archive the ticket for this issue.

Regards,

***@***.***D73A93.3724C880]
[M&G Plc Logo]
***@***.***D73A93.3724C880]
Melvin Uy
Collaboration Technical Specialist
Workspace Collaboration O365
***@***.*** ***@***.***>
t. 02039770030 (Internal: 60030)

10 Fenchurch Avenue
London EC3M 5AG
***@***.***D73A93.3724C880]


***@***.***D73A93.3724C880]
***@***.***D73A93.3724C880]
***@***.***D73A93.3724C880]

**Comment by manuelap-msft** [comment] 2021-04-26 11:57
Closing as duplicate of other Theming editor issues.

**Closed by manuelap-msft** 2021-04-26 11:57 UTC
Labels: theming
