### ISSUE TITLE
[BUG]: CreateProject Flow In Github ALM solution failed

### ISSUE THREAD

**Issue by AkashPatel136** [microsoft/powerapps-tools#649] opened 2020-12-22 14:38 UTC
**Describe the bug**
while creating a new project using Powerops app, it failed to create a project inside the environment. Create Project flow got failed at Assigned ROle action. Error message **"Content not shown due to security configuration"**

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - Power Platform Github ALM
 - Version - 1.0.0.63
 - Flow - CreateProject

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/75992078/102899796-7b74aa00-4439-11eb-8902-46e77dd2ebf0.png)

![image](https://user-images.githubusercontent.com/75992078/102900428-3d2bba80-443a-11eb-9a4c-62254c3b175b.png)

**Additional context**

**Comment by JeneferM-MSFT** [comment] 2020-12-22 14:46
removing CoeStarterKit label

**Comment by mikefactorial** [comment] 2020-12-22 15:34
Thanks for reporting this @AkashPatel136. There's an issue in the setup instructions in the readme related to creating the App Registration in AAD. I created a PR to update the documentation today #648. This error is likely due to a failure in the Flow authenticating to AAD. Take a look at the updated instructions, in particular the required API Permission which should be the Dynamics CRM permission rather than the PowerApps Runtime Service. There were a few steps in the published doc that were unnecessary as well.

**Comment by AkashPatel136** [comment] 2020-12-22 17:04
@mikefactorial Hello Mike, I have made the change as it says in the readme file. but still, get the error message. 

{
  "error": "invalid_grant",
  "error_description": "AADSTS50126: Error validating credentials due to invalid username or password.\r\nTrace ID: 0f31d148-bd68-4207-a2c2-fe75162d3b00\r\nCorrelation ID: 9d4192c1-1441-48e3-9a73-4e2718ca0e08\r\nTimestamp: 2020-12-22 16:59:20Z",
  "error_codes": [
    50126
  ],
  "timestamp": "2020-12-22 16:59:20Z",
  "trace_id": "0f31d148-bd68-4207-a2c2-fe75162d3b00",
  "correlation_id": "9d4192c1-1441-48e3-9a73-4e2718ca0e08",
  "error_uri": "https://login.microsoftonline.com/error?code=50126"
}

![image](https://user-images.githubusercontent.com/75992078/102914053-baacf600-444d-11eb-84e1-8e9699e8335d.png)

**Comment by mikefactorial** [comment] 2020-12-22 17:35
Hi @AkashPatel136 can you verify that the following settings in the PowerOps Admin App are set to a valid user's username and password? This should be an interactive user account that has access to the environment specified for each of the stages and has the Sys Admin role in the environment.

Based on the error message it looks like it's just the credentials it's complaining about. It appears that you have the app registration setup correctly now though.

![image](https://user-images.githubusercontent.com/42348035/102916663-ea5dfd00-4451-11eb-8607-f8f2418a67b9.png)

**Comment by AkashPatel136** [comment] 2020-12-22 18:33
Hi @mikefactorial for the stage owner I have entered my email and for admin I have entered my email and I am a system admin for the Power Platform.

**Comment by mikefactorial** [comment] 2020-12-22 18:43
@AkashPatel136 only thing I can think of is the password you entered might not be correct or your permissions don't extend the environments selected. Obviously, that's difficult to troubleshoot on my end, but the specific error you are getting is related to the credentials entered on that screen not being valid for one reason or another per the error_uri in the response (https://login.microsoftonline.com/error?code=50126). 

Another step to troubleshoot would be to mimic the auth request that Power Automate is doing using something like PostMan. 
![image](https://user-images.githubusercontent.com/42348035/102922108-7de7fb80-445b-11eb-8b5f-b56dd14acec2.png)

**Comment by mikefactorial** [comment] 2020-12-22 18:45
Another thought...do you have Multi Factor Authentication on your account? MFA won't work with the PowerOps solution as far as I know.

**Comment by AkashPatel136** [comment] 2020-12-22 18:50
we do have MFA enabled for all the users.

**Comment by devkeydet** [comment] 2021-01-14 12:25
I wanted to add some commentary to the discussion.  As discussed, the MFA errors are typically caused by using a username/password identity that has MFA enabled.  One way to address this is to use a username/password identity that *does not* have MFA enabled.  This is often not possible for some organizations without going through an exception process through their IT department or some other governance body.  In most organizations we encounter, their governance body prefers not to make such exceptions because username/password identities are not the way they want to handle automation identities.  They often prefer, instead to use what's often referred to as a Service Principal (SPN) identity for automation scenarios.  In order for the PowerOps app to work for an organization with such requirements, the components of the app we depend on must support SPN first.  One example is that the Actions in the GitHub workflow that runs behind the scenes needs to support SPN. Once the GitHub Actions support SPN, PowerOps will be able to inherit that support and then we can look at updating it to show how to use SPN in PowerOps. We're tracking the progress of that support via the issue in the repo below.  Note that what I have been referring to as SPN is used synonymously with appid/clientsecret, which is the topic of the issue below.

https://github.com/microsoft/powerplatform-actions/issues/14

**Comment by mikefactorial** [comment] 2021-04-27 15:35
Closing this issue as there hasn't been any recent activity. As of right now MFA isn't supported for the ALM Accelerator for Makers.

**Closed by mikefactorial** 2021-04-27 15:35 UTC
Labels: powerops
