### ISSUE TITLE
Fails on  Sync Template v2 (Check Deleted) Flows Fails  on COE Started KIT

### ISSUE THREAD

**Issue by kundan76** [microsoft/powerapps-tools#732] opened 2021-01-29 15:50 UTC
Hello Team, Sync Template v2 (Check Deleted) Flows is failing on COE starter Kit . It fails on  Newly Deleted Power Virtual Agents 

Action Failed An Action failed . No Dependent Actions Succeeded. 
After that Steps, other steps are in stopped. It runs for almost 2 hrs and fails in these steps 

Here is the [Screen Shot](https://drive.google.com/file/d/1-schDDAuCcqYy64UFfXyz7YN6fBwuuG0/view?usp=sharing)

**Comment by JeneferM-MSFT** [comment] 2021-02-01 16:02
Hello, thanks for using CoE. This was addressed via #488 Please upgrade to receive this change.

Duplicate of #488

**Closed by JeneferM-MSFT** 2021-02-01 16:02 UTC
Labels: coestarterkit
