### ISSUE TITLE
[BUG]: issue title

### ISSUE THREAD

**Issue by HenningStrand** [microsoft/powerapps-tools#507] opened 2020-10-07 13:51 UTC
**Describe the bug**
Missing Canvas Apps for DLP Customizer and Editor

**Component (please tell us which flow or app you are experiencing issues with):**
 - Core components solution
 - Version 1.70.2

**To Reproduce**
1. Follow the install steps for the core components (https://docs.microsoft.com/en-us/power-platform/guidance/coe/core-components)
2. When completed, Open Solutions->Center of Excellence - Core Components solution
3. Check to see that the mentioned Canvas apps are not in the solution. Also under 'Apps', the same two canvas apps are missing

**Expected behavior**
According to the documentation there should be 4 canvas apps found in the solution. Now there are only two: 'Set App Permissions' and 'Set Flow Permissions'

**Screenshots**
![image](https://user-images.githubusercontent.com/72507624/95339971-ee4b9b80-08b4-11eb-8dda-ea7e5f4d3697.png)

**Comment by JeneferM-MSFT** [comment] 2020-10-07 13:57
Duplicate of #500

**Closed by JeneferM-MSFT** 2020-10-07 13:57 UTC
Labels: coestarterkit
