### ISSUE TITLE
[BUG]: Unable to get a copy of the innovation backlog working

### ISSUE THREAD

**Issue by marcster** [microsoft/powerapps-tools#876] opened 2021-03-26 14:09 UTC
**Describe the bug**
I have created a copy of the innovation backlog app. When I run this copy, data for ideas already submitted is not appearing. 

**Component (please tell us which flow or app you are experiencing issues with):**
 - Innovation Backlog
 - 1.17
 - Innovation Backlog

**To Reproduce**
1. Create a copy of the innovation backlog app
2. Launch this copy
3. Data is not seen within the Ideas gallery even though the data can be seen using the Innovation Backlog app within the managed solution

**Expected behavior**
User should be able to view the data within the Ideas entity using an app created from the managed Innovation Backlog app  as a copy

**Screenshots**
Managed Innovation Backlog App
![image](https://user-images.githubusercontent.com/1025102/112643804-ab6a8980-8e3c-11eb-81b9-7566a8e9f0c5.png)

Copy of the Innovation Backlog App
![image](https://user-images.githubusercontent.com/1025102/112643947-cb9a4880-8e3c-11eb-8fc7-e8e5af705ac3.png)

**Additional context**

**Comment by JeneferM-MSFT** [comment] 2021-03-26 14:58
Can you please let me know how you created the copy? Was it just a save-as into the same environment?

**Comment by marcster** [comment] 2021-03-26 15:19
Yes, it was.

1. Created a new solution.
2. Added the existing Innovation Backlog app.
3. Opened the app to edit it.
4. "Save As" in the same environment.

**Comment by JeneferM-MSFT** [comment] 2021-03-28 14:41
Do you see errors too? As shown in #879?

**Comment by marcster** [comment] 2021-03-29 09:45
Yes, I see those errors as well.

**Comment by JeneferM-MSFT** [comment] 2021-03-29 20:47
Gotcha. This is the same issue as #879 then. I will track with that one so please follow it to find resolution.

**Comment by JeneferM-MSFT** [comment] 2021-03-29 20:48
Duplicate of #879

**Closed by JeneferM-MSFT** 2021-03-29 20:48 UTC
Labels: coestarterkit
