### ISSUE TITLE
Admin | Sync Template v2 (Power Apps User Shared With)

### ISSUE THREAD

**Issue by aakashpatel660** [microsoft/powerapps-tools#391] opened 2020-07-24 13:55 UTC
**Describe the bug**
Power Apps User Shared with Has been failing multiple times when it runs. None of the runs is getting successful. The Error message is pasted below. 

{
  "error": {
    "code": "AzureResourceManagerRequestFailed",
    "message": "The request failed with error: 'The environment '<null>' could not be found in the tenant ''.'. The tracking Id is ''.",
    "details": [
      {
        "code": "MultipleErrorsOccurred",
        "message": "There were multiple errors from the API Hubs service. Please see the details for more information.",
        "details": [
          {
            "code": "EnvironmentNotFound",
            "message": "The environment '<null>' could not be found in the tenant ''."
          }
        ]
      },
      {
        "code": "FullNonLocalizedError",
        "message": "{\"error\":{\"code\":\"EnvironmentNotFound\",\"message\":\"The environment '<null>' could not be found in the tenant ''.\"}}"
      }
    ]
  }
}

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - Core
 - Version -1.53
 - App or Flow - Sync Template (v2) Power Apps User Shared With

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/59940632/88398685-b8a61480-cd93-11ea-8fe5-f04b925dfdc6.png)

![image](https://user-images.githubusercontent.com/59940632/88398717-c52a6d00-cd93-11ea-83e9-a56c3b2406f6.png)

**Additional context**

**Comment by JeneferM-MSFT** [comment] 2020-07-24 14:17
This is resolved locally with #386 
[FixtoNullEnvBuginPowerAppsUserSharedWith_20200722134720.zip](https://github.com/microsoft/powerapps-tools/files/4972383/FixtoNullEnvBuginPowerAppsUserSharedWith_20200722134720.zip)

**Comment by aakashpatel660** [comment] 2020-07-24 15:29
Hello 

I have imported new flow and it is failing due to not able to find an app. I am guessing that if the app is deleted then the app should not be in the PowerApps App entity. Currently, flow is failing because the app does not exist in the environment but it is listed in the entity. Can you please help me why the flow is failing at that step.  


![image](https://user-images.githubusercontent.com/59940632/88407800-a383b280-cda0-11ea-9c2e-b6f1fa553507.png)


Thank you so much

**Comment by JeneferM-MSFT** [comment] 2020-07-24 16:07
This is a separate issue from the original post. For ease of consumption by other us and users, can you please post new issues for new bugs?

**Comment by JeneferM-MSFT** [comment] 2020-07-24 16:07
Duplicate of #386

**Closed by JeneferM-MSFT** 2020-07-24 16:07 UTC
Labels: coestarterkit
