### ISSUE TITLE
Sync Template v2 (Check Deleted) Flows Fails

### ISSUE THREAD

**Issue by kundan76** [microsoft/powerapps-tools#733] opened 2021-01-29 15:54 UTC
Admin | Sync Template v2 (Check Deleted) Flow runs for 2 hrs and fail on Step Newly Deleted Power Virtual Agents.
Action Failed An Action Failed . No dependednt Action Succedded . 
After this steps , No other steps run . 
Because of this the deleted Apps / Flows still shows on the List of Apps and Deleted . C

![image](https://user-images.githubusercontent.com/43321102/106296862-2db14580-6220-11eb-82b5-667eda6664ce.png)

**Comment by JeneferM-MSFT** [comment] 2021-01-29 15:58
Hello, thanks for using CoE. This was addressed via #488 Please upgrade to receive this change. 

Duplicate of #488

**Closed by JeneferM-MSFT** 2021-01-29 15:58 UTC
Labels: coestarterkit

**Comment by kundan76** [comment] 2021-01-29 20:05
IS there any process or documents on How to update to new version . We have already implemented before release and now for this issue we have downloaded the new version. I was hoping if there are documents which ecplain how to update from existing versions to new versions
Thank you

**Comment by JeneferM-MSFT** [comment] 2021-01-29 21:41
Yes indeed, here is our explanation for how to [install updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates).

Basically you have to remove any layers you created (by editing the flows) and then its like a re-install.
