### ISSUE TITLE
[BUG]: Importing CenterofExcellenceAuditComponents_1_38_managed.zip error 

### ISSUE THREAD

**Issue by daniaalchaudhry** [microsoft/powerapps-tools#784] opened 2021-02-19 18:43 UTC
**Describe the bug**
When I am trying to import CenterofExcellenceAuditComponents_1_38_managed.zip I recieve an error stating I am required to install the solution "msdyn_FlowApprovalsCore (2.0.1.1)"

Error Log:
[{"SolutionValidationResultType":"Error","Message":"The following solution cannot be imported: CenterofExcellenceAuditComponents. Some dependencies are missing. The missing dependencies are : <MissingDependencies><MissingDependency><Required key=\"14\" type=\"1\" schemaName=\"msdyn_flow_approvalresponse\" displayName=\"Approval Response\" solution=\"msdyn_FlowApprovalsCore (2.0.1.1)\" /><Dependent key=\"13\" type=\"29\" displayName=\"Admin | Archive and Clean Up v2 (Check Approval)\" id=\"{6c0522f0-6256-eb11-a812-000d3a996adc}\" /></MissingDependency></MissingDependencies> , ProductUpdatesOnly : False","ErrorCode":-2147188707,"AdditionalInfo":null}]

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: CenterofExcellenceAuditComponents_1_38_managed.zip
 - Version: 1.38

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by davidvansickle** [comment] 2021-02-19 18:53
When you create a new environment for the CoE, you have to create a simple flow to create the msdyn_flow objects initially.￼ See my Q&A post. Once you've run the flow you can delete it, the dependency objects remain.￼ 

The placeholder flow can be as simple as a button flow￼.

**Comment by JeneferM-MSFT** [comment] 2021-02-19 21:25
Correct, the order of operations has changed recently for Gov setup, you now have to [initialize flow approvals in your environment](https://docs.microsoft.com/power-platform/guidance/coe/setup-governance-components#initialize-flow-approval-tables-in-your-environment) before importing the solution. 

Thanks for using CoE
Duplicate of #753

**Closed by JeneferM-MSFT** 2021-02-19 21:25 UTC
Labels: coestarterkit
