### ISSUE TITLE
[BUG]: Admin | Sync Template v3 (Power Apps User Shared With) failed

### ISSUE THREAD

**Issue by apoorvakasbekar** [microsoft/powerapps-tools#832] opened 2021-03-13 02:23 UTC
Admin | Sync Template v3 (Power Apps User Shared With) failed
**Action 'Get_Apps_as_Admin' failed**

Solution - Core
Version - 1.98
CLEANUP - Admin | Sync Template v3 (Power Apps User Shared With)

![image](https://user-images.githubusercontent.com/69908205/111015942-29587a80-83d1-11eb-8433-eae2924d9fe7.png)

**Comment by JeneferM-MSFT** [comment] 2021-03-14 14:26
Hello, in order to help you will need to first find the failed instance (by clicking next failed) and then dive down into the failure until you find the failing action. Then we will explore.

**Comment by apoorvakasbekar** [comment] 2021-03-15 02:23
![image](https://user-images.githubusercontent.com/69908205/111095442-78361980-8563-11eb-9b56-733bac62e0e2.png)

**Below is the error:** 
ResponseSwaggerSchemaValidationFailure. The API 'powerappsforadmins' returned an invalid response for workflow operation 'Get_Apps_as_Admin' of type 'OpenApiConnection'. Error details: 'The API operation 'Get-AdminApps' requires the property 'body/value/30/properties/connectionReferences/0/iconUri' to be of type 'String' but is of type 'Null'.'

**Comment by JeneferM-MSFT** [comment] 2021-03-15 14:43
Thanks I will dupe this to your other issue in which for whatever reason the product is unable to to make the **Get Apps as Admin** call for your default environment
Duplicate of #830

**Closed by JeneferM-MSFT** 2021-03-15 14:43 UTC
Labels: coestarterkit
