### ISSUE TITLE
[BUG]: App Publish Date for null values

### ISSUE THREAD

**Issue by tchinnin** [microsoft/powerapps-tools#530] opened 2020-10-16 11:58 UTC
**Describe the bug**
At the moment, if the Power Apps LastPublishTime property is empty, the Flow Sync Apps will store the current datetime utcnow() into the Lasst Published date of the App into the CDS, which seems to be incorrect.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Core Solution
 - 1.70 Version
 - Admin | Sync Template v2 (Apps)

**To Reproduce**
Open the Flow Upsert App Record
See the  App Published field :   @{if(empty(items('Apply_to_each_App')?['properties']?['lastPublishTime']), utcNow(), items('Apply_to_each_App')?['properties']?['lastPublishTime'])}

**Expected behavior**
The App Published date field should be empty if the LastPublishTime is empty.

**Proposed solution**
Set the App Published Field to : 
@{if(empty(items('Apply_to_each_App')?['properties']?['lastPublishTime']), null, items('Apply_to_each_App')?['properties']?['lastPublishTime'])}

**Comment by tchinnin** [comment] 2020-10-16 12:36
Looks like the Upsert action in CoE doesn't accept null values....

**Comment by JeneferM-MSFT** [comment] 2020-10-16 12:50
I believe apps are now published automatically now and so this should not occur in the future.
Is this an old app? Just one of them?
Rather than complicating the flow further I'm wondering if we can just clean this up in your tenant.

**Comment by tchinnin** [comment] 2020-10-16 12:56
Yes all apps were created in 2017.

**Comment by JeneferM-MSFT** [comment] 2020-10-16 13:00
given that they are apps that have never been pusblished and created years ago, do you want to keep them? Or might you just delete them?

**Comment by tchinnin** [comment] 2020-10-16 13:02
We will probably delete them. Any way, having todays date in the published date is fine for the few app that weren't published back in 2017. 
This workaround should be used as well in the abandoned apps branch, so the flow doesnt fall in error and can continue without having to clean the the tenant.

**Comment by JeneferM-MSFT** [comment] 2020-10-19 16:44
Duplicate of #531 
Thank you for using CoE, this is fixed with your other issue #531.

**Closed by JeneferM-MSFT** 2020-10-19 16:44 UTC
Labels: coestarterkit
