### ISSUE TITLE
[BUG]: issue title

### ISSUE THREAD

**Issue by RaulMero** [microsoft/powerapps-tools#563] opened 2020-11-11 09:57 UTC
**Describe the bug**
On Core Components update from 1.39 to 1.70.6 fails giving error code 80041A06  
https://support.microsoft.com/en-us/help/4346891/the-import-of-solution-solution-name-failed-error-occurs-in-dynamics-3
and Exception message
'Attribute admin_rpamodifiedon is a String, but a DateTime type was specified'
On the existing entity the datatype of this field cannot be modified because it is a managed solution. Tried to add a field with same name and text data type, but importing the Core Components keeps failing.

How do I get this issue bypassed or how to get the import done?

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Core Components
 - Version 1.70.6
 - CenterofExcellenceCoreComponents

![image](https://user-images.githubusercontent.com/74295479/98797291-0ca53980-2415-11eb-9137-dafc7098338c.png)

**Comment by JeneferM-MSFT** [comment] 2020-11-11 13:29
Hello. This is known, you can import an interim solution in #491 and then import the current version. 

Thank you for using CoE, and enjoy the upgrade! 
Duplicate of #491

**Closed by JeneferM-MSFT** 2020-11-11 13:29 UTC
Labels: coestarterkit
