### ISSUE TITLE
[BUG]: Issues with CDS Default Environment

### ISSUE THREAD

**Issue by matrixzonee** [microsoft/powerapps-tools#504] opened 2020-10-07 12:29 UTC
**Describe the bug**
There is a bug in the "Admin | Sync Template v2 (Flows) runs failed" Power Automate. Currently, the Power Automate fetched the Environment Name from Environment ID which does not have the "default" prefix in the CDS Default environment. I was able to get the correct name after changing the field to Environment Name Field in the CDS Entity.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [Core]
 - Version [[1.23]
 - Flow [Admin | Sync Template v2 (Flows) runs failed

**To Reproduce**
1. Go to Power Automate
2. Run the "Admin | Sync Template v2 (Flows) runs failed"
3. Open the Environment CDS Entity and the default Environment will have an issue in the same

**Expected behavior**
The expectation was the "Admin | Sync Template v2 (Flows) runs failed" Power Automate will be able to fetch all the CDS environment from the Tenant including the default environment, Because of the "default" prefix in the name, the "Admin | Sync Template v2 (Flows) runs failed" Power Automate failed.

**Screenshots**
![image](https://user-images.githubusercontent.com/6177057/95330862-10d3b980-08a1-11eb-85a6-639dd8316873.png)

**Additional context**

**Comment by JeneferM-MSFT** [comment] 2020-10-07 13:43
Duplicate of #505

**Closed by JeneferM-MSFT** 2020-10-07 13:43 UTC
Labels: coestarterkit

**Comment by matrixzonee** [comment] 2020-10-07 14:08
The Core Component Version is 1.70.2
Can you please reopen the bug?
