### ISSUE TITLE
[BUG]: Admin | Sync Template v3 (Sync Flow Errors)

### ISSUE THREAD

**Issue by dchrist27** [microsoft/powerapps-tools#841] opened 2021-03-16 13:44 UTC
Core Components 1.98

Since upgrading core components last week to 1.98 the Sync Flow Errors flow is running but the notification is not being delivered to the Admin Email address defined in environment variable.

![image](https://user-images.githubusercontent.com/52799471/111317212-ef39e380-8631-11eb-9274-0ad31f993426.png)

Headers before upgrade:

![image](https://user-images.githubusercontent.com/52799471/111318259-e09ffc00-8632-11eb-991d-7daeb070f1af.png)

After upgrade to 1.98

![image](https://user-images.githubusercontent.com/52799471/111318511-1f35b680-8633-11eb-929e-ae7479233dac.png)

Dave

**Comment by dchrist27** [comment] 2021-03-16 13:50
Apologies...I just saw/read bug #815.  I'll follow that approach until the April update is released.

**Comment by JeneferM-MSFT** [comment] 2021-03-16 13:51
No problem at all, apologies for the inconvenience, and thanks for doing that research! And thanks for using CoE. 
Duplicate of #815

**Closed by JeneferM-MSFT** 2021-03-16 13:51 UTC
Labels: coestarterkit
