### ISSUE TITLE
[BUG]: Receive failures on Admin | Sync Audit Log with message "A record with matching key values already exists"

### ISSUE THREAD

**Issue by ctofts86** [microsoft/powerapps-tools#617] opened 2020-12-04 10:11 UTC
**Describe the bug**
Admin | Sync Audit Logs Flow failing with error message: 
""error": {
    "message": "--batchresponse_2058db2f-a8e4-4e4a-abf6-9680fbbdacfc\r\nContent-Type: application/http\r\nContent-Transfer-Encoding: binary\r\n\r\nHTTP/1.1 412 Precondition Failed\r\nREQ_ID: 5890c545-2264-46b1-9bfa-d836d469b983\r\nContent-Type: application/json; odata.metadata=minimal\r\nOData-Version: 4.0\r\n\r\n{\"error\":{\"code\":\"0x80040237\",\"message\":\"A record with matching key values already exists.\"}}\r\n--batchresponse_2058db2f-a8e4-4e4a-abf6-9680fbbdacfc--\r\n"
  }"

This Flow ran without issue on initial set up, and is now experiencing multiple failures with this same error message.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: CoE - Audit Logs
 - Version: 1.25
 - App or Flow: Admin | Sync Audit Logs

**To Reproduce**
1. Flow runs on recurrence
2. Failures on switch case "LaunchPowerApp"
3. Receive error messages in action "Update a record" within the above switch case.

**Expected behavior**
Flow success

**Screenshots**
![image](https://user-images.githubusercontent.com/47523775/101150972-e8560a80-3618-11eb-9bec-2686a3d0b364.png)

**Additional context**
Attempting to adopt CoE usage within our large organisation.

**Comment by JeneferM-MSFT** [comment] 2020-12-08 15:46
hello, this is a product bug and the product team is investigating. Please post a ticket if you are able.  
Duping to the issue where we are tracking already. Thanks for using CoE 
Duplicate of #606

**Closed by JeneferM-MSFT** 2020-12-08 15:46 UTC
Labels: coestarterkit
