### ISSUE TITLE
[BUG]: App Archival is not getting deleted - default environments not writing correctly to Archive table.

### ISSUE THREAD

**Issue by AkashPatel136** [microsoft/powerapps-tools#666] opened 2021-01-05 14:13 UTC
**Describe the bug**
I am an admin and I received approval for an app that the owner does not exist, so I approved the request for archival. The record was created on 12/7/2020 on the Archival Approval table on Governance Components solution. Today I was checking few records and I came accord the record which was still Active on the PowerApp Apps table. If you can explain to me how this data get sync. 

Based on my understanding is that if App status is active in the PowerApps App table that means the app still exists and it is not deleted. 

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - Core & Governance
 - Version - Core = 1.71.7 & Governance = 1.25
 - App or Flow [e.g. Sync Template (v2)]

**To Reproduce**

**Expected behavior**
IF application/flow is marched for approval for archival approval then it should delete the app/flow from the environment and update the record as deleted. 

**Screenshots**

**PowerApps App Table**
![image](https://user-images.githubusercontent.com/75992078/103655738-ada40280-4f35-11eb-917b-fb30380699c8.png)
![image](https://user-images.githubusercontent.com/75992078/103655744-b3014d00-4f35-11eb-82b3-0fa816c2e493.png)
![image](https://user-images.githubusercontent.com/75992078/103655755-b7c60100-4f35-11eb-8acc-4a4cdb0c3a17.png)
![image](https://user-images.githubusercontent.com/75992078/103655775-be547880-4f35-11eb-9698-40c4e5f1261c.png)

**Additional context**

**Comment by JeneferM-MSFT** [comment] 2021-01-05 16:43
Did you set the **_Auto Delete On Archive_** environment variable to delete? We have added it as a fail proof to ensure admins are ready to start deleting from the environment. 
See [Approval Clean Up](https://docs.microsoft.com/power-platform/guidance/coe/governance-components#admin--approval-clean-up)
or [setup instructions](https://docs.microsoft.com/power-platform/guidance/coe/setup-governance-components#update-environment-variables)

**Comment by AkashPatel136** [comment] 2021-01-05 19:38
Auto Delete On Archive Environment Variable is set to Yes

**Comment by JeneferM-MSFT** [comment] 2021-01-05 20:10
What identity is the action under? 
So if you go to edit the flow and see what identity has the connection reference
![image](https://user-images.githubusercontent.com/62659043/103693855-cf5db380-4f4e-11eb-86bc-934f30ba86ae.png)

If not yours, go and edit the Connection Reference from the flow details page
![image](https://user-images.githubusercontent.com/62659043/103693967-016f1580-4f4f-11eb-8756-e291e103cfbf.png)

**Comment by AkashPatel136** [comment] 2021-01-05 20:53
It is using my credentials for the connection reference

**Comment by JeneferM-MSFT** [comment] 2021-01-05 22:49
What error message is being thrown from Check for Perms, and what is being thrown for Modify Flow Owners as Admin?

**Comment by JeneferM-MSFT** [comment] 2021-01-06 00:39
I did find an issue locally where, if there is a broken connection in a flow, then the "Check for Perms" is failing with this error:
![image](https://user-images.githubusercontent.com/62659043/103715068-84569700-4f74-11eb-8700-06a378a49dc5.png)

I have added another catch for this to delete anyway. 
Let me know if that is the error you were seeing, or if something else.

**Comment by AkashPatel136** [comment] 2021-01-06 13:54
i have a different error message 

![image](https://user-images.githubusercontent.com/75992078/103775962-c62b2000-4ffc-11eb-9185-59b76a506827.png)

**Comment by JeneferM-MSFT** [comment] 2021-01-06 15:38
OK. That is an expected error when you arent an owner of a flow. 
Basically, the connector only allows you to check permissions if you own the flow, doesnt matter if you are a tenant admin. That is why we catch and do the call to Modify Flow Owners as Admin. 
Can you please see what error you get for this action: Modify Flow Owners as Admin

**Comment by AkashPatel136** [comment] 2021-01-06 15:47
![image](https://user-images.githubusercontent.com/75992078/103788259-a13ea900-500c-11eb-8eee-2075ad55c94d.png)

**Comment by JeneferM-MSFT** [comment] 2021-01-06 16:03
alright well I dont know why you would have that as forbidden if you have the permissions you state. 
The new version I have releasing in the future will try to delete in this case anyway. Can you see if you are able to delete this flow manually? If not, then you have an issue with your permissions. 
In order to get access, use the Set Flow Permissions app from the Core Solution

**Comment by AkashPatel136** [comment] 2021-01-06 17:08
when I tried to delete the below flow it throws an error message. 

![image](https://user-images.githubusercontent.com/75992078/103798493-cd135c00-5017-11eb-9a4f-d13d2dbed05a.png)

![image](https://user-images.githubusercontent.com/75992078/103798540-dbfa0e80-5017-11eb-94fd-d166dd109120.png)


{
  "error": {
    "code": "ConnectionAuthorizationFailed",
    "message": "The caller with object id '532eb18a-aee0-41be-a6e3-722ba72e481a' does not have permission for connection 'a14e98ee-e93d-439a-8f47-2e43aa0f9342' under Api 'shared_logicflows'."
  }
}

**Comment by AkashPatel136** [comment] 2021-01-06 18:44
After my start approval flow is being successful I tried to run the clean-up flow but it still fails.

**Comment by JeneferM-MSFT** [comment] 2021-01-06 19:44
I'm afraid the issue you are seeing is about your permissions then and not our tooling. 
One last thing to try, would be to grant yourself permission to the flow using the Set Flow Permissions app from Core, then go to the Flow Settings and Delete
![image](https://user-images.githubusercontent.com/62659043/103813116-6e001800-5014-11eb-9df8-3e5b2d89c555.png)

**Comment by AkashPatel136** [comment] 2021-01-06 19:56
I can do that but the concern for me is that I have 142 flows and for each, I have to do that and probably in the future also until a new version of COE does not come out.

**Comment by JeneferM-MSFT** [comment] 2021-01-06 19:59
Yes, the ability to augment permissions is something that is needed. 
If you are able to augment them using that app, that will be interesting. 
It appears as though you do not have correct permissions right now. This flow works for most people to add permissions to the flow and delete

**Comment by AkashPatel136** [comment] 2021-01-06 20:42
What I found out is interesting that in the below images I created a flow that gets flow details from my default environment. In Get Flow as Admin action where it gave me an option to chose an environment from my tenant and I selected my default environment and it worked for me, but instead of selecting the environment if I just enter environment ID it throws the error message. 

The issue I found is that my default environment ID is **Default-68a7ff20-812f-4738-90ea-0b1051846f74** and in COE it says my default environment ID is **68a7ff20-812f-4738-90ea-0b1051846f74**. so I am thinking it is looking for **Default-** at the beginning of environment ID which is stored in COE. 

I did show this to @topness-msft today and he also thinks this is a really interesting issue. 

![image](https://user-images.githubusercontent.com/75992078/103814535-d6102780-502f-11eb-9020-82ca0d472c92.png)

Did not work this
![image](https://user-images.githubusercontent.com/75992078/103814605-f50eb980-502f-11eb-9b3d-d2ca5706beab.png)

Did work 
![image](https://user-images.githubusercontent.com/75992078/103817547-e7a7fe00-5034-11eb-9861-aaf3855301c2.png)

**Comment by JeneferM-MSFT** [comment] 2021-01-06 21:36
Phil's awesome! Thanks for investigating this deeper, we often fall into bugs with the default environment for this very reason, some connectors expect it with the "Default-" and others without. 
In this case though, we do already send as Default-, as shown here:
![image](https://user-images.githubusercontent.com/62659043/103821874-e5897380-5023-11eb-9047-e719a624dc0e.png)

I'm not sure what's happening on your side, but I think that the final catch I put in place will still work for you to get around it, as long as you do have sufficient permissions to modify and delete. 

Let me try to get you a PR of that here to test

**Comment by JeneferM-MSFT** [comment] 2021-01-06 21:41
[CenterofExcellenceAuditComponents_1_26_managed.zip](https://github.com/microsoft/powerapps-tools/files/5778311/CenterofExcellenceAuditComponents_1_26_managed.zip)

**Comment by AkashPatel136** [comment] 2021-01-07 14:17
I want to leave this case open until next week and I will update based on the flow runs next week.

**Comment by JeneferM-MSFT** [comment] 2021-01-07 15:02
Yes of course. I would like to leave it open until we ship the fix actually so that others can find it.

**Comment by WouterF** [comment] 2021-01-11 14:57
@JeneferM-MSFT, can you show which changes you made in the flow?
I cannot import the whole new solution again just as a test because we adapted the texts of all the emails/approval mails to fit better to our organization. There were also some spelling mistakes in it.
I would like to add the fix manually to the flow.
Thanks

**Comment by JeneferM-MSFT** [comment] 2021-01-11 15:12
I'm not 100% sure I remember unfortunately as I made several changes in my attempt to fix. 
But I believe all I did in the end was change the Configure Run After of "Delete Flow"

**Comment by AkashPatel136** [comment] 2021-01-11 22:21
Hi @JeneferM-MSFT 

I am having the same issue for the other flows where my Default Environment cannot be found because it does not start with Default- is there anywhere in the flow I can change this so it so it will store as a Default-65........... like that?

**Comment by JeneferM-MSFT** [comment] 2021-01-12 00:03
Hi Akesh, Default-was not the cause for this case, as far as I can tell. Can you confirm that my fix above fixed this particular issue please?

Then if you have other instances of the CoE flows failing for default, please post them separately, and I'll need to know which flow and which call is failing. To our knowledge we have caught all these so happy to fix more individual cases if you find them.

**Comment by WouterF** [comment] 2021-01-12 14:08
Hi @JeneferM-MSFT, I tried the fix above by changing the run-after condition, but the flows keeps returning the same error because there is no "Default-" in front of the environment id.
Is there already a new version of the CoE governance solution that has this issue fixed?
Don't understand me wrong, I'm very happy that the CoE exists, but is it maybe possible to mark versions of the CoE with beta/stable. I would prefer to wait for a month or longer to upgrade the CoE, if I'm sure that the version is stable.
Until now, every time I upgrade the CoE, I have new unexpected issues.
However, thanks for the time and effort you all put in all of this, because it is not easy. But if possible I would be very happy with CoE versions marked as stable so I can install them without a lot of issues.
Thanks

**Comment by JeneferM-MSFT** [comment] 2021-01-12 14:13
The CoE is a starter kit intended to help people understand how to monitor their tenants. It isn't officially supported by Microsoft, and it isn't for everyone.

This flow is old and this issue is new, and I dont repro locally. So I dont know what is going on. Might be a product bug or something.

When you say its not working because you dont have default-, can you sahre what you mean? My repros work for the default environment.

**Comment by WouterF** [comment] 2021-01-12 14:17
Hi @JeneferM-MSFT, thanks for the fast response.
I updated the flow as indicated: Changing the run-after conditions:
![image](https://user-images.githubusercontent.com/5990852/104325534-03098200-54e9-11eb-8a00-a3023e30bdda.png)
However, I still get the same error message:
![image](https://user-images.githubusercontent.com/5990852/104325757-449a2d00-54e9-11eb-8ff1-b195265ca498.png)
Thanks

**Comment by JeneferM-MSFT** [comment] 2021-01-12 15:23
Let me explain the flow and see if you can let me know where we are differing. 
I added some questions **_inline_**, if you can please answer them that might help figure out what you are seeing.

1) We pull the list of flows from our custom archive table instead of the product in order to reduce API calls. 

![image](https://user-images.githubusercontent.com/62659043/104328880-87d4ab80-54a9-11eb-833d-23b2cb37f0f5.png)

2) In the ArchiveApproval Table, the envt name column is stored with the default- prefix for default envt. **_Can you confirm this is the case for you?_** 
![image](https://user-images.githubusercontent.com/62659043/104329751-83f55900-54aa-11eb-9451-033406d6405d.png)

3) We next do a call to Get Flow, we do this because we want to check to see if you already have permissions as a user. 
![image](https://user-images.githubusercontent.com/62659043/104330760-899f6e80-54ab-11eb-9540-931d0674123e.png)

We expect this call to fail if you are not listed as an editor or user for that flow, even if you are all the levels of admin.
**_Can you please confirm what error message you see for this call?_** 

Here is the expected failure if you just dont have permissions
![image](https://user-images.githubusercontent.com/62659043/104332796-c9ffec00-54ad-11eb-9807-f1a56dfbb668.png)

This GitHub issue helped surface other reasons Get Flow might fail though. For example a current product bug (fix on the way) which causes it to fail for flows with certain connectors like the CDS Native (Current) connector will fail due to a product bug
Here's what that failure looks like
![image](https://user-images.githubusercontent.com/62659043/104333076-13503b80-54ae-11eb-9d54-b7da69b721ce.png)


4) The expected forbidden error is why we catch this call at the next step and add your user
**_Can you please validate that the values in this call make sense for your user?_** 
![image](https://user-images.githubusercontent.com/62659043/104333725-cde03e00-54ae-11eb-9d5e-f05916cc8150.png)

5) Now there may be other reasons that Get Flow fails. 
The example from above, where we fail for some connectors due to product bug, if you already had permissions to the flow then the call to modify them will fail. 
**_Can you please let me know what failure you see for this call? Please include downloaded output_** 
![image](https://user-images.githubusercontent.com/62659043/104333312-55797d00-54ae-11eb-8b7e-17db1c101f0a.png)


6) Which is why we now also run the delete call even if the above call failed

**Comment by WouterF** [comment] 2021-01-12 15:38
Hi @JeneferM-MSFT,
Please find below the answers to your questions:
**In the ArchiveApproval Table, the envt name column is stored with the default- prefix for default envt. Can you confirm this is the case for you?**
This is not the case. The default- prefix is not here, all without this prefix.
![image](https://user-images.githubusercontent.com/5990852/104335473-aeb7cf80-54f3-11eb-9845-41647cc4e668.png)

**We expect this call to fail if you are not listed as an editor or user for that flow, even if you are all the levels of admin.
Can you please confirm what error message you see for this call?**
Same error as you.
![image](https://user-images.githubusercontent.com/5990852/104335739-fb9ba600-54f3-11eb-81cc-ef02f420ed81.png)

**The expected forbidden error is why we catch this call at the next step and add your user
Can you please validate that the values in this call make sense for your user?**
![image](https://user-images.githubusercontent.com/5990852/104336006-3b628d80-54f4-11eb-8f01-8770e3d2006e.png)

**Now there may be other reasons that Get Flow fails.
The example from above, where we fail for some connectors due to product bug, if you already had permissions to the flow then the call to modify them will fail.
Can you please let me know what failure you see for this call? Please include downloaded output**
![image](https://user-images.githubusercontent.com/5990852/104336325-9300f900-54f4-11eb-862c-6b6b3402baa4.png)

Thanks for the help. If you need more info, please let me know.

**Comment by JeneferM-MSFT** [comment] 2021-01-12 15:50
Your image for the archive table did not come through, but I presume you looked for your default envt's GUID and found it to not have the Default-prefix?

**Comment by WouterF** [comment] 2021-01-12 17:25
@JeneferM-MSFT, indeed the default environment does not have the default-prefix. In all of the records in the "Archive Approval" table, there is the same format of environment id's without prefix.
This is probably the reason why this flow fails, a product change.
I guess that the product team started removing the default prefix because it is too complex? Or am I wrong?

**Comment by JeneferM-MSFT** [comment] 2021-01-13 14:39
Thank you Wouter. I would not have predicted that was the spot of error so this was very useful. I will investigate.

**Comment by JeneferM-MSFT** [comment] 2021-01-18 16:32
The fix is in testing, expect to ship this week. 
Thanks

**Comment by JeneferM-MSFT** [comment] 2021-02-01 18:19
Hello. this fix for this was released today. The fix is in the "start approval" flows in that we fetch the proper name (including pre-fix) to put in the archival table. 
![image](https://user-images.githubusercontent.com/62659043/106500611-e244a480-6476-11eb-954d-df1c7f7d60c9.png)

Please be sure to remove any unmanaged layers before updating as described in [installing upates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates).

And thanks for helping make CoE great!

**Closed by JeneferM-MSFT** 2021-02-01 18:19 UTC
Labels: coestarterkit

**Comment by WouterF** [comment] 2021-02-02 09:23
@JeneferM-MSFT , the flow is still failing.
Should I clean the "Archive Approvals" table because it contains the old records?
![image](https://user-images.githubusercontent.com/5990852/106579155-a2e28a80-6540-11eb-8330-21b9d487426d.png)

**Comment by JeneferM-MSFT** [comment] 2021-02-02 14:17
Yes thats correct. This will not go back and fix old entries, it will just correct new entries. 
Thank you for asking, I hadnt thought to mention that in this fix.
