### ISSUE TITLE
[BUG]: Admin | Sync Template v3 (Apps)

### ISSUE THREAD

**Issue by tkudya** [microsoft/powerapps-tools#851] opened 2021-03-18 14:02 UTC
**Describe the bug**
When I run the Admin | Sync Template v3 (Apps), fails with the following message.
Flow run failed.Error
Action 'Get_PowerApp_Owner_profile_for_Editted' failed

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Core
 - Version 1.98
 - App or Flow Sync Template v3 (Apps)

**To Reproduce**
run the Admin | Sync Template v3 
**Screenshots**
![image](https://user-images.githubusercontent.com/78653328/111638490-48e90c00-87f2-11eb-851f-3522823c22f2.png)
![image](https://user-images.githubusercontent.com/78653328/111638608-63bb8080-87f2-11eb-9720-aa73f47cefe5.png)
![image](https://user-images.githubusercontent.com/78653328/111638671-7635ba00-87f2-11eb-98a2-c686a788b3c6.png)
![image](https://user-images.githubusercontent.com/78653328/111638726-86e63000-87f2-11eb-80ef-073b3c6c644a.png)

Raw Inputs
{
    "content": [
        {
            "iconUri": "https://az818438.vo.msecnd.net/icons/sharepointonline.png",
            "displayName": "SharePoint",
            "isOnPremiseConnection": false,
            "isCustomApiConnection": false,
            "bypassConsent": false,
            "id": "/providers/Microsoft.PowerApps/scopes/admin/apis/shared_sharepointonline"
        }
    ],
    "schema": {
        "type": "array",
        "items": {
            "type": "object",
            "properties": {
                "iconUri": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "apiTier": {
                    "type": "string"
                },
                "isOnPremiseConnection": {
                    "type": "boolean"
                },
                "isCustomApiConnection": {
                    "type": "boolean"
                },
                "bypassConsent": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                }
            },
            "required": [
                "iconUri",
                "displayName",
                "apiTier",
                "isOnPremiseConnection",
                "isCustomApiConnection",
                "bypassConsent",
                "id"
            ]
        }
    }
}

**Comment by manuelap-msft** [comment] 2021-03-18 15:18
Hello,

thank you for raising this. Would you be able to also share the Input that is causing this issue? It would be the **Content** under Inputs from the Parse JSON action.

Thank you
Manuela

**Comment by manuelap-msft** [comment] 2021-03-18 15:55
Duplicate of #812

**Closed** 2021-03-18 16:04 UTC
Labels: coestarterkit
