### ISSUE TITLE
[BUG]: Updating core components solution import error

### ISSUE THREAD

**Issue by keharrin** [microsoft/powerapps-tools#738] opened 2021-02-01 19:17 UTC
**Describe the bug**
I am attempting to update the CenterofExcellenceCoreComponents solution with a from version 1.45 to 1.85

Import is unsuccessful due to Attribute admin_rpamodifiedon is a String, but a DateTime type was specified.

I am unable to delete this column in the RPA table.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by JeneferM-MSFT** [comment] 2021-02-01 19:47
Hello, you will need to upgrade to the interim solution (1.62) shown in #515 
And then try again to upgrade to 1.85. 

Thanks for using CoE!
Duplicate of #515

**Closed by JeneferM-MSFT** 2021-02-01 19:47 UTC
Labels: coestarterkit

**Comment by keharrin** [comment] 2021-02-02 20:51
Hi Jennifer Thanks.  I was able to import the version 1.60.5 from the #515 successfully.  However, when I attempt to import 1.85 I am getting a missing dependencies error:
[{"SolutionValidationResultType":"Error","Message":"The following solution cannot be imported: CenterofExcellenceCoreComponents. Some dependencies are missing. The missing dependencies are : <MissingDependencies><MissingDependency><Required key=\"16\" type=\"1\" schemaName=\"admin_archiveapproval\" displayName=\"Archive Approval \" solution=\"Active\" /><Dependent key=\"17\" type=\"1\" schemaName=\"admin_app\" displayName=\"PowerApps App\" /></MissingDependency><MissingDependency><Required key=\"16\" type=\"1\" schemaName=\"admin_archiveapproval\" displayName=\"Archive Approval \" solution=\"Active\" /><Dependent key=\"18\" type=\"1\" schemaName=\"admin_flow\" displayName=\"Flow\" /></MissingDependency></MissingDependencies> , ProductUpdatesOnly : False","ErrorCode":-2147188707,"AdditionalInfo":null}]

**Comment by JeneferM-MSFT** [comment] 2021-02-02 21:18
Hello, yes we shipped with an accidental dependency. The new version of core that is out will work for you.

**Comment by olivaresFCO10** [comment] 2023-10-16 23:13
> Hello, yes we shipped with an accidental dependency. The new version of core that is out will work for you.

Hi , pls I need your help with the same message, maybe is happening again, I just trying to import the CenterofExcellenceCoreComponents_4.16_managed.zip but i got the same error message, Is something wrong with the package again? (pls feel free to mailing the response manuelrr182@gmail.com
