### ISSUE TITLE
[BUG]: Admin | Sync Flow (XX) - Error if "admin_modified" is NULL

### ISSUE THREAD

**Issue by aschauera** [microsoft/powerapps-tools#547] opened 2020-10-29 10:26 UTC
**Describe the bug**
The Admin | Sync Flows (XX) contain a condition to check if the entitiy (app|flow|..) is already in CoE. The check for the modified date fails if no value is present in admin_XXmodifiedon.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution CORE
 - Version 1.70.6
 - App or Flow Sync Template v2 apps | Sync Template v2  flows

**To Reproduce**
Create App Entity with admin_modifiedon field empty.
Start TEST for Admin | Sync Template (v2) (Apps). Inspect "apply to each app"

**Expected behavior**
Action "only proceed if changed since last updated in CoE should check field admin_modifiedon for NULL

**Screenshots**
![image](https://user-images.githubusercontent.com/36595952/97556174-60f1f780-19d9-11eb-936f-ba9d521de0d5.png)

**Comment by JeneferM-MSFT** [comment] 2020-10-30 13:20
Can you please help me understand how you did this step: **_Create App Entity with admin_modifiedon field empty._**

I am seeing this field be populated for apps when they are created.

**Comment by eBentl** [comment] 2020-11-09 03:33
Hi @JeneferM-MSFT  I have also had this occur with two of my entries (though I couldn't say why)
I wrapped the left-hand comparison in a coalesce to generate an empty string and found that the items were fixed when they were upserted the second time

**Comment by JeneferM-MSFT** [comment] 2020-11-09 14:34
Thank you! Can you share the expression you used and where you used it explicitly? I'm hesitant to try on fix on my side without a repro but if I can copy directly from you, then I'm happy to make the change.
Thanks for helping make CoE great!

**Comment by eBentl** [comment] 2020-11-09 20:56
No worries :) Below is the expression and screenshot of where it was implemented for the App flow which is where my issue was. My last test only evaluated as true for the two apps which had null values so I don't believe it is having any unintended consequences. I would imagine you should be able to reproduce it by just editing an existing 'admin_app'/'admin_flow' entity record and stripping out the admin_modifiedon field value.
**coalesce(first(body('Get_App_from_CoE')?['value'])?['admin_flowmodifiedon'],'')**
![image](https://user-images.githubusercontent.com/43974241/98594532-eace8880-2328-11eb-871b-691dd3955ebe.png)

**Comment by JeneferM-MSFT** [comment] 2020-11-11 22:11
I dont repro even when I manually delete the data in that column. 
However everything still runs fine with your recommended change so I put it in. 
Local fix will ship with the next version of the toolkit, likely next week.
Thanks for using CoE! And for helping make it better.

**Comment by JeneferM-MSFT** [comment] 2020-11-16 18:14
This has been resolved in the new version of the toolkit released today: [https://aka.ms/CoEStarterKitDownload](https://aka.ms/CoEStarterKitDownload)

**PLEASE NOTE:** In order to receive updates, you now have to remove all unmanaged layers from any apps/flows you have created in the past. Otherwise you will not see the changes for the app/flow that maintains its unmanaged layers. 

For more details on what this looks like, please view [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates)

Thanks for using CoE, and helping make it great with your feedback.

**Closed by JeneferM-MSFT** 2020-11-16 18:14 UTC
Labels: coestarterkit
