### ISSUE TITLE
Action 'List_Flows_as_Admin' failed for the flow in COE  CLEANUP - Admin | Sync Template v3 (Check Deleted)

### ISSUE THREAD

**Issue by RPadhy** [microsoft/powerapps-tools#982] opened 2021-04-29 20:19 UTC
**Describe the bug**
The below 2 actions are failing in the flow " CLEANUP - Admin | Sync Template v3 (Check Deleted)" under COE core component. 
1) List Flows as Admin
2) Get Flows as Admin
This is failing for the default environment only while lopping in.

Error Details: The Response is not in JSON format. 

when I look into the output of the action, it is showing the below error.

innerError | "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\"\"http://www.w3.org/TR/html4/strict.dtd\">\r\n<HTML><HEAD><TITLE>Bad Request</TITLE>\r\n<META HTTP-EQUIV=\"Content-Type\" Content=\"text/html; charset=us-ascii\"></HEAD>\r\n<BODY><h2>Bad Request - Request Too Long</h2>\r\n<hr><p>HTTP Error 400. The size of the request headers is too long.</p>\r\n</BODY></HTML>\r\n"
-- | --

**To Reproduce**

**Expected behavior**
The flow should complete successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/43860631/116613419-a5b60700-a906-11eb-87df-cf3fa7903c36.png)

**Additional context**
We upgraded the COE from version 1.45 to 2.01 and As per the instruction in below URL, tuned on the flow " CLEANUP - Admin | Sync Template v3 (Check Deleted)"
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#activate-the-sync-template-flows

**Comment by JeneferM-MSFT** [comment] 2021-04-30 14:14
Hello you have hit a product bug. Please see #941 there is a flow at the bottom you can run to see this repro outside of the context of the toolkit. Please post a support ticket for assistance. 
Closing as Duplicate of #941

**Closed by JeneferM-MSFT** 2021-04-30 14:14 UTC
Labels: coestarterkit

**Comment by RPadhy** [comment] 2021-04-30 15:25
I found another ticket where similar issue was reported. Is it good try the flow to clear connection references suggested in the ticket? Below is the ticket#
https://github.com/microsoft/powerapps-tools/issues/905

**Comment by JeneferM-MSFT** [comment] 2021-04-30 16:00
I do not think these are related no. That cleanup happens in a different part of the flow.
