### ISSUE TITLE
[BUG]: Sync v3 Apps flow fails

### ISSUE THREAD

**Issue by tsegato** [microsoft/powerapps-tools#713] opened 2021-01-21 14:25 UTC
I dont get data in second time the flow is called. I get following errors. Any pointers how to troubleshoot this?

![image](https://user-images.githubusercontent.com/43033640/105364095-0abdda80-5bfd-11eb-9446-2bed96cef122.png)

**Comment by JeneferM-MSFT** [comment] 2021-01-21 15:30
Hello, you have highlighted a failure that is caught. So your failure if further down, that said I am certain I know the failure. It is fixed in an upcoming released and you can local fix if you'd like while you await ship. 
Duplicate of #681 
Thanks for using CoE.

**Closed by JeneferM-MSFT** 2021-01-21 15:30 UTC
Labels: coestarterkit
