### ISSUE TITLE
[BUG]: You are not permitted to make flows in this '...'. Please switch to the default environment, 

### ISSUE THREAD

**Issue by WouterF** [microsoft/powerapps-tools#683] opened 2021-01-11 12:54 UTC
**Describe the bug**
Admin | Approval Clean Up flow fails. 
The service account is power platform administrator so should have enough permissions.
Something that draws our attention is that there is no "Default-" in front of the id of the default environment, these are 2 examples:
![image](https://user-images.githubusercontent.com/5990852/104187312-e3eeef80-5417-11eb-870b-4034a9a65291.png)
For more info about the flow error see screenshots below.

**Edit:** It seems like the person in this issue has the same problem: https://github.com/microsoft/powerapps-tools/issues/666

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: Governance
 - Version: 1.25
 - App or Flow: Admin | Approval Clean Up

**Expected behavior**
Flow should not fail because it is ran by a service account that is power platform administrator.

**Screenshots**
![image](https://user-images.githubusercontent.com/5990852/104184715-2e6e6d00-5414-11eb-8c7f-81a52e49fe07.png)
![image](https://user-images.githubusercontent.com/5990852/104184641-0c74ea80-5414-11eb-9544-9a319b89f658.png)

**Additional context**

**Comment by JeneferM-MSFT** [comment] 2021-01-11 14:51
Please see the solution PR sent in #666 
I believe you are experiencing that same issue, and would like to hear if my tweak fixes if for you. 
And by fix I mean this may still fail but it is caught, and the flow deleted.

Duplicate of #666

**Closed by JeneferM-MSFT** 2021-01-11 14:51 UTC
Labels: coestarterkit
