### ISSUE TITLE
How Do I Untangle an audit log from being multi tenant to a single tenant?

### ISSUE THREAD

**Issue by NPrice99** [microsoft/powerapps-tools#594] opened 2020-11-24 15:18 UTC
**Describe the bug**
Somehow my Audity Log has gone from a single tenant audit log to a multi tenant audit log.  How do I make my Audit Log a Single Tenant Audit Log again ?

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Core
 - Version 1.75.1
 - App or Flow [e.g. Sync Template (v2)]

**To Reproduce**

**Expected behavior**
Audit Log SHould be Single Tenant

**Screenshots**

**Additional context**
How to set up an audit log as a single tenant audit log ?

**Comment by JeneferM-MSFT** [comment] 2020-11-24 15:50
Duplicate of #592 

I put a recommendation in your original

**Closed by JeneferM-MSFT** 2020-11-24 15:50 UTC
Labels: coestarterkit
