### ISSUE TITLE
Can't create API 'shared_flowpush' connection

### ISSUE THREAD

**Issue by katmcelveen** [microsoft/powerapps-tools#883] opened 2021-03-29 17:56 UTC
Hello,

I am just getting started with the CoE but am having trouble. I started with the most recent version of Core Components (1_98_managed(1)) but when attempting to import I am being prompted to create a Notifications connection for API 'shared_flowpush'.

When I attempt to create this connection I get this error:
![image](https://user-images.githubusercontent.com/63921352/112878727-46aa6b80-9096-11eb-81c3-ddae3c08a0aa.png)

I tried just adding the Notifications connections, but am still being prompted and am unable to import the solution. 

To test, I imported the CoreComponents_1_71_5_managed from the repository and was able to import it, but I would like to be able to use the more recent version if possible. 

Thanks!

**Comment by JeneferM-MSFT** [comment] 2021-03-29 18:19
Hello. Can you tell me, are you a gov cloud? (GCC or GCC High)

**Comment by katmcelveen** [comment] 2021-03-29 19:03
Yes, we are GCC, gwinnett county

**Comment by JeneferM-MSFT** [comment] 2021-03-29 20:23
Gotcha. Then this is known and fixed in the upcoming April release. 

To track the fix being released please see #815 
To install a temporary workaround see #839

**Comment by JeneferM-MSFT** [comment] 2021-03-29 20:23
Duplicate of #815 

Thanks for using CoE!

**Closed by JeneferM-MSFT** 2021-03-29 20:23 UTC
Labels: coestarterkit
