### ISSUE TITLE
[BUG]: Cannot upgrade Audit Log module from 1.0.0.20 to 1.3.2

### ISSUE THREAD

**Issue by dchrist27** [microsoft/powerapps-tools#655] opened 2020-12-23 16:55 UTC
![image](https://user-images.githubusercontent.com/52799471/103018982-af200480-450b-11eb-8e13-c1b5a6979d10.png)

Clicking Next I see this screen:

![image](https://user-images.githubusercontent.com/52799471/103019076-d545a480-450b-11eb-9e44-7eb6dd826b61.png)

When I select Office 365 Management API then new connection I see the following popup:

![image](https://user-images.githubusercontent.com/52799471/103019205-0e7e1480-450c-11eb-875e-863a285f53e3.png)

Shouldn't the wizard find this connector that already exists?  (This is the connector that was setup following option 1 https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog)

![image](https://user-images.githubusercontent.com/52799471/103019375-5309b000-450c-11eb-9b74-4e0901affc5c.png)

This connector seems to be OK since the [Child] Admin | Sync Logs flow is running.

![image](https://user-images.githubusercontent.com/52799471/103019732-e642e580-450c-11eb-91a7-8ac5bcb2233a.png)

Thanks for your help.
Dave

**Comment by JeneferM-MSFT** [comment] 2020-12-23 17:33
Duplicate of #615

**Closed by JeneferM-MSFT** 2020-12-23 17:33 UTC
Labels: coestarterkit
