### ISSUE TITLE
[BUG]: CoE does not consider Unpublished Model-Driven Apps

### ISSUE THREAD

**Issue by tchinnin** [microsoft/powerapps-tools#776] opened 2021-02-17 15:01 UTC
**Describe the bug**
CoE Flow to retreive Model-Driven Apps, only gets Published Model-Driven Apps. If a MDA is created but never published (like a lot are on default environnement because of citizen dev. tests) CoE doesn't collect neither the App nor the Maker.

**Component (please tell us which flow or app you are experiencing issues with):**
- Core Solution
- Admin | Sync Template v3 (Model Driven Apps)

**To Reproduce**
1. On Power Apps Portal, Create a Model-Driven Apps, but **DONT PUBLISH IT** 
2. Open Admin | Sync Template v3 (Model Driven Apps) Flow
3. See all Model-Driven listed by "List Model-Driven Apps" action
4. See only "Published" App appears. (componentstate = 0)

**Expected behavior**
Would be nice to have Unpublished Model-driven Apps in CoE. On big companies (more than 100k users) a lot of citizen developpers try Power Apps on Default Environement, and create "Model-Driven" Apps without publishing it. These apps can't be used, makers are not collected in CoE. 
Building solutions over CoE I like to use only data collected by CoE. I'am creating a clean up Flow for Model-Driven on Default environement, but can't use CoE data because all apps are not collected.

**Additional context**
Unpublished Model-Driven Apps on appmodules table can be retrieve using the following REST Method:
`/api/data/v9.0/appmodules/Microsoft.Dynamics.CRM.RetrieveUnpublishedMultiple()?$select=appmoduleid,name,clienttype,createdon,modifiedon,componentstate,_createdby_value `

**Comment by JeneferM-MSFT** [comment] 2021-02-17 15:18
Hello. I'm afraid this is known and not something we can fix because of the way the data is gathered.
If you are able to create a flow which finds and collects these, we would be happy to investigate your solution and perhaps incorporate it into the CoE. But to our knowledge, we cannot easily find these. 

Duplicate of #312

**Comment by tchinnin** [comment] 2021-02-17 15:23
I have build a flow that retrieve these unpublished MDAs, but I had to go through the HTTP connector. 

![image](https://user-images.githubusercontent.com/46782173/108225407-3371bb00-713c-11eb-9ce4-376300206986.png)

**Comment by JeneferM-MSFT** [comment] 2021-02-17 15:28
Ah yes, I remember that being the back up plan now. Once you get it into a working state, if you'd like to share you are welcome to do so. And then we might be able to add it as natively integrated.
Note that if you should be able to add another flow which writes to your CoE tables, in other words you could write to the Apps table from this new flow you are creating, and then use the CoE tables for your reporting.

**Comment by JeneferM-MSFT** [comment] 2021-02-28 15:21
Closing out items without further action items

**Closed by JeneferM-MSFT** 2021-02-28 15:21 UTC
Labels: coestarterkit
