### ISSUE TITLE
[BUG]: Sync template v2 (powerapps users shared with)

### ISSUE THREAD

**Issue by brunoboucher** [microsoft/powerapps-tools#379] opened 2020-07-17 04:54 UTC
**Describe the bug**
Run solution flow : Admin | Sync Template v2 (Power Apps User Shared With)
Admin | Sync Template v2 (Power Apps User Shared With)
and got a fail to flow action : « Get_App_Role_Assignments_as_Admin »

**To Reproduce**
I'm import the script and execute

Error Message I got:
The request failed with error: 'The environment '<null>' could not be found in the tenant ''.'. The tracking Id is '8b01e7e6-9354-4f11-8384-65cc6fe92a20'.

**Comment by brunoboucher** [comment] 2020-07-17 04:55
I.m using the latest version of Coe core 1.53

**Comment by JeneferM-MSFT** [comment] 2020-07-17 12:33
Hi there. There is another issue, #369 , which tracks this same issue. Can you please hop over there and help with the repro?
It's a slightly different repro solve is a different flow but it sounds like the same bug. Please see if you can answer the latest questions there to help us debug.

Duplicate of #369

**Comment by brunoboucher** [comment] 2020-07-17 13:54
I'll go see the other issue. 
Regards.

**Comment by JeneferM-MSFT** [comment] 2020-07-21 19:38
oops didnt mean to reopen

**Closed by JeneferM-MSFT** 2020-07-21 19:38 UTC
Labels: coestarterkit
