### ISSUE TITLE
[BUG]: Admin | Sync Template v2 (Flows) runs never ending....

### ISSUE THREAD

**Issue by brunoboucher** [microsoft/powerapps-tools#545] opened 2020-10-28 18:50 UTC
**Describe the bug**
Admin | Sync Template v2 (Flows) runs never ending....some runs is 6d old...and it's still running
I put a screen shot where the flow "jam"

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Core
 - Version 1.70.3
 - Flow: Admin | Sync Template v2 (Flows) 

**To Reproduce**
1. Start the sync

**Expected behavior**
My flows data uptodate and the flows was ending

**Screenshots**
![image](https://user-images.githubusercontent.com/32851166/97482422-870d8e00-192c-11eb-9361-f0448ef5bb57.png)

And the action who seems to "block"
![image](https://user-images.githubusercontent.com/32851166/97482675-d489fb00-192c-11eb-914c-d7ddfbf78c64.png)

**Additional context**
I do a copy of the flow, and I got the same issue.

**Comment by JeneferM-MSFT** [comment] 2020-10-28 19:36
Hello. This is a known issue and fixed in 70_6. You will need to upgrade and then please ensure you see the following in the flow to ensure upgrade worked correctly
Duplicate of #497 

![image](https://user-images.githubusercontent.com/62659043/97487517-f5e9e780-192a-11eb-870c-533c8fe3a11e.png)

**Closed by JeneferM-MSFT** 2020-10-28 19:36 UTC
Labels: coestarterkit
