### ISSUE TITLE
[BUG]: Error during Core Components upgrade: 8004801E

### ISSUE THREAD

**Issue by mknightca** [microsoft/powerapps-tools#828] opened 2021-03-12 17:02 UTC
**Describe the bug**
We have CoE tool kit installed about a month ago. I was attempting today to import the new core components versions and perform an upgrade. Got an error message described below.

Error:
Import failed: Failed to update all the dependent flows. Failed workflow: {workflowname: Microsoft.Xrm.Sdk.AliasedValue, workflowid: Microsoft.Xrm.Sdk.AliasedValue, statecode: Microsoft.Xrm.Sdk.AliasedValue} with error message Flow client error returned with status code "BadRequest" and details "{"error":{"code":"InvalidOpenApiFlow","message":"Flow save failed with code 'InvalidPaginationPolicy' and message 'The pagination policy of workflow run action 'List_RPA_Flows' of type 'ApiConnection' at line '1' and column '11917' is not valid. The value specified for property 'minimumItemsCount' exceeds the maximum allowed. Actual: '100000'. Maximum: '5000'.'."}}".

**Component (please tell us which flow or app you are experiencing issues with):**
 - CenterofExcellenceCoreComponents_1_98_managed (1)
 - I got this from downloading the tool kit yesterday, its a zipped file within coestarterkit

**To Reproduce**
1. go to make.powerapps.com
2. Change environment to CoE env
3. Click Solutions
4. Import
5. Browse and upload zip file described above
6. Advanced Settings - use 'upgrade (recommended)
7. import
8. make sure all connections are setup
9. continue
10. get error message

**Expected behavior**
Currently have 1.71.7 installed, would expect to be on new version

**Comment by manuelap-msft** [comment] 2021-03-12 18:02
Hello.

This is covered by #725

All the flows have this pagination policy. It indicates that you are using an insufficient license.
Note that we do not support trial licenses for the toolkit any longer due to some product changes that upped the requirements for throttling purposes.

See here for the Flow limits and license profiles: https://docs.microsoft.com/en-us/power-automate/limits-and-config

And hence our requirements for licenses. What licenses do I need to run this solution?

Duplicate of #725

**Closed** 2021-03-12 18:02 UTC
Labels: coestarterkit

**Comment by mknightca** [comment] 2021-03-15 14:07
@manuelap-msft thank you but i'm not quite understanding where i'm going wrong. We aren't using any trial licenses at all. We are using M365 E5 licensing and 5 different dynamics licensing but none are trial. 

Is this suggesting I have to buy a separate power automate license in order to upgrade the product? What would be different if i tried to just reinstall the product? Why would that work and not an upgrade this is confusing.

**Comment by manuelap-msft** [comment] 2021-03-15 14:16
Hello,

your error message indicates that the maximum pagination setting allowed as per your license type is 5,000.

As per the Power Automate documentation above, this limit applies to the Low license profile
![image](https://user-images.githubusercontent.com/55705669/111166797-63c04400-8598-11eb-9826-6528666bc5e8.png)

See:
![image](https://user-images.githubusercontent.com/55705669/111166764-573beb80-8598-11eb-9bb5-b4cfd4420f5f.png)

A fresh install or upgrade would lead to the same error.

**Comment by mknightca** [comment] 2021-03-15 17:04
Hello @manuelap-msft , is it looking at the licenses of the person trying the import? or tenant wide settings? I've tried now adding "Power Automate Per User" paid service plan like the link suggests 'all others have 100,000 limit' but i'm getting the same error.  When we installed CoE we had a power apps plan 2 trial. It looks like it uses the original creators license and not the person trying to do the import does that sound correct? approx when did the trial thing change as we had no issues with the install on dec 7

**Comment by manuelap-msft** [comment] 2021-03-15 17:47
Hello,

it would be looking at the Flow Owner, which is typically the creator. You can change Flow Ownership using APIs
https://docs.microsoft.com/en-us/power-automate/web-api#update-a-cloud-flow

I'm not sure when this changed, they are part of the Power Automate service and limits and not something to do with the CoE Kit.

**Comment by mknightca** [comment] 2021-03-22 16:35
Hello, @manuelap-msft 

I have to report back that we resolved the issue and it didn't have anything to do with licensing. So I had the original installer do the upgrade and there were no issues. This is a user using the following licenses:

Common Data Service
Exchange Online Plan 1
Flow Free
Flow P2 Viral
Power BI (Free)
PowerApps Trial


My user account has the following and I could not do the upgrade without the error:

There's about 70 but I'm showing relevant

Common Data Service
Exchange Online (Plan 2)
Flow Free
Power BI Pro
Power Apps per user plan
Power Automate per user plan
Power Automate for 365
Power Apps Trial


So I have same licenses if not more and get the error everytime i try to upgrade anything. 

I have all the requirements here: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup other than i am not a global admin, i am only a Microsoft Power Platform service admin but this suggests its all the same.

I will reach out to my microsoft rep to discuss the options but i feel that i'm being restricted to do upgrades to CoE because i'm not the original creator or that I'm not a global admin.
