### ISSUE TITLE
[BUG]: Admin | Sync Template v2 (Apps) and Admin | Sync Template v2 (Flows) start twice and flow one fails

### ISSUE THREAD

**Issue by WouterF** [microsoft/powerapps-tools#543] opened 2020-10-26 12:24 UTC
**Describe the bug**
**First:**
The two flows:
- Admin | Sync Template v2 (Apps)
- Admin | Sync Template v2 (Flows)
Are triggered by Admin | Sync Template v2. This triggering flow updates 9 environments.
The two other flows are started 18 times each, so double.
![image](https://user-images.githubusercontent.com/5990852/97171120-2b58ce80-178d-11eb-98e6-332d0319297c.png)

**Second:**
The flow Admin | Sync Template v2 (**Flows**) "throws multiple errors: (I removed the guid's to not make them public)
- Connection Reference
![image](https://user-images.githubusercontent.com/5990852/97171885-745d5280-178e-11eb-9f80-a4363767fb11.png)
- Could not find flow:
![image](https://user-images.githubusercontent.com/5990852/97171664-1cbee700-178e-11eb-87ff-38c8878db88b.png)
- admin_FlowResource does not exist
![image](https://user-images.githubusercontent.com/5990852/97171799-51cb3980-178e-11eb-9184-4fdce55727de.png)

**Third:**
The flow Admin | Sync Template v2 (**Apps**) throws an error for SharePoint form apps:
![image](https://user-images.githubusercontent.com/5990852/97172283-1ed57580-178f-11eb-8d34-a32266ed7f6b.png)

**This happened after upgrading to v1.70.6 .**

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: Core
 - Version: v1.70.6
 - App or Flow: Admin | Sync Template v2, Admin | Sync Template v2 (Apps) and Admin | Sync Template v2 (Flows)

**To Reproduce**
1. Go to the Admin | Sync Template v2 run history. See that it updates every environment.
2. Go to the Sync Template v2 (Apps) and Admin | Sync Template v2 (Flows) run history and see that they start double.

**Expected behavior**
The Flow and App flows should only start for every environment. If you have 9 environments, they should start each 9 times, not 18.

I don't know why the others errors for Sync Template v2 (Apps) and Admin | Sync Template v2 (Flows) occur.

**Screenshots**

**Additional context**

**Comment by JeneferM-MSFT** [comment] 2020-10-28 13:14
1) Multiple runs - my assumption is that the main sync flow ran twice. This can happen on upgrade/install for people. Turning the flow on runs it, and then if you hit run manually that would be a second run. 

2) Will investigate

3) We have this local fixed in our tenant, please see if this resolves the issue for you?
[AppSyncFlowwithEmbeddedFix_20201028131318.zip](https://github.com/microsoft/powerapps-tools/files/5452046/AppSyncFlowwithEmbeddedFix_20201028131318.zip)

**Comment by JeneferM-MSFT** [comment] 2020-10-28 15:42
For item 2, can you please share which action is failing.

**Comment by WouterF** [comment] 2020-10-29 07:30
**1. The main sync flow only runs one time a day:**
![image](https://user-images.githubusercontent.com/5990852/97537788-a5709980-19bf-11eb-9c00-6d7fa6665185.png)
The others run twice. We don't installed them recently or didn't turn them on or off.
![image](https://user-images.githubusercontent.com/5990852/97537850-c20cd180-19bf-11eb-95c8-bdcd1f32aa0e.png)

**2. See below the actions that throw the errors. We haven't customized the CoE, just upgraded once to the last version...**

_Connection reference:_
![image](https://user-images.githubusercontent.com/5990852/97538259-655de680-19c0-11eb-90a7-38d272d6cd22.png)

_Could not find flow:_
![image](https://user-images.githubusercontent.com/5990852/97538129-2fb8fd80-19c0-11eb-96f3-64e26aa1245c.png)

_admin_FlowResource does not exist_
![image](https://user-images.githubusercontent.com/5990852/97538555-e4ebb580-19c0-11eb-9803-4c599bc33744.png)

**3. Thanks, I'll try**

**Comment by JeneferM-MSFT** [comment] 2020-10-30 15:04
I believe you are saying that you see 2 sync flows started for each envt, for each object type. And that may be more now if the main sync flow has run again. This would cause you to be accessing/deleting objects at the same time from different flows and hence be in a bad state. 

If so, this is likely the long running issue caused by recent changes to throttling. 
And if you tried to upgrade to 70_6 which fixed, then that did not work as it no longer does an overwrite. 

Can you please upgrade in the following manner? 
> Switch to classic (this could take some time) 
![image](https://user-images.githubusercontent.com/62659043/97719195-cc4ccf80-1a94-11eb-91e4-a798558a8039.png)


> Import
![image](https://user-images.githubusercontent.com/62659043/97720698-90b30500-1a96-11eb-93de-8b8a202455aa.png)


> Choose 70_6 [CenterofExcellenceCoreComponents_1_70_6_managed.zip](https://github.com/microsoft/powerapps-tools/files/5465857/CenterofExcellenceCoreComponents_1_70_6_managed.zip)
![image](https://user-images.githubusercontent.com/62659043/97720944-dd96db80-1a96-11eb-9bb1-fb4369d51125.png)


> Next & Next

> Chose Overwrite and Import
![image](https://user-images.githubusercontent.com/62659043/97721182-1fc01d00-1a97-11eb-8e77-3fea90e05cfe.png)

**Comment by WouterF** [comment] 2020-11-02 12:10
I've followed the steps you mentioned and I have overwritten the solution package using the classic import.
The "Admin | Sync Template v2 (Flows)" flow keeps being triggered twice. We have 9 environments, should it start 9 times. Now it is started 18 times.
The flow seems to work correctly for all environments except "Personal Productivity" - the default one.
![image](https://user-images.githubusercontent.com/5990852/97866289-f3610680-1d0b-11eb-8565-a8ba37e1f9a8.png)

This is the error:
`{
  "status": 404,
  "message": "admin_ConnectionReference With Id = [hided] Does Not Exist",
  "error": {
    "message": "admin_ConnectionReference With Id = [hided] Does Not Exist"
  },
  "source": "[hided].crm4.dynamics.com",
  "errors": [],
  "debugInfo": "clientRequestId: [hided]"
}`
![image](https://user-images.githubusercontent.com/5990852/97866599-826e1e80-1d0c-11eb-99ed-2341059e9618.png)

**Comment by JeneferM-MSFT** [comment] 2020-11-03 22:09
The (flows) sync flow is triggered when the CoE record for the environment it touched. 
If this isnt happening from the main sync flow being called twice, it could be due to one of these other flows running. 

Can you validate:

1) Were these flows running during that time? They do also touch those records. 

![image](https://user-images.githubusercontent.com/62659043/98045530-ddc00f80-1de5-11eb-94ff-e036475f88e4.png)

2) If so, are all 3 now finished? 
 
3) Were the other objects sync flows also run multiple times? (apps/PVAs/etc)

4) If you wait until tomorrows sync flow to run, do you see these happening only once?

**Comment by WouterF** [comment] 2020-11-04 10:34
Hi,
Thanks for the info. See below for answers to the questions:

1. None of these flows were running. Only the "Check Deleted" one ran on October 31. The other two are turned off.

2. Yes they are all finished

3. The "Admin | Sync Template v2 (RPA)" does **not** run double. The sync apps, flows, PVA run double.

4. I waited until this morning and as in point 3, only the PVA sync flows not run double.

**Comment by JeneferM-MSFT** [comment] 2020-11-04 13:59
Do you possibly have a saved version of the sync flow running somewhere else?
Ways to check
- turn off the main sync flow we are seeing here, and then see if the object flows (flow/PVA/etc) run tomorrow  
- open your PBI and look in your CoE envt for a duplicate. Something you did a save-on from the past most likely 
![image](https://user-images.githubusercontent.com/62659043/98120476-d854da80-1e62-11eb-9bc7-1b7412f01072.png)

**Comment by WouterF** [comment] 2020-11-05 07:57
I checked if I have duplicates. There seem to be no duplicates.
What is very strange, is that in the PPAC and CoE Dashboard, I don't see all flows in my environment.
For example the CLEANUP - Admin | Sync Template v2 (Orphaned Makers) & CLEANUP - Admin | Sync Template v2 (Power Apps User Shared With) are not showed at all in the PPAC but exist in the Core solution... It seems like there is a bug in the Power Platform or am I wrong? Maybe there is a sync flow running that I don't see because of the bug?
See screenshots below.
![image](https://user-images.githubusercontent.com/5990852/98212825-71a7ed80-1f44-11eb-84ad-4f2ec5db69e5.png)
![image](https://user-images.githubusercontent.com/5990852/98212856-7cfb1900-1f44-11eb-9750-c084421edcba.png)
![image](https://user-images.githubusercontent.com/5990852/98212948-a0be5f00-1f44-11eb-9d65-7cd54a78cb8e.png)

**Comment by JeneferM-MSFT** [comment] 2020-11-05 12:34
More mysteries! For the admin pages, I know sometimes I have to say "load more" even if the item I'm looking for should be showing from a sort POV. Otherwise let's put a pin in those two to see if the double run is whats causing all this drama for us.

Can you please try turning off the **_Admin | Sync Template v2_** we see in Core here and then see if you still get a single run of each object?

**Comment by eBentl** [comment] 2020-11-09 04:09
Hi @JeneferM-MSFT can you advise (at least roughly) what was done for issue#3 as the zip package provided doesn't allow connectors to be specified and errors out.

I have added a condition to check the app type prior to getting the apps sharing settings and bypass checking the Role Assignments if the app is of type SharepointFormApp and would just like to be sure that I'm not missing any extra required details.

**Comment by WouterF** [comment] 2020-11-09 07:44
@JeneferM-MSFT , In the PPAC I clicked on "load more" but it is still not showing all flows/apps in an environment. Anyways, this is not for here but I will log a support ticket for that...

I turned the "Admin | Sync Template v2" flow off on Thursday. The other flows haven't ran anymore after turning this main flow off. 
So this morning I turned it on again, ran the flow (it ran only 1 time) and again the other flows are running twice while the main flow only updates 11 environments and not 22...
![image](https://user-images.githubusercontent.com/5990852/98513110-a7601580-2267-11eb-980d-179117b42b6d.png)

**Comment by JeneferM-MSFT** [comment] 2020-11-09 14:25
Hello folks. The fix to issue 3 (SP Embedded Apps failure) looks like this. Sorry about the package, it appears that we cannot release individual flows to you anymore now that we use connection references. 

![image](https://user-images.githubusercontent.com/62659043/98552851-d10f4180-2253-11eb-9fdc-8fcd2b00592c.png)
Where the left side of that condition is : `items('Apply_to_each_App')?['properties']?['embeddedApp']?['type']`

**Comment by JeneferM-MSFT** [comment] 2020-11-09 15:36
On the double run issue, I'm afraid I'm out of ideas. We do not repro and have not heard this from anyone else. 
There are ways to track and monitor what edits occur in an entity in the CDS, I would recommend exploring that feature set. I am not familiar with it to walk you through it unfortunately.

**Comment by mpinuel** [comment] 2020-11-12 13:27
Hi **@JeneferM-MSFT,** 
I've the same error reported by **@WouterF**:
We've upgraded the CoE-Core Components version and since then, we have similar issues:
- "Admin | Sync Template v2" flow runs once and we have 15 environments.
- "Admin | Sync Template v2 (Apps)" and "Admin | Sync Template v2 (Flows)" are triggered twice per environment, so we have 30 instances of each
- Other flows as PVA or RPA run once per environment.
- Double instances are likely to cause data inconsistency errors to occur, such as those provided above that also occur to us, for example the "admin_ConnectionReference With Id = XXXX Does Not Exist" in the 'Delete_a_record' action.
Please, if you need more information about or you find a possible solution we can test, please tell us.
Thanks!

**Comment by JeneferM-MSFT** [comment] 2020-11-12 14:33
Can you please turn off your main sync flow (Admin | Sync Template v2) and see if these two still run?
Admin | Sync Template v2 (Apps) and Admin | Sync Template v2 (Flows)

**Comment by JeneferM-MSFT** [comment] 2020-11-12 15:18
A couple more follow ups. Putting them all here for ease of reading

1) **See if it repros outside of the context of our sync flows**
   A. Turn off the main sync flow and ensure no (flow) sync flows are running    
   B. Make a flow that listens to the flows table and which does something simple like a compose
![image](https://user-images.githubusercontent.com/62659043/98956920-75dc8980-24b5-11eb-85c4-5002f8597224.png)
    You can use this one if you'd like: [Checknumberoftriggers_20201112150629.zip](https://github.com/microsoft/powerapps-tools/files/5531431/Checknumberoftriggers_20201112150629.zip)
    
    C.  Manually edit an environment 
     There are many ways to do this, but here is one. Edit something that you can change back after we are done
![image](https://user-images.githubusercontent.com/62659043/98957499-1b8ff880-24b6-11eb-96e6-06c7792f48bc.png)

     D. See if our test from from B, and the (flows) sync flow ran once or twice. 

2) **Turn off sync flow and see if it runs**
    Can you please turn off your main sync flow (Admin | Sync Template v2) and see if these two still run?
    Admin | Sync Template v2 (Apps) and Admin | Sync Template v2 (Flows)
    (Wouter checked this for his repro already)

3) **See number of environtments in the loop**
    Can you please check in the main Sync Template flow the number of environments that were looped? 
    (Wouter checked this for his repro already)
    ![image](https://user-images.githubusercontent.com/62659043/98956007-66a90c00-24b4-11eb-90bf-54f3e2a4c08a.png)

**Comment by mpinuel** [comment] 2020-11-13 13:16
Hello @JeneferM-MSFT !

I've already performed the tests you requested:

**1.	See if it repros outside of the context of our sync flows**
A. Turn off the main sync flow and ensure no (flow) sync flows are running:
![image](https://user-images.githubusercontent.com/32450895/99074283-c3411f80-25b7-11eb-807c-a2d696a34790.png)

B. Make a flow that listens to the flows table and which does something simple like a compose:
![image](https://user-images.githubusercontent.com/32450895/99074319-d522c280-25b7-11eb-9957-3c63e45c8f2c.png)

C. Manually edit an environment:
![image](https://user-images.githubusercontent.com/32450895/99075993-b1ad4700-25ba-11eb-935e-3119c071edcb.png)

D. See if our test from from B, and the (flows) sync flow ran once or twice:
- Sync flow ran twice when I edited the environment record:
![image](https://user-images.githubusercontent.com/32450895/99074674-7dd12200-25b8-11eb-8575-6cfbdb964d2f.png)
- Test flow from B has not been launched by modifying the environment record, but it has been launched before:
![image](https://user-images.githubusercontent.com/32450895/99074884-d7395100-25b8-11eb-8b1a-1db95b1c56dd.png)

**2.	Turn off sync flow and see if it runs**
Can you please turn off your main sync flow (Admin | Sync Template v2) and see if these two still run?
Admin | Sync Template v2 (Apps) and Admin | Sync Template v2 (Flows)
- Yesterday (Nov 12) I turned off the main sync Flow, so this morning (Nov 13) they have not launched (last executions are from yesterday):
![image](https://user-images.githubusercontent.com/32450895/99075173-5169d580-25b9-11eb-8e15-dcd07f78da0f.png)
- Admin Sync Template v2 (Apps) and (Flows) are active, but have not been launched since yesterday:
![image](https://user-images.githubusercontent.com/32450895/99075280-80804700-25b9-11eb-9fce-0214f03d7eb5.png)

**3.	See number of environments in the loop**
Can you please check in the main Sync Template flow the number of environments that were looped?
- Yes, we have 15 environments:
![image](https://user-images.githubusercontent.com/32450895/99075353-9f7ed900-25b9-11eb-9655-b860acc94f74.png)

If you need any other test, do not hesitate to tell us.

Thanks!

**Comment by JeneferM-MSFT** [comment] 2020-11-13 14:23
Thanks for posting these findings. 

Oh and shoot I totally messed up the test flow in B. Can you please change it to be the Environment entity? It should match the below image. 

Even without test B, I now feel confident that this is either something with the trigger in these flows, or something configured in the entity. Since most people dont repro, I suspect its the latter, but can you please:

1) Change the trigger in the test flow (your step B) to be as shown below. You'll also need to change the field being called in the compose.
2) Share what your trigger looks like in the (flow) sync flow? It should look like this:
![image](https://user-images.githubusercontent.com/62659043/99081838-3dea4a80-2578-11eb-830c-7986eb2cffd3.png)

**Comment by WouterF** [comment] 2020-11-16 07:56
1. I tested with the new flow and updating an environment record:
![image](https://user-images.githubusercontent.com/5990852/99225829-f9b1b100-27e8-11eb-905d-faca86a05a50.png)
I updated one of the environment records (the region from "europe" to "test", I cannot change other fields as I cannot open it in Excel, it's blocked in our organization)
**Flow runnedonce:**
![image](https://user-images.githubusercontent.com/5990852/99225942-31205d80-27e9-11eb-9fc2-22de0d1d2c0c.png)

2. Share what your trigger looks like in the (flow) sync flow:
![image](https://user-images.githubusercontent.com/5990852/99226013-5319e000-27e9-11eb-8b46-e9fa803ca317.png)

**When you click "peek code" there are differences between the trigger of the sync flow (flow) & the test flow we created:**
`{
    "inputs": {
        "host": {
            "connectionName": "shared_commondataservice",
            "operationId": "SubscribeOnUpdatedItems",
            "apiId": "/providers/Microsoft.PowerApps/apis/shared_commondataservice"
        },
        "parameters": {
            "dataset": "default.cds",
            "table": "admin_environments",
            "scope": "Organization"
        },
        "authentication": "@parameters('$authentication')"
    }
}`

`{
    "inputs": {
        "host": {
            "connection": {
                "name": "@parameters('$connections')['shared_commondataservice_1']['connectionId']"
            }
        },
        "body": {
            "NotificationUrl": "@{listCallbackUrl()}"
        },
        "path": "/datasets/@{encodeURIComponent(encodeURIComponent('default.cds'))}/tables/@{encodeURIComponent(encodeURIComponent('admin_environments'))}/onupdateditemswebhook",
        "queries": {
            "scope": "Organization"
        },
        "authentication": "@parameters('$authentication')"
    },
    "metadata": {
        "flowSystemMetadata": {
            "swaggerOperationId": "SubscribeOnUpdatedItems"
        }
    }
}`

**Comment by mpinuel** [comment] 2020-11-16 09:26
Hi @JeneferM-MSFT ,

On our side we have also carried out the test that you indicate:

- I changed the entity name in the test Flow to: Environments:
![image](https://user-images.githubusercontent.com/32450895/99234833-5a46eb00-27f5-11eb-995d-ef9e4d8f8ec1.png)

- I have modified again a record in the environment entity, and the test flow ran only once (same as @WouterF  said):
![image](https://user-images.githubusercontent.com/32450895/99235095-b3168380-27f5-11eb-9147-602f720bbfab.png)

- But Admin | Sync Template v2 (Flows) and Admin | Sync Template v2 (Apps) ran also twice with this change:
![image](https://user-images.githubusercontent.com/32450895/99235258-eb1dc680-27f5-11eb-9498-7a2a6ea48edb.png)

Thanks!

**Comment by mpinuel** [comment] 2020-11-16 12:22
Reviewing the triggers "peek code", as @WouterF said before, I have seen that there are some differences between the triggers of the CoE Sync Flows, although I don't know if they can have anything to do with the problem we have:
- **Admin | Sync Template v2 (Apps)** -> ran twice and **Admin | Sync Template v2 (PVA)** -> ran once, have exactly the same code on the trigger:
{
    "inputs": {
        "host": {
            "connection": {
                "name": "@parameters('$connections')['**shared_commondataservice**']['connectionId']"
            }
        },
        "body": {
            "NotificationUrl": "@{listCallbackUrl()}"
        },
        "path": "/datasets/@{encodeURIComponent(encodeURIComponent('default.cds'))}/tables/@{encodeURIComponent(encodeURIComponent('admin_environments'))}/onupdateditemswebhook",
        "queries": {
            "scope": "Organization"
        },
        "authentication": "@parameters('$authentication')"
    },
    "metadata": {
        "flowSystemMetadata": {
            "swaggerOperationId": "SubscribeOnUpdatedItems"
        }
    }
}
- **Admin | Sync Template v2 (Flows)** -> ran twice has a little difference in the trigger, because the shared common data service connection ends with _1:
{
    "inputs": {
        "host": {
            "connection": {
                "name": "@parameters('$connections')['**shared_commondataservice_1'**]['connectionId']"
            }
        },
        "body": {
            "NotificationUrl": "@{listCallbackUrl()}"
        },
        "path": "/datasets/@{encodeURIComponent(encodeURIComponent('default.cds'))}/tables/@{encodeURIComponent(encodeURIComponent('admin_environments'))}/onupdateditemswebhook",
        "queries": {
            "scope": "Organization"
        },
        "authentication": "@parameters('$authentication')"
    },
    "metadata": {
        "flowSystemMetadata": {
            "swaggerOperationId": "SubscribeOnUpdatedItems"
        }
    }
}

Thanks!

**Comment by JeneferM-MSFT** [comment] 2020-11-16 15:39
Good idea to look at peek! We match though for the flow triggers in the (flow) sync flow between your envt's and mine, so its correct as we dont repro. 

Would it be possible for you to create a clean environment, install the Core solution and see if you repro in a new environment?

**Comment by WouterF** [comment] 2020-11-16 16:04
@JeneferM-MSFT , sorry but this is not possible for me to install it again. I work for a client and I have unfortunately no time to debug the CoE...
For your information, MS support is investigating if something is going wrong with the triggers and CDS:
![image](https://user-images.githubusercontent.com/5990852/99277043-a31a9600-282d-11eb-90bc-c2873eeb7206.png)

**Comment by JeneferM-MSFT** [comment] 2020-11-16 17:01
Wonderful. Please let me know what they find so that I can point anyone else in the future who sees this issue.

**Comment by mpinuel** [comment] 2020-11-18 11:26
Hello,

By our side, we have managed to solve the issue with the duplicated instances of flows. We followed these steps:

1. First, we try to uninstall the upgraded version of **"Center of Excellence – Core Components"** solution in our environment, but  we had some solution dependencies errors because some hidden Power Apps of the first test CoE installation used some entities.

2. We reviewed the environment Power Apps from PowerShell and removed those that gave error and were not being used:
`Get-AdminPowerApp -EnvironmentName [GUID]`
`Remove-AdminPowerApp -AppName [GUID] -EnvironmentName [GUID]`

3. Once removed, we ran again the CoE Core Components solution uninstall, this time in a satisfactory way, but before reinstalling the solution, we checked the environment Flows through PowerShell, since we saw that there was a duplicate Flow of previous installations that had not been removed: **we had before uninstalling the solution two "Admin | Sync Template v2 (Flows)" flows in the same environment!**
`Get-AdminFlow -EnvironmentName [GUID]`
Then remove the duplicated Flow from PS:
`Remove-AdminFlow -EnvironmentName [GUID] -FlowName [GUID]`

4. Finally, once we have a clean environment we installed the last version of **"Center of Excellence – Core Components" solution (v 1.71.1)** and now we no longer have duplicated instances of the flows, just one per environment!

Thanks!

Regards,

**Comment by WouterF** [comment] 2020-11-18 12:47
@JeneferM-MSFT , I checked using PowerShell, but for me there are no two "Admin | Sync Template v2 (Flows)" flows.
However, with the investigation of @mpinuel , it is clear that there are unwanted duplicate flows & apps in environments that are not visible in the UI.
Can you contact the product team and ask them to investigate because it seems to me that this is a bug.

**Comment by JeneferM-MSFT** [comment] 2020-11-18 18:07
Good to hear you are fixed up @mpinuel.
@WouterF, I will pass along as well, but given that you have support on the line, I think that will be the most likely solution since they will have access to your tenant. 

I will close this issue now and hope that product team can address.

**Closed by JeneferM-MSFT** 2020-11-18 18:07 UTC
Labels: coestarterkit
