### ISSUE TITLE
CLEANUP - Admin | Sync Template v3 (Check Deleted) fails - A binary operator with incompatible types was detected. Found operand types 'Edm.Guid' and 'Edm.String' for operator kind 'Equal'

### ISSUE THREAD

**Issue by RamitK** [microsoft/powerapps-tools#862] opened 2021-03-22 12:14 UTC
The flow still fails with multiple errors. First it fails for "Newly Deleted Canvas App" step for Get Apps as Admin connector. I verified that the environment was deleted:
![image](https://user-images.githubusercontent.com/39703138/111987619-71943d00-8b35-11eb-901e-68faf687c8af.png)
and it is possible it was deleted when the flow was in the middle (as it took more than 5 days to run). My question is, shouldn't there be error handling for this flow in case the environment does not exist anymore?

Also it failed for PVAs:

![image](https://user-images.githubusercontent.com/39703138/111987854-ba4bf600-8b35-11eb-9172-316b96f0c089.png)

The error being (status: 400): {"code":"0x0","message":"A binary operator with incompatible types was detected. Found operand types 'Edm.Guid' and 'Edm.String' for operator kind 'Equal'."}

Not sure why it is also failing. Could you please advise?

Solution version for Core Components: 1.98

_Originally posted by @RamitK in https://github.com/microsoft/powerapps-tools/issues/813#issuecomment-804015619_

**Comment by JeneferM-MSFT** [comment] 2021-03-22 13:05
To answer this first question: **_Shouldn't there be error handling for this flow in case the environment does not exist anymore_**

Your case is when the environment was deleted since the flow started. 
We considered adding catches here and decided not to as this would mask other failures. If this is the cause it will pass on rerun. 

So for that one, we will consider it WF. This bug will track the second issue of the PVA failure as a result.

**Comment by JeneferM-MSFT** [comment] 2021-03-22 13:41
For the issue of the PVA, we were incorrectly filtering by looking for '' instead of null in 2 spots. Local fixed now. Thanks for using CoE and helping make it great!

**Comment by RamitK** [comment] 2021-03-23 03:24
@JeneferM-MSFT Thanks. This makes sense. We will try the local fix for PVA and see if it works.

**Comment by manuelap-msft** [comment] 2021-04-08 11:55
Fixed with the current release, shipped today. Thank you for using the CoE!

**Closed by manuelap-msft** 2021-04-08 11:55 UTC
Labels: coestarterkit, localfixed
