### ISSUE TITLE
[BUG]: Pagination issue at  "Admin | Sync Template v2 (Custom Connectors)" flow template

### ISSUE THREAD

**Issue by Michal-Ziemba** [microsoft/powerapps-tools#473] opened 2020-09-17 14:59 UTC
**Describe the bug**
When trying to [Activate the Sync Template flow](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#activate-the-sync-template-flows) "Admin | Sync Template v2 (Custom Connectors)" and save it, I got en error:
`The pagination policy of workflow run action 'Find_connector_record' of type 'ApiConnection' at line '1' and column '6222' is not valid. The value specified for property 'minimumItemsCount' exceeds the maximum allowed. Actual: '10000'. Maximum: '5000'.`

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - Core
 - Version - 1.60
 - Flow - Admin | Sync Template v2 (Custom Connectors)

**To Reproduce**

1. Go to the make.powerapps.com, 
2. In the left navigation, select Solutions, and then select Center of Excellence - Core Components.
3. Select the flow "Admin | Sync Template v2 (Custom Connectors)", to go to the flow details page.
4. Select Save As.
5. After all connectors are OK, click Continue
6. You get en error.

**Comment by Michal-Ziemba** [comment] 2020-09-17 15:11
I cannot export and import the Flow as a workaround. I got this error during the import of the ZIP file:
`The request failed with error: '{"error":{"code":"PackageFlowMissingConnectionMap","message":"Flow resource '27f36964-b573-4497-93ae-6bd5cee3756f' missing mapping for connections 'shared_commondataservice_1,shared_commondataservice,shared_office365users,shared_powerappsforadmins,shared_commondataservice_4'."}}'. The tracking Id is '26603cdb-19c3-480b-906b-6af41f7c4d45'.`

**Comment by JeneferM-MSFT** [comment] 2020-09-17 15:18
Duplicate of #428 
Hello. This is a known issue, and we are releasing a fix in the next few days. 
Thanks for using CoE!

**Closed by JeneferM-MSFT** 2020-09-17 15:18 UTC
Labels: coestarterkit
