### ISSUE TITLE
[Issue]: Unable to update from 1.45 to 2.0.10

### ISSUE THREAD

**Issue by Chaitra1006** [microsoft/powerapps-tools#976] opened 2021-04-29 06:37 UTC
**Describe the bug**
Currently I have only COE Starter Kit version 1.45 been setup in my tenant which has most of the Power Platform data when viewed in COE Dashboard. 
When I try to import the latest COE Core component version 2.0.10 on top of the current setup encounter "Solution "Center of Excellence - Core Components" failed to import: ImportAsHolding Exception during StageAndUpgrade" error

**Component **
 - Solution : Core
 - Version  : 1.45

**To Reproduce**
1. Go to https://make.powerapps.com 
2. Select COE installed environment
3. Click Solutions
4. Click Import and select latest CenterofExcellenceCoreComponents_2_0_10_managed.zip
5. Click Next and Import 

**Expected behavior**
To successfully update to latest COE Starter Kit version 

**Screenshots**
![image](https://user-images.githubusercontent.com/38909384/116509373-c9feed00-a8e0-11eb-8704-8eb283ab2344.png)

![image](https://user-images.githubusercontent.com/38909384/116510086-fb2bed00-a8e1-11eb-89f9-c620c1964805.png)

![image](https://user-images.githubusercontent.com/38909384/116510415-7e4d4300-a8e2-11eb-9d0f-7fa2bbf05a5f.png)

![image](https://user-images.githubusercontent.com/38909384/116509272-a3d94d00-a8e0-11eb-8b02-5bde4f8ae328.png)

**Additional context**
Please suggest if the current Core component (managed solution) of 1.45 version must be uninstalled (would delete data in Dataverse?) and then the new version of 2.0.10 must be installed? 

I did try to setup the latest Core component 2.0.10 in a new environment in the same tenant, but it does not show all the data as the older version shows. Did set the FullInventory Environment Variable to Yes as mentioned https://docs.microsoft.com/en-us/power-platform/guidance/coe/limitations#incomplete-inventory, but no impact. 
Observe that many instances Admin | Sync Template v3 Apps, Connectors, Custom Connectors, Flows are either still in running or failed.

My older Core component (managed solution) of 1.45 version show around 11,000+ flows and 6000+ apps whereas my new Core component (managed solution) of 2.0.10 version installed in new environment shows only 2500+ flows and 800+ apps.

Please suggest how to update to latest Core component of 2.0.10 version and get all the tenant power platform data in one environment of the tenant

**Comment by JeneferM-MSFT** [comment] 2021-04-29 13:04
Hello this is a duplicate of #515 . We changed an attribute type and so you'll need to upgrade to an intermediate solution which first removed the attribute, and then upgrade to latest. 
You can find the intermediate solution in (CenterofExcellenceCoreComponents_1_62_managed.zip) at the bottom of #515

**Closed by JeneferM-MSFT** 2021-04-29 13:04 UTC
Labels: coestarterkit

**Comment by Chaitra1006** [comment] 2021-04-29 15:49
Thanks @JeneferM-MSFT ! It did work to update to new 2.0.10 version.

But why is the new COE setup in new environment not showing the data as the old COE setup belonging to same Tenant? 
The older Core component (managed solution) of 1.45 version show around 11,000+ flows and 6000+ apps in Power BI Dashboard, whereas new Core component (managed solution) of 2.0.10 version installed in new environment shows only 2500+ flows and 800+ apps.

**Comment by JeneferM-MSFT** [comment] 2021-04-29 15:56
Hello the old versions of the toolkit (back to 1.45) used an old and now deprecated connector for accessing the inventory and so it had started to become unreliable. We converted to the new connector late last year and so if there are differences I would tend to believe your new data is correct. 

My suggestion is to wait until all the flows in the new version of the toolkit runs all the way through. Then spot check some environments. For example the default envt from the products UX to the toolkit. If you see discrepencies there please post a new issue.

**Comment by Chaitra1006** [comment] 2021-04-29 16:28
Yes, I do see discrepancies. The new COE version's workflows either fail or continue to run for more than a week, thereby making the flow performance slow.
Please advise if have to still got wait or raise another issue.
![image](https://user-images.githubusercontent.com/38909384/116584729-46bbb680-a935-11eb-9c40-33f28979f92d.png)

![image](https://user-images.githubusercontent.com/38909384/116585265-d3ff0b00-a935-11eb-893d-ae95951cac87.png)

**Comment by JeneferM-MSFT** [comment] 2021-04-29 16:44
When you installed the updates, did you follow the instructions shown here: [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates)
If you had unmanaged layers you will not get the updated versions of the flows

Can you also please let me know, what is the value of this environment variable? You will want this to be no or it will update every flow and every app every time. 
![image](https://user-images.githubusercontent.com/62659043/116587552-ce72d800-a8d7-11eb-812c-501b83988efd.png)

**Comment by Chaitra1006** [comment] 2021-04-29 17:29
Yes, followed the mentioned instructions to install 1.98 and later updated to 2.0.10 and set the FullInventory Environment Variable to Yes as mentioned https://docs.microsoft.com/en-us/power-platform/guidance/coe/limitations#incomplete-inventory after update to 2.0.10.
Did not have any unmanaged layers before the update.

**Comment by JeneferM-MSFT** [comment] 2021-04-29 17:40
OK then you will just need to wait for the flows to complete. With a tenant your size this could take a week or more unfortunately due to throttling limits. Couple of suggestions:

1) Please set the fullinventory variable back to no for future runs (set the current value)
1) Turn off Admin Sync Template V3 so that it doesnt trigger a second run tomorrow while it finishes the full inventory
1) Work with your Power Platform contact to discuss getting onto the **_Bring your Own Datalake_** preview for large tenants.

**Comment by Chaitra1006** [comment] 2021-04-29 18:06
Sure, will work on your suggestions and will respond with the outcome.

**Comment by Chaitra1006** [comment] 2021-04-30 12:18
Observe today that the flow numbers are incrementing but not the apps. So have created a new issue https://github.com/microsoft/powerapps-tools/issues/986 with the details. Please assist.
