### ISSUE TITLE
[BUG]: Users get double approval requests

### ISSUE THREAD

**Issue by WouterF** [microsoft/powerapps-tools#763] opened 2021-02-08 11:35 UTC
**Describe the bug**
Our users get double approval requests to delete flows/apps.
You can see in the screenshot that last week one of our users rejected an approval and now they again get one.
I also received a message from someone else that **approved** deletion of a flow last week and today he got again a new request.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: Governance
 - Version: Newest

**Expected behavior**
Users shouldn't get double approval requests for the same flow/app when they have already rejected or approved deletion/archival.
Old records from the "Archive Approval" should be deleted automatically.

**Screenshots**
![image](https://user-images.githubusercontent.com/5990852/107214326-0f123200-6a0a-11eb-9f81-d03bfb3d54ec.png)

**Additional context**

**Comment by JeneferM-MSFT** [comment] 2021-02-08 14:18
Regarding this question: Is it normal that in this flow the filter condition is admin_approvalresponse eq null ?
The answer is yes, that flow is trying to match our approvals with approval responses, so we only look at the approvals with no response yet. 
Looking at other flows to find cause here.

**Comment by JeneferM-MSFT** [comment] 2021-02-08 14:21
Regarding this comment: Old records from the "Archive Approval" should be deleted automatically.
We do delete these here, although I acknowledge now by looking at it that the scope's title does not make that clear. 
![image](https://user-images.githubusercontent.com/62659043/107232021-cc366700-69d5-11eb-9949-2bea12f9566d.png)

**Comment by WouterF** [comment] 2021-02-08 14:22
@JeneferM-MSFT, thanks for the quick answer.
Please let me know when you have find the cause so that I can fix it here.
I think the issue is in the "Admin | Archive and Clean Up v2 (Start Approval for Flows)" flow, because it re-sends approval requests for flows that have already been approved/rejected for deletion/archival.

**Comment by JeneferM-MSFT** [comment] 2021-02-08 14:24
I found the cause, somehow we lost our clause here. Note that this is from the apps one, I presume the same bug occurred to the flows one. Let me remember what goes there and let you know.
![image](https://user-images.githubusercontent.com/62659043/107232450-449d2800-69d6-11eb-95e4-8608ed024507.png)

**Comment by WouterF** [comment] 2021-02-08 14:33
@JeneferM-MSFT, thanks for the investigation.
Until now our company does not use the flow for the power apps yet. That flow is turned off.
We have the issue with the flows one.

**Comment by JeneferM-MSFT** [comment] 2021-02-08 14:43
Yes the same issue is in the flow. It appears there is a product bug and its not liking me to refer to items in that for-each. I am investigating.

**Comment by JeneferM-MSFT** [comment] 2021-02-08 14:57
Alright I opened the flows one and the issue is not there. Do you see these correctly in the 
![image](https://user-images.githubusercontent.com/62659043/107236709-d0b14e80-69da-11eb-8742-a201338f640d.png)

**Comment by WouterF** [comment] 2021-02-08 15:04
@JeneferM-MSFT , yes I see the same as you. But this flow re-sends the approval request for a flow to be archived when the approve/reject of a previous one already happened.
![image](https://user-images.githubusercontent.com/5990852/107237652-3f1bfe00-6a27-11eb-83c3-345049a60c08.png)

**Comment by JeneferM-MSFT** [comment] 2021-02-08 16:06
I'm afraid I dont repro this. 

1) Do you still have the other flow (not v2) running? 
2) Do you have a run repro showing it going down the wrong path that we can explore?

**Comment by WouterF** [comment] 2021-02-08 19:03
@JeneferM-MSFT, yes all the flows in the core components solution are running. The V3's.
I will monitor it because it's very difficult to reproduce...
What is sure is that business users received a archival request for their flow one week ago and approved deletion. Today they got the same email, so something is going wrong. 
I don't find the cause. But I saw some strange things in the Power Platform the last months that could be related:

1. One of the flows in the core components of the CoE fails. The "list flows" connector returns flows that cannot be removed, these are some kind of zombie flows that are returned but do not exist. I have a ticket for that open since October 2020 and the product team is still busy with it.
2. As a Power Platform administrator, I have flows without owner in the default environment that are impossible to delete. Again some kind of zombie flows.
3. There was an issue with the environment id, sometimes in the CoE, for the default environment there is "Default-" in front of the id, sometimes not. Maybe there are somewhere still old records that cause issues...

**Comment by JeneferM-MSFT** [comment] 2021-02-08 19:30
Sorry, for question 1, what I meant is that this new update to the governance components created new flows (so that we could switch to the modern CDS Native connector) with v2 in the title. 
This should have deleted the old flows and added new, leaving you with these 4 (v2) flows for the archival solution
![image](https://user-images.githubusercontent.com/62659043/107271143-a96d7800-6a00-11eb-9150-a6015d817663.png)

However is something went wrong in install you might still have these sitting around and running, in which case you would get the new approvals created by them. 
![image](https://user-images.githubusercontent.com/62659043/107271314-e6d20580-6a00-11eb-8e72-dbd4775d15a5.png)

**Comment by WouterF** [comment] 2021-02-08 20:19
@JeneferM-MSFT , thanks for clarifying. I confirm that I have the new v2 flows for the governance solution.
The issue is not with copies of flows, but the V2 ignores the approval responses from 1 week ago.
Let me explain it in a different way below. Please let me know if it is clear.
![image](https://user-images.githubusercontent.com/5990852/107276437-4a851e80-6a53-11eb-9131-4ab6323d8669.png)

**Comment by JeneferM-MSFT** [comment] 2021-02-08 20:36
Glad you have a repro run, lets try to find the problem. 
Can you please find a flow you expected to be approved and one for rejected that is returned in this step? Note I usually use this [json viewer](http://jsonviewer.stack.hu/) to determine this
![image](https://user-images.githubusercontent.com/62659043/107277572-7380c180-6a09-11eb-8164-066aafe6f0b0.png)

Once you know which # it will be in the for-each, step into the for each to see how it proceeds, these filters are where we look for it. 
![image](https://user-images.githubusercontent.com/62659043/107277953-028dd980-6a0a-11eb-8432-b95174c3dc5d.png)
![image](https://user-images.githubusercontent.com/62659043/107278184-42ed5780-6a0a-11eb-8ff6-e49b0eb728be.png)

**Comment by WouterF** [comment] 2021-02-09 07:12
@JeneferM-MSFT, I tried what you said and now it looks like the filtering works. I moved the archival request into a "debug" condition to turn it off and tested the flow.
Yesterday I cleaned up the "Archive Approval" and "Flows" table. I guess that maybe due to the recent product change of MS that sometimes puts "Default-" in front of the environment and sometimes not is the cause. Maybe this caused duplicates in (one of) these two tables and lead to the filter that was not working.
Next week the flows will run again, I'm curious...

**Comment by JeneferM-MSFT** [comment] 2021-02-09 14:46
Wonderful. I'll stay tuned to see if this still repros for you next week. The fix to the bug you helped me find in the app version will ship today.

Do know that there is a debug switch you can use so that these mails come to admin instead of your end users while you debug. See the [environment variable](https://docs.microsoft.com/power-platform/guidance/coe/setup-governance-components#update-environment-variables)  **_ProductionEnvironment_**:

_Determines if the environment is Production or Dev/Test. True (the default) will mean that the approvals are sent to app/flow owners. False will send those approvals to the admin email._

**Comment by JeneferM-MSFT** [comment] 2021-02-15 17:58
Hello, checking in to see if this was resolved for you.

**Comment by WouterF** [comment] 2021-02-16 07:23
Hi @JeneferM-MSFT, thanks for asking. This week, the users did not receive anymore the requests they approved/declined last week. I guess that removing old values from the "Flow" or "Archive Approval" tables did the trick.
Thanks for your help. Will the fix for the Power Apps archival flow be shipped in the next CoE version?

**Comment by JeneferM-MSFT** [comment] 2021-02-16 15:21
Yes, we have already shipped the fix for the apps side. Thanks for using CoE and helping make it great!

**Closed by JeneferM-MSFT** 2021-02-16 15:21 UTC
Labels: coestarterkit
