### ISSUE TITLE
[BUG]: issue title

### ISSUE THREAD

**Issue by AngK72** [microsoft/powerapps-tools#759] opened 2021-02-06 14:11 UTC
**Describe the bug**
Unable to update Core Components of Centre of Excellence, Error 80041A06.  

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: Centre of Excellence - Core Components
 - Version 1.89
 - Managed Solution

**To Reproduce**
1. Click on "Import Solution"
2. Choose CenterofExcellenceCoreComponents_1_89_managed.zip
3. Select Upgrade (leave "Enable Plugin steps and flows included in the solution" checked)
4. Click "Import".

**Expected behavior**
Expected that the core components for the Centre of Excellence would update.

**Screenshots**
![Solution error message](https://user-images.githubusercontent.com/27891691/107120339-b8162c80-6852-11eb-85fd-616f64ae2e22.jpg)

**Additional context**
Exception message:  Attribute admin_rpamodifiedon is a String, but a DateTime type was specified.

**Comment by JeneferM-MSFT** [comment] 2021-02-06 17:48
Hello, you will need to upgrade to the interim solution (1.62) shown in #515 
And then try again to upgrade to 1.85. 

Thanks for using CoE!
Duplicate of #515

**Closed by JeneferM-MSFT** 2021-02-06 17:48 UTC
Labels: coestarterkit
