### ISSUE TITLE
Attribute admin_rpamodifiedon is a String, but a DateTime type was specified

### ISSUE THREAD

**Issue by devendrasv** [microsoft/powerapps-tools#509] opened 2020-10-08 05:24 UTC
Hi,

While importing the latest version (CenterofExcellenceCoreComponents_1_70_2_managed) of CoE core components, I am getting error as Attribute admin_rpamodifiedon is a String, but a DateTime type was specified. My current version of core components installed is 1.39 which is a managed solution. 

Could you help me to resolve the issue? 

Thanks.
Devendra

**Comment by JeneferM-MSFT** [comment] 2020-10-12 12:42
Hello. Can you please use the interim solution provided in #491 ? 
You will install that version, which will remove the field. And then install 70_2.

Thanks for using CoE
Duplicate of #491

**Closed by JeneferM-MSFT** 2020-10-12 12:42 UTC
Labels: coestarterkit

**Comment by macvi** [comment] 2020-10-12 15:28
Hi @JeneferM-MSFT! 
I am experiencing the same issue. My current version is 1.60, I tried installing 1.70 and 1.70.2 with same error message.
 Unfortunately I cannot install the version from #491 since it is an earleir version from the one I have.
 Many thanks for your help !
 Victor

**Comment by JeneferM-MSFT** [comment] 2020-10-12 16:23
Victor would you mind creating a separate github issue for that one? I'll create a fix for you and that version there.

**Comment by macvi** [comment] 2020-10-12 21:01
Hi Jennifer !
Just did it. Issue #515
Many thanks again
