### ISSUE TITLE
[BUG]: New 16/11/2020 PowerBI dashboard Microsoft Teams Environments is blank

### ISSUE THREAD

**Issue by NPrice99** [microsoft/powerapps-tools#573] opened 2020-11-16 21:57 UTC
**Describe the bug**

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [e.g. Core, Nurture]  CORE
 - Version [e.g. 1.29]  1.71
 - App or Flow [e.g. Sync Template (v2)]  POwerBI 

**To Reproduce**
1. run Sync flows 
2. Start PowerBI desktop
3. Show Dashboard-PowerPlatformAdminDashboard-2020-11-16

**Expected behavior**
AI expect to see some Microsoft Teams Environments.  The Environments Tab says there are 4 Microsoft Teams Envionments.  The Microsoft Teams Environments is blank.

**Screenshots**
![image](https://user-images.githubusercontent.com/8484048/99312819-83e42e80-2856-11eb-8b4a-0355c26d4905.png)

![image](https://user-images.githubusercontent.com/8484048/99312877-98282b80-2856-11eb-9ba9-43466e459043.png)

**Additional context**

**Comment by JeneferM-MSFT** [comment] 2020-11-16 22:02
It appears that the issue is with the filter on the first screen you show. 
Please change that filter as shown here to see if you have teams environments. You'll need to change it for the other environments on this page as well. 
![image](https://user-images.githubusercontent.com/62659043/99313336-3777ff00-2814-11eb-8ac4-a75345b0641c.png)

**Comment by manuelap-msft** [comment] 2020-11-17 11:01
Thanks for spotting this, Nigel! I uploaded a new version just now that should have this filter fixed - here's a direct link to the new version: https://github.com/microsoft/powerapps-tools/raw/master/Administration/CoEStarterKit/Individual%20Components/Dashboard-PowerPlatformAdminDashboard-2020-11-16.pbit

**Comment by manuelap-msft** [comment] 2020-11-17 11:02
Closing this, but let me know if you spot any other issues! Thank you!

**Comment by NPrice99** [comment] 2020-11-17 12:26
Hi Manuela

I have just downloaded the version you created 40 ish minutes ago.

The environments tab now says there are no Microsoft Teams environments :-

[cid:image002.jpg@01D6BCDC.EECD3060]
There are still no environments in the Microsoft Teams Environments Tab either.

Regards

Nigel

**Comment by manuelap-msft** [comment] 2020-11-17 12:30
If you go to aka.ms/ppac > Environments and filter by Microsoft Teams, do you see any Teams environments there?

**Comment by NPrice99** [comment] 2020-11-17 12:32
Yes – I have 2 Teams type environments

**Comment by manuelap-msft** [comment] 2020-11-17 12:45
Ah, I think I know what's happening here!

1. What version of the Core components solution are you on?
1. If you navigate to the Core Components solution and edit the Admin | Sync Template v2, scroll down a bit to the Get Environments action (it's within a scope). Click on "Show advanced options". Does that show **2020-09-01** as the API Version or something lower? Earlier versions of the API don't return Microsoft Teams as the Environment Type, but instead return NotSpecified which is what leads me to think that this is the issue as in your BI screenshot I can see NotSpecified.
![image](https://user-images.githubusercontent.com/55705669/99391481-27265980-28d2-11eb-8c8f-3226441d6e31.png)

If you are seeing an earlier version here, please upgrade to the latest version of the Core components that we also released yesterday.

Before you upgrade, please make sure to remove any unmanaged layers you might have on flows in the solution - if you have unmanaged layers (= that means you've made customizations to the flow), the upgrade won't take effect.
The screenshots here take you through how to check for unmanaged layers, and remove them.
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#installing-updates

**Comment by manuelap-msft** [comment] 2020-11-17 12:45
(re-opened the issue to investigate what's happening here)

**Comment by NPrice99** [comment] 2020-11-17 12:50
When I downloaded the pbit file last night the Environmenst screen was working and at the top it said I had two Microsoft Teams Envvironments.  It was only when I downloaded the version an hour ago it disappeared.  But the Microsoft Teams Tab never worked.

**Comment by NPrice99** [comment] 2020-11-17 12:53
Core Components version = 1.71

[cid:image002.jpg@01D6BCE0.AE5C2960]

Uh Uh !

**Comment by manuelap-msft** [comment] 2020-11-17 12:54
If you included an image, that didn't come through now!

Can you check on the Admin | Sync Template v2 flow that you don't have any unmanaged layers?

**Comment by NPrice99** [comment] 2020-11-17 12:55
Can I change the API Version to 2020-09-01 simply by editing the field ??

**Comment by manuelap-msft** [comment] 2020-11-17 12:57
Unfortunately not, the schema of the output has changed between API versions (some fields have different names, on some fields the structure of data is different) so we had to make some changes further down as well when we insert / update environments into  the Dataverse table.

**Comment by NPrice99** [comment] 2020-11-17 12:57
[cid:image002.jpg@01D6BCE1.3385D280]

**Comment by NPrice99** [comment] 2020-11-17 14:04
In the latest version there are lots of connection references which is playing havoc with my DLP –

[cid:image002.jpg@01D6BCEA.8A0D60B0]
I think some of them are hangovers from when the Solution was developed.

**Comment by manuelap-msft** [comment] 2020-11-17 14:07
Unfortunately, screenshots aren't coming through when you reply via email - can you go straight to https://github.com/microsoft/powerapps-tools/issues/573 and add them here.

There may be a few connection references for the same connector, as there is a limit of how many connections a connection reference can support so we had to duplicate some. But as they are all for the same connector, this shouldn't have an impact on your DLP policy.

However, we did add the Microsoft Teams connector to the sync flows to gather further information about Microsoft Teams environments - that one is new, and included for the first time with this release. I think that's the only connector we added new, so maybe this is the one causing issues if it's not yet included in your DLP policy.

**Comment by NPrice99** [comment] 2020-11-17 14:44
Hi Manuela

Ended up trashing all of my DLPs and flow now works.

Removed all non-manged layers from all of the Flows.

Re-Imported the Solution 1.71.1

All now works !

Thanks for your help.

I would have never found the unmanaged layers issue if you had not told me.

Thanks Again

Nigel

**Comment by manuelap-msft** [comment] 2020-11-17 15:27
YAY! And you are seeing Microsoft Teams environments in the Power BI Dashboard as well now?

Not related to the CoE kit itself, but for info - with the old solution import experience, you had the option to "override customizations" which then got rid of your unmanaged layer as part of the import. This often led to issues as some customers selected this but didn't know it would remove their customizations hence with the modern solution import experience, this option was removed and customers are now responsible for making sure their solution is "ready" to receive the upgrade.

There are a few items on the roadmap to make this easier and add notifications during the import on flows that have customizations and thus won't receive the upgrade etc! The team is going to continue investing and working on making this experience easier.

Closing this issue now but please let us know if you continue to experience other issues!

**Closed by manuelap-msft** 2020-11-17 15:27 UTC
Labels: coestarterkit

**Comment by NPrice99** [comment] 2020-11-17 15:54
Hi Manuela

Yes, all working now.

Lets see what happens when I recreate my DLPs.

Thanks for your help again.

Nigel
