### ISSUE TITLE
[BUG]: You can only import solutions with a package version of 9.1 or earlier into this organization. Also, you can't import any solutions into this organization that were exported from Microsoft Dynamics 365 2011 or earlier.

### ISSUE THREAD

**Issue by StuartBaxter-FabricIT** [microsoft/powerapps-tools#752] opened 2021-02-03 12:53 UTC
**Describe the bug**

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: InnovationBacklog
 - Version 1.17
 - App or Flow: Innvoation Backlog

**To Reproduce**
Create new team
add power apps to team
create first app
navigate to "apps"
click import

[CenterofExcellenceInnovationBacklog_1_17_managed.zip](https://github.com/microsoft/powerapps-tools/files/5918531/CenterofExcellenceInnovationBacklog_1_17_managed.zip)

attempt to install solution

**Expected behavior**

Solution should install

**Screenshots**

![image](https://user-images.githubusercontent.com/78484260/106753405-88351200-6623-11eb-8bdb-12b0aade5335.png)

**Additional context**

**Comment by JeneferM-MSFT** [comment] 2021-02-03 13:05
Hello, can you please share the screenshot of the failure, and also the exact text from the error.

**Comment by StuartBaxter-FabricIT** [comment] 2021-02-03 13:18
[cid:image001.jpg@01D6FA2F.12196770]



Stuart Baxter | Fabric IT
Dynamics 365 Consultant
Stuart.Baxter@fabric-it.com
Signal House, Hulley Road,
​Macclesfield, SK10 2SF
+44 (0) 1625 443 110
Disclaimer

**Comment by JeneferM-MSFT** [comment] 2021-02-03 13:21
Images don't come through if you add the in email, you have to go to GitHub and add them there.

**Comment by StuartBaxter-FabricIT** [comment] 2021-02-03 13:27
I've added an image to my original post

thanks



Stuart Baxter | Fabric IT
Dynamics 365 Consultant
Stuart.Baxter@fabric-it.com
Signal House, Hulley Road,
​Macclesfield, SK10 2SF
+44 (0) 1625 443 110
Disclaimer

**Comment by JeneferM-MSFT** [comment] 2021-02-03 14:22
Thanks, note that our testing has worked and this has worked for other customers, so there is something unique or at least corner going on here. 
Do you see an option to download a log file for the failure?

**Comment by StuartBaxter-FabricIT** [comment] 2021-02-03 14:54
Hi,

There's no option to download a log file, sorry



Stuart Baxter | Fabric IT
Dynamics 365 Consultant
Stuart.Baxter@fabric-it.com
Signal House, Hulley Road,
​Macclesfield, SK10 2SF
+44 (0) 1625 443 110
Disclaimer

**Comment by osbornecc** [comment] 2021-02-03 21:22
I'm receiving this error as well.  The Core Components version trying to import is 1.89.  Our environment database version is 9.1.0000.27039, and is on 2020 release wave 2.  

I saw that the 2021 release wave 1 became available but we are not yet able to apply early updates to any of our environments.  
Is it possible the current Core Components solution was created in a 2021 release wave 1 environment?

Thanks!

**Comment by JeneferM-MSFT** [comment] 2021-02-04 19:09
Hello folks. The product team has asked that you please open a support ticket if that is available to you. 
[Get Support](https://docs.microsoft.com/en-us/power-platform/admin/get-help-support)

If so, please let me know a tracking ID so I can be sure they are connected.

**Comment by shmcarth** [comment] 2021-02-04 19:51
This is by design and the error message is accurate.  What has occured is that the solution was exported from a 9.2 version environment and you are attempting to import it into a 9.1 environment.  We don't support importing a newer solution into an older environment.  The reason you are seeing this issue now is that we are now changing our online versions from v 9.1 to v 9.2 and it is working its way through our safe deployment practices using different stations for each geography.  You should review where you place your development environments to ensure that they are in geographies that represent the oldest versions to ensure you can deploy to newer geographies.  It is invalid to have your source environment in newer geographies and your destination environments in older ones.  A short term workaround (but not formally supported) is to change the version and SolutionPackageVersion to a 9.1 version to unblock this version test.  You may still get dependency issues, so the real action is for you to change where your source environment is located.  If this is an ISV scenario, it is highly recommended that ISVs use the North America Geo because it is at the tail end of our deployments and is one of the last Geos to get updated.  Solutions exported from there will be importable in all other Geos.  The other option is for you to wait until version 9.2 reaches your environment (release 20122).  For more information on our stations and deployments, please see this link: https://docs.microsoft.com/en-us/dynamics365/released-versions/dynamics-365ce#latest-version-availability.  You will see that 9.2.20122 is scheduled for station 5 deployment (including North America) this weekend - I expect this error will not be thrown if you try on Monday morning.

**Comment by StuartBaxter-FabricIT** [comment] 2021-02-04 20:26
Hi,

To clarify, I am attempting to deploy into a Dataverse for Teams environment in the UK.

Does your advice apply in this case?

Thanks

Stuart
________________________________


Stuart Baxter | Fabric IT
Dynamics 365 Consultant
Stuart.Baxter@fabric-it.com
Signal House, Hulley Road,
​Macclesfield, SK10 2SF
+44 (0) 1625 443 110
Disclaimer

**Comment by shmcarth** [comment] 2021-02-04 22:14
It should apply there too, but I would like to investigate.  Can you open a case with support (or send me an environment id if you can find it) and email to my alias here @microsoft.com?

**Comment by StuartBaxter-FabricIT** [comment] 2021-02-05 10:09
Hi,

My environment ID is e48574b4-6508-42a8-81c7-e2c5a6d0af4d

Thanks



Stuart Baxter | Fabric IT
Dynamics 365 Consultant
Stuart.Baxter@fabric-it.com
Signal House, Hulley Road,
​Macclesfield, SK10 2SF
+44 (0) 1625 443 110
Disclaimer

**Comment by JeneferM-MSFT** [comment] 2021-02-08 16:32
Can you folks please try this again and let us know if you are now able to import?

**Comment by osbornecc** [comment] 2021-02-08 16:44
@JeneferM-MSFT, what timing!  I was just checking on my environments.  This morning, I do see the database versions all start with "9.2" in GCC.

I haven't fully finished importing Core Components 1.89 yet, but I did get past the version error.
Thank you.

**Comment by StuartBaxter-FabricIT** [comment] 2021-02-08 17:01
Hi,

I am still seeing the same issue as before

Is this perhaps because I am in Europe as opposed to USA?



Stuart Baxter | Fabric IT
Dynamics 365 Consultant
Stuart.Baxter@fabric-it.com
Signal House, Hulley Road,
​Macclesfield, SK10 2SF
+44 (0) 1625 443 110
Disclaimer

**Comment by JeneferM-MSFT** [comment] 2021-02-09 18:32
Hey folks. Looks like a product fix will be available in a couple weeks to make this work for those few of you still struggling with it. I will check back at the beginning of March on you.

**Comment by dylanwauters** [comment] 2021-02-11 09:42
same issue here

**Comment by JeneferM-MSFT** [comment] 2021-03-02 16:15
Hi everyone. This is working now for us in our testing. Can you all please give it a try again?

**Comment by JeneferM-MSFT** [comment] 2021-03-03 16:34
closing out issues without further action items on our side

**Closed by JeneferM-MSFT** 2021-03-03 16:34 UTC
Labels: coestarterkit
