### ISSUE TITLE
[BUG]: Receive the "AF20052" error wen running job [Child] Admin | Sync Logs

### ISSUE THREAD

**Issue by rafaelkhalilyullov** [microsoft/powerapps-tools#577] opened 2020-11-17 19:46 UTC
**Describe the bug**
I've completed all steps from the instruction of setting up the audit log  using Option 1 (Option 1: Connect to the audit log by using an Azure AD app registration)
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog
And when I start the 'Admin | Sync Audit Logs' flow for all child flows ('[Child] Admin | Sync Logs flow') I receive the same error:

```
  "error": {
    "code": "AF20052",
    "message": "Blob key [some long string]$audit_general$Audit_General$emea0012 in the url is invalid"
  }
```

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution:  Center of Excellence - Audit Logs
 - Version: 1.0.0.17
 - Flow: [Child] Admin | Sync Logs

**To Reproduce**
1. Open this official instruction: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog 
2. Follow the approach 'Option 1: Connect to the audit log by using an Azure AD app registration'
3. Receive the error

**Expected behavior**
After completing the all steps from instructions both jobs run successfully without errors

**Screenshots**
Please find the screenshot attached

**Additional context**
We are trying to establish and adopt the CoE in our organization.
<img width="960" alt="CoE Audit Logs Flow Error" src="https://user-images.githubusercontent.com/55822339/99439733-a2b1f600-2926-11eb-870e-8af43f3b4f94.png">

**Comment by JeneferM-MSFT** [comment] 2020-11-17 19:51
Hello, we have a flaw in our documentation which we are addressing. 

Please edit the Admin | Sync Audit Logs flow (not the child flow) and enter your tenant ID in the variable designated for it
![image](https://user-images.githubusercontent.com/55705669/97887546-fa930f00-1d21-11eb-971a-9469bf28ad9c.png)

Duplicate of #552

**Closed by JeneferM-MSFT** 2020-11-17 19:51 UTC
Labels: coestarterkit

**Comment by rafaelkhalilyullov** [comment] 2020-11-17 20:22
Thank you a lot!

**Comment by JeneferM-MSFT** [comment] 2020-11-17 20:24
You are most welcome! Thanks for using CoE!
